import Blanc.Lift.ConsolidationRequest.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 0..3, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.ConsolidationRequest

open Jaune

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0xe7 [.unk, .unk, .unk] t_00e7_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x146 [.unk] t_0146_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 0 0x173 [.unk, .unk] t_0173_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.ConsolidationRequest
