import Blanc.Lift.CheckAssembly
import Blanc.Lift.ConsolidationRequest.CheckPart0
import Blanc.Lift.ConsolidationRequest.CheckPart1

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Assembles the per-entry decisions of the CheckPart modules.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.ConsolidationRequest

open Jaune

theorem cert_check : Cert.check code cert = true :=
  Cert.check_seven entry_0 entry_1 entry_2 entry_3 entry_4 entry_5 entry_6
    (by decide +kernel)

end Blanc.Lift.ConsolidationRequest
