import Blanc.Lift.ConsolidationRequest.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 4..6, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.ConsolidationRequest

open Jaune

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0x18e [.unk, .unk] t_018e_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0x4d [.unk, .unk, .unk, .unk, .unk] t_004d_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 0 0xe9 [.unk, .unk, .unk, .unk] t_00e9_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.ConsolidationRequest
