import Blanc.Lift.Check
import Blanc.Lift.VyperNonreentrantDeployed.Fixed.Creation.Input

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Creation.Check.cert_check checks the preserved creation input. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed.Creation

open Jaune

-- Code: 18353 bytes, SHA-256: 72c969f0d2164bcc31aadfbf05d2882bf92668e9b0910b91590b78c9d9832308
def code : ByteArray := Blanc.Lift.VyperNonreentrantDeployed.Fixed.Creation.creationCode

def t_0005_c0 : SFunc := (.next (.push [0x01] (by decide)) (.next (.push [0x01] (by decide)) (.next (.reg .sstore) (.next (.push [0x47, 0x90] (by decide)) (.next (.push [0x00, 0x1b] (by decide)) (.next (.push [0x00, 0x00] (by decide)) (.next (.reg .codecopy) (.next (.push [0x47, 0x90] (by decide)) (.next (.push [0x00, 0x00] (by decide)) (.last .return_))))))))))
def t_47ac_c0 : SFunc := (.dest (.next (.push [0x00] (by decide)) (.next (.reg (.dup 0)) (.last .revert))))
def t_0000_c0 : SFunc := (.next (.reg .callvalue) (.next (.push [0x47, 0xac] (by decide)) (.branch t_0005_c0 t_47ac_c0)))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.VyperNonreentrantDeployed.Fixed.Creation
