import Blanc.Lift.VyperNonreentrantDeployed.Fixed.Cert
import Blanc.Lift.CheckFast

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Each entry is decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune

/-- Depth 15 covers all 18320 runtime byte positions. -/
def codeTries : CodeTries code 15 :=
  CodeTries.ofCode code 15 (by decide +kernel) (by decide +kernel)

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0x52 [.unk] t_0052_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x13a [.unk, .unk, .unk] t_013a_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 0 0x297 [.unk, .unk, .unk] t_0297_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0x538 [.unk, .unk] t_0538_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0x544 [.unk] t_0544_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 0 0x65e [.unk] t_065e_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_7 :
    checkNode code (Cert.entries cert) 0 0xa2f [.unk] t_0a2f_c7 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_8 :
    checkNode code (Cert.entries cert) 0 0xab2 [.unk, .unk] t_0ab2_c8 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_9 :
    checkNode code (Cert.entries cert) 0 0xb33 [.unk, .unk] t_0b33_c9 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_10 :
    checkNode code (Cert.entries cert) 0 0xb6c [.unk] t_0b6c_c10 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_11 :
    checkNode code (Cert.entries cert) 0 0xdf9 [.unk, .unk, .unk, .unk] t_0df9_c11 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_12 :
    checkNode code (Cert.entries cert) 0 0x102c [.unk] t_102c_c12 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_13 :
    checkNode code (Cert.entries cert) 0 0x1363 [.unk] t_1363_c13 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_14 :
    checkNode code (Cert.entries cert) 0 0x187a [.unk, .unk, .unk] t_187a_c14 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_15 :
    checkNode code (Cert.entries cert) 0 0x1909 [.unk] t_1909_c15 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_16 :
    checkNode code (Cert.entries cert) 0 0x1b9e [.unk] t_1b9e_c16 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_17 :
    checkNode code (Cert.entries cert) 0 0x1d7f [.unk, .unk, .unk, .unk] t_1d7f_c17 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_18 :
    checkNode code (Cert.entries cert) 0 0x1d8b [.unk, .unk, .unk] t_1d8b_c18 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_19 :
    checkNode code (Cert.entries cert) 0 0x1e99 [.unk] t_1e99_c19 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_20 :
    checkNode code (Cert.entries cert) 0 0x20a7 [.unk, .unk, .unk] t_20a7_c20 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_21 :
    checkNode code (Cert.entries cert) 0 0x238b [.unk] t_238b_c21 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_22 :
    checkNode code (Cert.entries cert) 0 0x23fc [.unk, .unk] t_23fc_c22 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_23 :
    checkNode code (Cert.entries cert) 0 0x2408 [.unk] t_2408_c23 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_24 :
    checkNode code (Cert.entries cert) 0 0x24e9 [.unk] t_24e9_c24 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_25 :
    checkNode code (Cert.entries cert) 0 0x2712 [.unk, .unk] t_2712_c25 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_26 :
    checkNode code (Cert.entries cert) 0 0x271e [.unk] t_271e_c26 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_27 :
    checkNode code (Cert.entries cert) 0 0x2843 [.unk, .unk] t_2843_c27 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_28 :
    checkNode code (Cert.entries cert) 0 0x288f [.unk] t_288f_c28 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_29 :
    checkNode code (Cert.entries cert) 0 0x2a2a [.unk] t_2a2a_c29 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_30 :
    checkNode code (Cert.entries cert) 0 0x2a98 [.unk, .unk] t_2a98_c30 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_31 :
    checkNode code (Cert.entries cert) 0 0x2aa3 [.unk] t_2aa3_c31 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_32 :
    checkNode code (Cert.entries cert) 0 0x2bd9 [.unk, .unk] t_2bd9_c32 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_33 :
    checkNode code (Cert.entries cert) 0 0x2f12 [.unk, .unk, .unk, .unk, .unk, .unk, .unk] t_2f12_c33 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_34 :
    checkNode code (Cert.entries cert) 0 0x3104 [] t_3104_c34 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_35 :
    checkNode code (Cert.entries cert) 0 0x332b [.unk, .ret] t_332b_c35 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_36 :
    checkNode code (Cert.entries cert) 0 0x34d2 [.ret] t_34d2_c36 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_37 :
    checkNode code (Cert.entries cert) 0 0x3748 [.unk, .unk, .unk, .ret] t_3748_c37 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_38 :
    checkNode code (Cert.entries cert) 0 0x375a [.ret] t_375a_c38 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_39 :
    checkNode code (Cert.entries cert) 0 0x3be8 [.unk, .unk, .unk, .unk, .ret] t_3be8_c39 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_40 :
    checkNode code (Cert.entries cert) 0 0x3bf0 [.ret] t_3bf0_c40 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_41 :
    checkNode code (Cert.entries cert) 0 0x3d59 [.ret] t_3d59_c41 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_42 :
    checkNode code (Cert.entries cert) 0 0x3dae [.ret] t_3dae_c42 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_43 :
    checkNode code (Cert.entries cert) 0 0x3e7e [.unk, .ret] t_3e7e_c43 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_44 :
    checkNode code (Cert.entries cert) 0 0x3ef8 [.unk, .unk, .unk, .ret] t_3ef8_c44 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_45 :
    checkNode code (Cert.entries cert) 0 0x3f54 [.unk, .unk, .unk, .ret] t_3f54_c45 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_46 :
    checkNode code (Cert.entries cert) 0 0x40e5 [.unk, .unk, .unk, .ret] t_40e5_c46 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_47 :
    checkNode code (Cert.entries cert) 0 0x40f7 [.ret] t_40f7_c47 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_48 :
    checkNode code (Cert.entries cert) 0 0x41c1 [.unk, .unk, .unk, .ret] t_41c1_c48 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_49 :
    checkNode code (Cert.entries cert) 0 0x434d [.unk, .unk, .unk, .ret] t_434d_c49 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_50 :
    checkNode code (Cert.entries cert) 0 0x435f [.ret] t_435f_c50 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_51 :
    checkNode code (Cert.entries cert) 0 0x458d [.unk, .unk, .unk, .ret] t_458d_c51 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_52 :
    checkNode code (Cert.entries cert) 0 0x4751 [.unk, .ret] t_4751_c52 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_53 :
    checkNode code (Cert.entries cert) 0 0xc85 [.unk, .unk, .unk] t_0c85_c53 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_54 :
    checkNode code (Cert.entries cert) 0 0x310a [.unk, .ret] t_310a_c54 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_55 :
    checkNode code (Cert.entries cert) 0 0xde0 [.unk, .unk, .unk, .unk] t_0de0_c55 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_56 :
    checkNode code (Cert.entries cert) 0 0x314e [.ret] t_314e_c56 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_57 :
    checkNode code (Cert.entries cert) 0 0x31ce [.unk, .ret] t_31ce_c57 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_58 :
    checkNode code (Cert.entries cert) 0 0x333b [.unk, .ret] t_333b_c58 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_59 :
    checkNode code (Cert.entries cert) 0 0x33af [.unk, .ret] t_33af_c59 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_60 :
    checkNode code (Cert.entries cert) 0 0x34d4 [.unk, .ret] t_34d4_c60 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_61 :
    checkNode code (Cert.entries cert) 0 0x355b [.unk, .ret] t_355b_c61 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_62 :
    checkNode code (Cert.entries cert) 0 0x37bf [.unk, .ret] t_37bf_c62 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_63 :
    checkNode code (Cert.entries cert) 0 0x3bf2 [.unk, .ret] t_3bf2_c63 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_64 :
    checkNode code (Cert.entries cert) 0 0x375c [.unk, .ret] t_375c_c64 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_65 :
    checkNode code (Cert.entries cert) 0 0x3df1 [.unk, .ret] t_3df1_c65 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_66 :
    checkNode code (Cert.entries cert) 0 0x4361 [.unk, .ret] t_4361_c66 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_67 :
    checkNode code (Cert.entries cert) 0 0x2efb [.unk, .unk, .unk, .unk, .unk, .unk, .unk] t_2efb_c67 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_68 :
    checkNode code (Cert.entries cert) 0 0x10c [.unk, .unk, .unk] t_010c_c68 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_69 :
    checkNode code (Cert.entries cert) 0 0x1ec [.unk, .unk, .unk] t_01ec_c69 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_70 :
    checkNode code (Cert.entries cert) 0 0x3db0 [.ret] t_3db0_c70 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_71 :
    checkNode code (Cert.entries cert) 0 0x17fc [.unk, .unk, .unk] t_17fc_c71 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_72 :
    checkNode code (Cert.entries cert) 0 0x1bdb [.unk, .unk, .unk] t_1bdb_c72 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_73 :
    checkNode code (Cert.entries cert) 0 0x1f4d [.unk, .unk, .unk] t_1f4d_c73 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_74 :
    checkNode code (Cert.entries cert) 0 0x1ffc [.unk, .unk, .unk] t_1ffc_c74 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_75 :
    checkNode code (Cert.entries cert) 0 0x3d5b [.ret] t_3d5b_c75 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_76 :
    checkNode code (Cert.entries cert) 0 0x35c7 [.unk, .unk, .unk, .ret] t_35c7_c76 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_77 :
    checkNode code (Cert.entries cert) 0 0x3eab [.unk, .unk, .unk, .ret] t_3eab_c77 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_78 :
    checkNode code (Cert.entries cert) 0 0x3ffa [.unk, .unk, .unk, .ret] t_3ffa_c78 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_79 :
    checkNode code (Cert.entries cert) 0 0x4137 [.unk, .unk, .unk, .ret] t_4137_c79 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_80 :
    checkNode code (Cert.entries cert) 0 0x4263 [.unk, .unk, .unk, .ret] t_4263_c80 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_81 :
    checkNode code (Cert.entries cert) 0 0x44d1 [.unk, .unk, .unk, .ret] t_44d1_c81 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_82 :
    checkNode code (Cert.entries cert) 0 0x40f9 [.unk, .ret] t_40f9_c82 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_83 :
    checkNode code (Cert.entries cert) 0 0x34e0 [.unk, .unk, .unk, .ret] t_34e0_c83 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_84 :
    checkNode code (Cert.entries cert) 0 0x3566 [.unk, .unk, .unk, .ret] t_3566_c84 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_85 :
    checkNode code (Cert.entries cert) 0 0x37e7 [.unk, .unk, .unk, .ret] t_37e7_c85 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_86 :
    checkNode code (Cert.entries cert) 0 0x38ee [.unk, .ret] t_38ee_c86 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_87 :
    checkNode code (Cert.entries cert) 0 0x4168 [.unk, .unk, .unk, .ret] t_4168_c87 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem cert_check : Cert.check code cert = true := by
  unfold Cert.check
  rw [Bool.and_eq_true]
  refine ⟨by decide +kernel, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact entry_0
  · exact entry_1
  · exact entry_2
  · exact entry_3
  · exact entry_4
  · exact entry_5
  · exact entry_6
  · exact entry_7
  · exact entry_8
  · exact entry_9
  · exact entry_10
  · exact entry_11
  · exact entry_12
  · exact entry_13
  · exact entry_14
  · exact entry_15
  · exact entry_16
  · exact entry_17
  · exact entry_18
  · exact entry_19
  · exact entry_20
  · exact entry_21
  · exact entry_22
  · exact entry_23
  · exact entry_24
  · exact entry_25
  · exact entry_26
  · exact entry_27
  · exact entry_28
  · exact entry_29
  · exact entry_30
  · exact entry_31
  · exact entry_32
  · exact entry_33
  · exact entry_34
  · exact entry_35
  · exact entry_36
  · exact entry_37
  · exact entry_38
  · exact entry_39
  · exact entry_40
  · exact entry_41
  · exact entry_42
  · exact entry_43
  · exact entry_44
  · exact entry_45
  · exact entry_46
  · exact entry_47
  · exact entry_48
  · exact entry_49
  · exact entry_50
  · exact entry_51
  · exact entry_52
  · exact entry_53
  · exact entry_54
  · exact entry_55
  · exact entry_56
  · exact entry_57
  · exact entry_58
  · exact entry_59
  · exact entry_60
  · exact entry_61
  · exact entry_62
  · exact entry_63
  · exact entry_64
  · exact entry_65
  · exact entry_66
  · exact entry_67
  · exact entry_68
  · exact entry_69
  · exact entry_70
  · exact entry_71
  · exact entry_72
  · exact entry_73
  · exact entry_74
  · exact entry_75
  · exact entry_76
  · exact entry_77
  · exact entry_78
  · exact entry_79
  · exact entry_80
  · exact entry_81
  · exact entry_82
  · exact entry_83
  · exact entry_84
  · exact entry_85
  · exact entry_86
  · exact entry_87

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
