import Blanc.Lift.VyperNonreentrantDeployed.Fixed.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 0..12, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune

theorem entry_0_piece_0 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x8 [] t_0008_c0 = true := by
  decide +kernel

theorem entry_0_piece_1 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1e [.unk] t_001e_c0 = true := by
  decide +kernel

theorem entry_0_piece_2 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x3b [.unk] t_003b_c0 = true := by
  decide +kernel

theorem entry_0_piece_3 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x62a [.unk] t_062a_c0 = true := by
  decide +kernel

theorem entry_0_piece_4 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x647 [.unk] t_0647_c0 = true := by
  decide +kernel

theorem entry_0_piece_5 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xbd0 [.unk] t_0bd0_c0 = true := by
  decide +kernel

theorem entry_0_piece_6 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xf27 [.unk] t_0f27_c0 = true := by
  decide +kernel

theorem entry_0_piece_7 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xf6b [.unk] t_0f6b_c0 = true := by
  decide +kernel

theorem entry_0_piece_8 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1045 [.unk] t_1045_c0 = true := by
  decide +kernel

theorem entry_0_piece_9 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x10c4 [.unk] t_10c4_c0 = true := by
  decide +kernel

theorem entry_0_piece_10 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x13f2 [.unk] t_13f2_c0 = true := by
  decide +kernel

theorem entry_0_piece_11 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1423 [.unk] t_1423_c0 = true := by
  decide +kernel

theorem entry_0_piece_12 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1448 [.unk] t_1448_c0 = true := by
  decide +kernel

theorem entry_0_piece_13 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x146d [.unk] t_146d_c0 = true := by
  decide +kernel

theorem entry_0_piece_14 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x14a7 [.unk] t_14a7_c0 = true := by
  decide +kernel

theorem entry_0_piece_15 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x14c9 [.unk] t_14c9_c0 = true := by
  decide +kernel

theorem entry_0_piece_16 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x14f8 [.unk] t_14f8_c0 = true := by
  decide +kernel

theorem entry_0_piece_17 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x151b [.unk] t_151b_c0 = true := by
  decide +kernel

theorem entry_0_piece_18 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1612 [.unk] t_1612_c0 = true := by
  decide +kernel

theorem entry_0_piece_19 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1641 [.unk] t_1641_c0 = true := by
  decide +kernel

theorem entry_0_piece_20 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1751 [.unk] t_1751_c0 = true := by
  decide +kernel

theorem entry_0_piece_21 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x194c [.unk] t_194c_c0 = true := by
  decide +kernel

theorem entry_0_piece_22 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1b6c [.unk] t_1b6c_c0 = true := by
  decide +kernel

theorem entry_0_piece_23 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1b88 [.unk] t_1b88_c0 = true := by
  decide +kernel

theorem entry_0_piece_24 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1e65 [.unk] t_1e65_c0 = true := by
  decide +kernel

theorem entry_0_piece_25 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1e82 [.unk] t_1e82_c0 = true := by
  decide +kernel

theorem entry_0_piece_26 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2470 [.unk] t_2470_c0 = true := by
  decide +kernel

theorem entry_0_piece_27 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x24b5 [.unk] t_24b5_c0 = true := by
  decide +kernel

theorem entry_0_piece_28 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x24d2 [.unk] t_24d2_c0 = true := by
  decide +kernel

theorem entry_0_piece_29 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2785 [.unk] t_2785_c0 = true := by
  decide +kernel

theorem entry_0_piece_30 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x28f4 [.unk] t_28f4_c0 = true := by
  decide +kernel

theorem entry_0_piece_31 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x29a6 [.unk] t_29a6_c0 = true := by
  decide +kernel

theorem entry_0_piece_32 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2abb [.unk] t_2abb_c0 = true := by
  decide +kernel

theorem entry_0_piece_33 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2b64 [.unk] t_2b64_c0 = true := by
  decide +kernel

theorem entry_0_step_34 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2aaf [.unk] t_2aaf_c0 = true := by
  simp only [t_2aaf_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xa4, 0x8e, 0xac, 0x9d] (by decide)) [.unk] = some [(.const (Nat.toB256 0xa48eac9d)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xa48eac9d)), .unk] = some [.unk, (.const (Nat.toB256 0xa48eac9d)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xa48eac9d)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x2b, 0x64] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x2b64)), .unk, .unk] from by decide, show (Nat.toB256 0x2b64).toNat = 0x2b64 from by decide, entry_0_piece_32, entry_0_piece_33] <;> decide

theorem entry_0_step_35 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x299a [.unk] t_299a_c0 = true := by
  simp only [t_299a_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x30, 0xc5, 0x40, 0x85] (by decide)) [.unk] = some [(.const (Nat.toB256 0x30c54085)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x30c54085)), .unk] = some [.unk, (.const (Nat.toB256 0x30c54085)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x30c54085)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x2a, 0xaf] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x2aaf)), .unk, .unk] from by decide, show (Nat.toB256 0x2aaf).toNat = 0x2aaf from by decide, entry_0_piece_31, entry_0_step_34] <;> decide

theorem entry_0_step_36 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x28e8 [.unk] t_28e8_c0 = true := by
  simp only [t_28e8_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x55, 0x1a, 0x65, 0x88] (by decide)) [.unk] = some [(.const (Nat.toB256 0x551a6588)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x551a6588)), .unk] = some [.unk, (.const (Nat.toB256 0x551a6588)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x551a6588)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x29, 0x9a] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x299a)), .unk, .unk] from by decide, show (Nat.toB256 0x299a).toNat = 0x299a from by decide, entry_0_piece_30, entry_0_step_35] <;> decide

theorem entry_0_step_37 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2779 [.unk] t_2779_c0 = true := by
  simp only [t_2779_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x3c, 0x15, 0x7e, 0x64] (by decide)) [.unk] = some [(.const (Nat.toB256 0x3c157e64)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x3c157e64)), .unk] = some [.unk, (.const (Nat.toB256 0x3c157e64)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x3c157e64)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x28, 0xe8] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x28e8)), .unk, .unk] from by decide, show (Nat.toB256 0x28e8).toNat = 0x28e8 from by decide, entry_0_piece_29, entry_0_step_36] <;> decide

theorem entry_0_step_38 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x24c6 [.unk] t_24c6_c0 = true := by
  simp only [t_24c6_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x08, 0x15, 0x79, 0xa5] (by decide)) [.unk] = some [(.const (Nat.toB256 0x81579a5)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x81579a5)), .unk] = some [.unk, (.const (Nat.toB256 0x81579a5)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x81579a5)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x27, 0x79] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x2779)), .unk, .unk] from by decide, show (Nat.toB256 0x2779).toNat = 0x2779 from by decide, entry_0_piece_28, entry_0_step_37] <;> decide

theorem entry_0_step_39 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x24a9 [.unk] t_24a9_c0 = true := by
  simp only [t_24a9_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x1a, 0x4d, 0x01, 0xd2] (by decide)) [.unk] = some [(.const (Nat.toB256 0x1a4d01d2)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x1a4d01d2)), .unk] = some [.unk, (.const (Nat.toB256 0x1a4d01d2)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x1a4d01d2)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x24, 0xc6] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x24c6)), .unk, .unk] from by decide, show (Nat.toB256 0x24c6).toNat = 0x24c6 from by decide, entry_0_piece_27, entry_0_step_38] <;> decide

theorem entry_0_step_40 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2464 [.unk] t_2464_c0 = true := by
  simp only [t_2464_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xcc, 0x2b, 0x27, 0xd7] (by decide)) [.unk] = some [(.const (Nat.toB256 0xcc2b27d7)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xcc2b27d7)), .unk] = some [.unk, (.const (Nat.toB256 0xcc2b27d7)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xcc2b27d7)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x24, 0xa9] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x24a9)), .unk, .unk] from by decide, show (Nat.toB256 0x24a9).toNat = 0x24a9 from by decide, entry_0_piece_26, entry_0_step_39] <;> decide

theorem entry_0_step_41 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1e76 [.unk] t_1e76_c0 = true := by
  simp only [t_1e76_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x52, 0xd2, 0xcf, 0xdd] (by decide)) [.unk] = some [(.const (Nat.toB256 0x52d2cfdd)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x52d2cfdd)), .unk] = some [.unk, (.const (Nat.toB256 0x52d2cfdd)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x52d2cfdd)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x24, 0x64] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x2464)), .unk, .unk] from by decide, show (Nat.toB256 0x2464).toNat = 0x2464 from by decide, entry_0_piece_25, entry_0_step_40] <;> decide

theorem entry_0_step_42 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1e59 [.unk] t_1e59_c0 = true := by
  simp only [t_1e59_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xe3, 0x10, 0x32, 0x73] (by decide)) [.unk] = some [(.const (Nat.toB256 0xe3103273)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xe3103273)), .unk] = some [.unk, (.const (Nat.toB256 0xe3103273)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xe3103273)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x1e, 0x76] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1e76)), .unk, .unk] from by decide, show (Nat.toB256 0x1e76).toNat = 0x1e76 from by decide, entry_0_piece_24, entry_0_step_41] <;> decide

theorem entry_0_step_43 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1b7c [.unk] t_1b7c_c0 = true := by
  simp only [t_1b7c_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x3e, 0xb1, 0x71, 0x9f] (by decide)) [.unk] = some [(.const (Nat.toB256 0x3eb1719f)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x3eb1719f)), .unk] = some [.unk, (.const (Nat.toB256 0x3eb1719f)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x3eb1719f)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x1e, 0x59] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1e59)), .unk, .unk] from by decide, show (Nat.toB256 0x1e59).toNat = 0x1e59 from by decide, entry_0_piece_23, entry_0_step_42] <;> decide

theorem entry_0_step_44 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1b60 [.unk] t_1b60_c0 = true := by
  simp only [t_1b60_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x5b, 0x36, 0x38, 0x9c] (by decide)) [.unk] = some [(.const (Nat.toB256 0x5b36389c)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x5b36389c)), .unk] = some [.unk, (.const (Nat.toB256 0x5b36389c)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x5b36389c)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x1b, 0x7c] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1b7c)), .unk, .unk] from by decide, show (Nat.toB256 0x1b7c).toNat = 0x1b7c from by decide, entry_0_piece_22, entry_0_step_43] <;> decide

theorem entry_0_step_45 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1940 [.unk] t_1940_c0 = true := by
  simp only [t_1940_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x5e, 0x0d, 0x44, 0x3f] (by decide)) [.unk] = some [(.const (Nat.toB256 0x5e0d443f)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x5e0d443f)), .unk] = some [.unk, (.const (Nat.toB256 0x5e0d443f)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x5e0d443f)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x1b, 0x60] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1b60)), .unk, .unk] from by decide, show (Nat.toB256 0x1b60).toNat = 0x1b60 from by decide, entry_0_piece_21, entry_0_step_44] <;> decide

theorem entry_0_step_46 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1745 [.unk] t_1745_c0 = true := by
  simp only [t_1745_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xed, 0x8e, 0x84, 0xf3] (by decide)) [.unk] = some [(.const (Nat.toB256 0xed8e84f3)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xed8e84f3)), .unk] = some [.unk, (.const (Nat.toB256 0xed8e84f3)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xed8e84f3)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x19, 0x40] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1940)), .unk, .unk] from by decide, show (Nat.toB256 0x1940).toNat = 0x1940 from by decide, entry_0_piece_20, entry_0_step_45] <;> decide

theorem entry_0_step_47 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1635 [.unk] t_1635_c0 = true := by
  simp only [t_1635_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xbb, 0x7b, 0x8b, 0x80] (by decide)) [.unk] = some [(.const (Nat.toB256 0xbb7b8b80)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xbb7b8b80)), .unk] = some [.unk, (.const (Nat.toB256 0xbb7b8b80)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xbb7b8b80)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x17, 0x45] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1745)), .unk, .unk] from by decide, show (Nat.toB256 0x1745).toNat = 0x1745 from by decide, entry_0_piece_19, entry_0_step_46] <;> decide

theorem entry_0_step_48 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1606 [.unk] t_1606_c0 = true := by
  simp only [t_1606_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x86, 0xfc, 0x88, 0xd3] (by decide)) [.unk] = some [(.const (Nat.toB256 0x86fc88d3)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x86fc88d3)), .unk] = some [.unk, (.const (Nat.toB256 0x86fc88d3)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x86fc88d3)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x16, 0x35] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1635)), .unk, .unk] from by decide, show (Nat.toB256 0x1635).toNat = 0x1635 from by decide, entry_0_piece_18, entry_0_step_47] <;> decide

theorem entry_0_step_49 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x150f [.unk] t_150f_c0 = true := by
  simp only [t_150f_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xf2, 0x38, 0x8a, 0xcb] (by decide)) [.unk] = some [(.const (Nat.toB256 0xf2388acb)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xf2388acb)), .unk] = some [.unk, (.const (Nat.toB256 0xf2388acb)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xf2388acb)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x16, 0x06] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1606)), .unk, .unk] from by decide, show (Nat.toB256 0x1606).toNat = 0x1606 from by decide, entry_0_piece_17, entry_0_step_48] <;> decide

theorem entry_0_step_50 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x14ec [.unk] t_14ec_c0 = true := by
  simp only [t_14ec_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x76, 0xa2, 0xf0, 0xf0] (by decide)) [.unk] = some [(.const (Nat.toB256 0x76a2f0f0)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x76a2f0f0)), .unk] = some [.unk, (.const (Nat.toB256 0x76a2f0f0)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x76a2f0f0)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x15, 0x0f] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x150f)), .unk, .unk] from by decide, show (Nat.toB256 0x150f).toNat = 0x150f from by decide, entry_0_piece_16, entry_0_step_49] <;> decide

theorem entry_0_step_51 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x14bd [.unk] t_14bd_c0 = true := by
  simp only [t_14bd_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xf4, 0x46, 0xc1, 0xd0] (by decide)) [.unk] = some [(.const (Nat.toB256 0xf446c1d0)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xf446c1d0)), .unk] = some [.unk, (.const (Nat.toB256 0xf446c1d0)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xf446c1d0)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x14, 0xec] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x14ec)), .unk, .unk] from by decide, show (Nat.toB256 0x14ec).toNat = 0x14ec from by decide, entry_0_piece_15, entry_0_step_50] <;> decide

theorem entry_0_step_52 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x149b [.unk] t_149b_c0 = true := by
  simp only [t_149b_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xfe, 0xe3, 0xf7, 0xf9] (by decide)) [.unk] = some [(.const (Nat.toB256 0xfee3f7f9)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xfee3f7f9)), .unk] = some [.unk, (.const (Nat.toB256 0xfee3f7f9)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xfee3f7f9)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x14, 0xbd] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x14bd)), .unk, .unk] from by decide, show (Nat.toB256 0x14bd).toNat = 0x14bd from by decide, entry_0_piece_14, entry_0_step_51] <;> decide

theorem entry_0_step_53 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1461 [.unk] t_1461_c0 = true := by
  simp only [t_1461_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x49, 0x03, 0xb0, 0xd1] (by decide)) [.unk] = some [(.const (Nat.toB256 0x4903b0d1)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x4903b0d1)), .unk] = some [.unk, (.const (Nat.toB256 0x4903b0d1)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x4903b0d1)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x14, 0x9b] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x149b)), .unk, .unk] from by decide, show (Nat.toB256 0x149b).toNat = 0x149b from by decide, entry_0_piece_13, entry_0_step_52] <;> decide

theorem entry_0_step_54 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x143c [.unk] t_143c_c0 = true := by
  simp only [t_143c_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xfd, 0x06, 0x84, 0xb1] (by decide)) [.unk] = some [(.const (Nat.toB256 0xfd0684b1)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xfd0684b1)), .unk] = some [.unk, (.const (Nat.toB256 0xfd0684b1)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xfd0684b1)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x14, 0x61] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1461)), .unk, .unk] from by decide, show (Nat.toB256 0x1461).toNat = 0x1461 from by decide, entry_0_piece_12, entry_0_step_53] <;> decide

theorem entry_0_step_55 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1417 [.unk] t_1417_c0 = true := by
  simp only [t_1417_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xc2, 0x4c, 0x7c, 0x29] (by decide)) [.unk] = some [(.const (Nat.toB256 0xc24c7c29)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xc24c7c29)), .unk] = some [.unk, (.const (Nat.toB256 0xc24c7c29)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xc24c7c29)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x14, 0x3c] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x143c)), .unk, .unk] from by decide, show (Nat.toB256 0x143c).toNat = 0x143c from by decide, entry_0_piece_11, entry_0_step_54] <;> decide

theorem entry_0_step_56 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x13e6 [.unk] t_13e6_c0 = true := by
  simp only [t_13e6_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xfd, 0xe6, 0x25, 0xe6] (by decide)) [.unk] = some [(.const (Nat.toB256 0xfde625e6)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xfde625e6)), .unk] = some [.unk, (.const (Nat.toB256 0xfde625e6)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xfde625e6)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x14, 0x17] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1417)), .unk, .unk] from by decide, show (Nat.toB256 0x1417).toNat = 0x1417 from by decide, entry_0_piece_10, entry_0_step_55] <;> decide

theorem entry_0_step_57 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x10b8 [.unk] t_10b8_c0 = true := by
  simp only [t_10b8_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xd5, 0x05, 0xac, 0xcf] (by decide)) [.unk] = some [(.const (Nat.toB256 0xd505accf)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xd505accf)), .unk] = some [.unk, (.const (Nat.toB256 0xd505accf)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xd505accf)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x13, 0xe6] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x13e6)), .unk, .unk] from by decide, show (Nat.toB256 0x13e6).toNat = 0x13e6 from by decide, entry_0_piece_9, entry_0_step_56] <;> decide

theorem entry_0_step_58 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x1039 [.unk] t_1039_c0 = true := by
  simp only [t_1039_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x09, 0x5e, 0xa7, 0xb3] (by decide)) [.unk] = some [(.const (Nat.toB256 0x95ea7b3)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x95ea7b3)), .unk] = some [.unk, (.const (Nat.toB256 0x95ea7b3)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x95ea7b3)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x10, 0xb8] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x10b8)), .unk, .unk] from by decide, show (Nat.toB256 0x10b8).toNat = 0x10b8 from by decide, entry_0_piece_8, entry_0_step_57] <;> decide

theorem entry_0_step_59 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xf5f [.unk] t_0f5f_c0 = true := by
  simp only [t_0f5f_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x23, 0xb8, 0x72, 0xdd] (by decide)) [.unk] = some [(.const (Nat.toB256 0x23b872dd)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x23b872dd)), .unk] = some [.unk, (.const (Nat.toB256 0x23b872dd)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x23b872dd)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x10, 0x39] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x1039)), .unk, .unk] from by decide, show (Nat.toB256 0x1039).toNat = 0x1039 from by decide, entry_0_piece_7, entry_0_step_58] <;> decide

theorem entry_0_step_60 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xf1b [.unk] t_0f1b_c0 = true := by
  simp only [t_0f1b_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xa9, 0x05, 0x9c, 0xbb] (by decide)) [.unk] = some [(.const (Nat.toB256 0xa9059cbb)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xa9059cbb)), .unk] = some [.unk, (.const (Nat.toB256 0xa9059cbb)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xa9059cbb)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x0f, 0x5f] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0xf5f)), .unk, .unk] from by decide, show (Nat.toB256 0xf5f).toNat = 0xf5f from by decide, entry_0_piece_6, entry_0_step_59] <;> decide

theorem entry_0_step_61 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xbc5 [.unk] t_0bc5_c0 = true := by
  simp only [t_0bc5_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xa4, 0x61, 0xb3, 0xc8] (by decide)) [.unk] = some [(.const (Nat.toB256 0xa461b3c8)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xa461b3c8)), .unk] = some [.unk, (.const (Nat.toB256 0xa461b3c8)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xa461b3c8)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x0f, 0x1b] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0xf1b)), .unk, .unk] from by decide, show (Nat.toB256 0xf1b).toNat = 0xf1b from by decide, entry_0_piece_5, entry_0_step_60] <;> decide

theorem entry_0_piece_62 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x477e [.unk] t_477e_c0 = true := by
  decide +kernel

theorem entry_0_step_63 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xbbf [.unk] t_0bbf_c0 = true := by
  simp only [t_0bbf_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.reg .callvalue) [.unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x47, 0x7e] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x477e)), .unk, .unk] from by decide, show (Nat.toB256 0x477e).toNat = 0x477e from by decide, entry_0_step_61, entry_0_piece_62] <;> decide

theorem entry_0_step_64 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x63b [.unk] t_063b_c0 = true := by
  simp only [t_063b_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0xdd, 0xc1, 0xf5, 0x9d] (by decide)) [.unk] = some [(.const (Nat.toB256 0xddc1f59d)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xddc1f59d)), .unk] = some [.unk, (.const (Nat.toB256 0xddc1f59d)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xddc1f59d)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x0b, 0xbf] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0xbbf)), .unk, .unk] from by decide, show (Nat.toB256 0xbbf).toNat = 0xbbf from by decide, entry_0_piece_4, entry_0_step_63] <;> decide

theorem entry_0_step_65 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x61e [.unk] t_061e_c0 = true := by
  simp only [t_061e_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x3d, 0xf0, 0x21, 0x24] (by decide)) [.unk] = some [(.const (Nat.toB256 0x3df02124)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0x3df02124)), .unk] = some [.unk, (.const (Nat.toB256 0x3df02124)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0x3df02124)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x06, 0x3b] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x63b)), .unk, .unk] from by decide, show (Nat.toB256 0x63b).toNat = 0x63b from by decide, entry_0_piece_3, entry_0_step_64] <;> decide

theorem entry_0_step_66 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x2f [.unk] t_002f_c0 = true := by
  simp only [t_002f_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x0c, 0x3e, 0x4b, 0x54] (by decide)) [.unk] = some [(.const (Nat.toB256 0xc3e4b54)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xc3e4b54)), .unk] = some [.unk, (.const (Nat.toB256 0xc3e4b54)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xc3e4b54)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x06, 0x1e] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x61e)), .unk, .unk] from by decide, show (Nat.toB256 0x61e).toNat = 0x61e from by decide, entry_0_piece_2, entry_0_step_65] <;> decide

theorem entry_0_step_67 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0xc [] t_000c_c0 = true := by
  simp only [t_000c_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x00] (by decide)) [] = some [(.const (Nat.toB256 0x0))] from by decide, show absNinst (.reg .calldataload) [(.const (Nat.toB256 0x0))] = some [.unk] from by decide, show absNinst (.push [0xe0] (by decide)) [.unk] = some [(.const (Nat.toB256 0xe0)), .unk] from by decide, show absNinst (.reg .shr) [(.const (Nat.toB256 0xe0)), .unk] = some [.unk] from by decide, show absNinst (.push [0x0b, 0x4c, 0x7e, 0x4d] (by decide)) [.unk] = some [(.const (Nat.toB256 0xb4c7e4d)), .unk] from by decide, show absNinst (.reg (.dup 1)) [(.const (Nat.toB256 0xb4c7e4d)), .unk] = some [.unk, (.const (Nat.toB256 0xb4c7e4d)), .unk] from by decide, show absNinst (.reg .xor) [.unk, (.const (Nat.toB256 0xb4c7e4d)), .unk] = some [.unk, .unk] from by decide, show absNinst (.push [0x00, 0x2f] (by decide)) [.unk, .unk] = some [(.const (Nat.toB256 0x2f)), .unk, .unk] from by decide, show (Nat.toB256 0x2f).toNat = 0x2f from by decide, entry_0_piece_1, entry_0_step_66] <;> decide

theorem entry_0_step_68 :
    checkNodeT code 15 codeTries.bytes (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  simp only [t_0000_c0, checkNodeT, AVal.jumps?, Ninst.size, Ninst.pcFree, Ninst.toBytes, Rinst.toUInt8, Xinst.toUInt8, pushToB8L, bytesAtT, LTrie.get?, List.length_cons, List.length_nil, Nat.reduceAdd, zero_add, Fin.isValue, Fin.coe_ofNat_eq_mod, Nat.one_mod, Nat.toUInt8_eq, UInt8.ofNat_one, UInt8.reduceAdd, Bool.and_eq_true, beq_iff_eq, B256.toNat_toB256_of_lt, Bool.true_and, Bool.and_true, Bool.false_or, Bool.or_false, Bool.true_or, Bool.or_true, Bool.false_and, Bool.and_false, show ((none : Option Bool) == some true) = false from by decide, show ((none : Option Bool) == some false) = false from by decide, show absNinst (.push [0x03] (by decide)) [] = some [(.const (Nat.toB256 0x3))] from by decide, show absNinst (.reg .calldatasize) [(.const (Nat.toB256 0x3))] = some [.unk, (.const (Nat.toB256 0x3))] from by decide, show absNinst (.reg .gt) [.unk, (.const (Nat.toB256 0x3))] = some [.unk] from by decide, show absNinst (.push [0x00, 0x0c] (by decide)) [.unk] = some [(.const (Nat.toB256 0xc)), .unk] from by decide, show (Nat.toB256 0xc).toNat = 0xc from by decide, entry_0_piece_0, entry_0_step_67] <;> decide

/-- Entry 0 has 3992 tree nodes, above the `--check-split-nodes 1000` budget (`CHECK_SPLIT_NODE_BUDGET`, scripts/lift/lift.py): split at unknown-condition branches into pieces at or below the budget, each its own kernel decision, and composed by rewriting with the branch lemmas (one small step per connector, `entry_0_step_*`) instead of one whole-tree decision. -/
theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  exact entry_0_step_68

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0x52 [.unk] t_0052_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x13a [.unk, .unk, .unk] t_013a_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 0 0x297 [.unk, .unk, .unk] t_0297_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0x538 [.unk, .unk] t_0538_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0x544 [.unk] t_0544_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 0 0x65e [.unk] t_065e_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_7 :
    checkNode code (Cert.entries cert) 0 0xa2f [.unk] t_0a2f_c7 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_8 :
    checkNode code (Cert.entries cert) 0 0xab2 [.unk, .unk] t_0ab2_c8 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_9 :
    checkNode code (Cert.entries cert) 0 0xb33 [.unk, .unk] t_0b33_c9 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_10 :
    checkNode code (Cert.entries cert) 0 0xb6c [.unk] t_0b6c_c10 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_11 :
    checkNode code (Cert.entries cert) 0 0xdf9 [.unk, .unk, .unk, .unk] t_0df9_c11 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_12 :
    checkNode code (Cert.entries cert) 0 0x102c [.unk] t_102c_c12 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
