import Blanc.Lift.VyperNonreentrantDeployed.Fixed.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 66..87, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune

theorem entry_66 :
    checkNode code (Cert.entries cert) 0 0x4361 [.unk, .ret] t_4361_c66 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_67 :
    checkNode code (Cert.entries cert) 0 0x2efb [.unk, .unk, .unk, .unk, .unk, .unk, .unk] t_2efb_c67 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_68 :
    checkNode code (Cert.entries cert) 0 0x10c [.unk, .unk, .unk] t_010c_c68 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_69 :
    checkNode code (Cert.entries cert) 0 0x1ec [.unk, .unk, .unk] t_01ec_c69 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_70 :
    checkNode code (Cert.entries cert) 0 0x3db0 [.ret] t_3db0_c70 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_71 :
    checkNode code (Cert.entries cert) 0 0x17fc [.unk, .unk, .unk] t_17fc_c71 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_72 :
    checkNode code (Cert.entries cert) 0 0x1bdb [.unk, .unk, .unk] t_1bdb_c72 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_73 :
    checkNode code (Cert.entries cert) 0 0x1f4d [.unk, .unk, .unk] t_1f4d_c73 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_74 :
    checkNode code (Cert.entries cert) 0 0x1ffc [.unk, .unk, .unk] t_1ffc_c74 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_75 :
    checkNode code (Cert.entries cert) 0 0x3d5b [.ret] t_3d5b_c75 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_76 :
    checkNode code (Cert.entries cert) 0 0x35c7 [.unk, .unk, .unk, .ret] t_35c7_c76 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_77 :
    checkNode code (Cert.entries cert) 0 0x3eab [.unk, .unk, .unk, .ret] t_3eab_c77 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_78 :
    checkNode code (Cert.entries cert) 0 0x3ffa [.unk, .unk, .unk, .ret] t_3ffa_c78 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_79 :
    checkNode code (Cert.entries cert) 0 0x4137 [.unk, .unk, .unk, .ret] t_4137_c79 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_80 :
    checkNode code (Cert.entries cert) 0 0x4263 [.unk, .unk, .unk, .ret] t_4263_c80 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_81 :
    checkNode code (Cert.entries cert) 0 0x44d1 [.unk, .unk, .unk, .ret] t_44d1_c81 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_82 :
    checkNode code (Cert.entries cert) 0 0x40f9 [.unk, .ret] t_40f9_c82 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_83 :
    checkNode code (Cert.entries cert) 0 0x34e0 [.unk, .unk, .unk, .ret] t_34e0_c83 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_84 :
    checkNode code (Cert.entries cert) 0 0x3566 [.unk, .unk, .unk, .ret] t_3566_c84 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_85 :
    checkNode code (Cert.entries cert) 0 0x37e7 [.unk, .unk, .unk, .ret] t_37e7_c85 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_86 :
    checkNode code (Cert.entries cert) 0 0x38ee [.unk, .ret] t_38ee_c86 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_87 :
    checkNode code (Cert.entries cert) 0 0x4168 [.unk, .unk, .unk, .ret] t_4168_c87 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
