import Blanc.Lift.VyperNonreentrantDeployed.Fixed.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 41..65, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune

theorem entry_41 :
    checkNode code (Cert.entries cert) 0 0x3d59 [.ret] t_3d59_c41 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_42 :
    checkNode code (Cert.entries cert) 0 0x3dae [.ret] t_3dae_c42 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_43 :
    checkNode code (Cert.entries cert) 0 0x3e7e [.unk, .ret] t_3e7e_c43 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_44 :
    checkNode code (Cert.entries cert) 0 0x3ef8 [.unk, .unk, .unk, .ret] t_3ef8_c44 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_45 :
    checkNode code (Cert.entries cert) 0 0x3f54 [.unk, .unk, .unk, .ret] t_3f54_c45 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_46 :
    checkNode code (Cert.entries cert) 0 0x40e5 [.unk, .unk, .unk, .ret] t_40e5_c46 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_47 :
    checkNode code (Cert.entries cert) 0 0x40f7 [.ret] t_40f7_c47 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_48 :
    checkNode code (Cert.entries cert) 0 0x41c1 [.unk, .unk, .unk, .ret] t_41c1_c48 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_49 :
    checkNode code (Cert.entries cert) 0 0x434d [.unk, .unk, .unk, .ret] t_434d_c49 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_50 :
    checkNode code (Cert.entries cert) 0 0x435f [.ret] t_435f_c50 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_51 :
    checkNode code (Cert.entries cert) 0 0x458d [.unk, .unk, .unk, .ret] t_458d_c51 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_52 :
    checkNode code (Cert.entries cert) 0 0x4751 [.unk, .ret] t_4751_c52 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_53 :
    checkNode code (Cert.entries cert) 0 0xc85 [.unk, .unk, .unk] t_0c85_c53 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_54 :
    checkNode code (Cert.entries cert) 0 0x310a [.unk, .ret] t_310a_c54 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_55 :
    checkNode code (Cert.entries cert) 0 0xde0 [.unk, .unk, .unk, .unk] t_0de0_c55 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_56 :
    checkNode code (Cert.entries cert) 0 0x314e [.ret] t_314e_c56 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_57 :
    checkNode code (Cert.entries cert) 0 0x31ce [.unk, .ret] t_31ce_c57 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_58 :
    checkNode code (Cert.entries cert) 0 0x333b [.unk, .ret] t_333b_c58 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_59 :
    checkNode code (Cert.entries cert) 0 0x33af [.unk, .ret] t_33af_c59 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_60 :
    checkNode code (Cert.entries cert) 0 0x34d4 [.unk, .ret] t_34d4_c60 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_61 :
    checkNode code (Cert.entries cert) 0 0x355b [.unk, .ret] t_355b_c61 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_62 :
    checkNode code (Cert.entries cert) 0 0x37bf [.unk, .ret] t_37bf_c62 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_63 :
    checkNode code (Cert.entries cert) 0 0x3bf2 [.unk, .ret] t_3bf2_c63 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_64 :
    checkNode code (Cert.entries cert) 0 0x375c [.unk, .ret] t_375c_c64 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_65 :
    checkNode code (Cert.entries cert) 0 0x3df1 [.unk, .ret] t_3df1_c65 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
