import Blanc.Lift.VyperNonreentrantDeployed.Fixed.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 13..40, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune

theorem entry_13 :
    checkNode code (Cert.entries cert) 0 0x1363 [.unk] t_1363_c13 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_14 :
    checkNode code (Cert.entries cert) 0 0x187a [.unk, .unk, .unk] t_187a_c14 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_15 :
    checkNode code (Cert.entries cert) 0 0x1909 [.unk] t_1909_c15 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_16 :
    checkNode code (Cert.entries cert) 0 0x1b9e [.unk] t_1b9e_c16 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_17 :
    checkNode code (Cert.entries cert) 0 0x1d7f [.unk, .unk, .unk, .unk] t_1d7f_c17 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_18 :
    checkNode code (Cert.entries cert) 0 0x1d8b [.unk, .unk, .unk] t_1d8b_c18 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_19 :
    checkNode code (Cert.entries cert) 0 0x1e99 [.unk] t_1e99_c19 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_20 :
    checkNode code (Cert.entries cert) 0 0x20a7 [.unk, .unk, .unk] t_20a7_c20 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_21 :
    checkNode code (Cert.entries cert) 0 0x238b [.unk] t_238b_c21 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_22 :
    checkNode code (Cert.entries cert) 0 0x23fc [.unk, .unk] t_23fc_c22 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_23 :
    checkNode code (Cert.entries cert) 0 0x2408 [.unk] t_2408_c23 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_24 :
    checkNode code (Cert.entries cert) 0 0x24e9 [.unk] t_24e9_c24 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_25 :
    checkNode code (Cert.entries cert) 0 0x2712 [.unk, .unk] t_2712_c25 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_26 :
    checkNode code (Cert.entries cert) 0 0x271e [.unk] t_271e_c26 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_27 :
    checkNode code (Cert.entries cert) 0 0x2843 [.unk, .unk] t_2843_c27 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_28 :
    checkNode code (Cert.entries cert) 0 0x288f [.unk] t_288f_c28 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_29 :
    checkNode code (Cert.entries cert) 0 0x2a2a [.unk] t_2a2a_c29 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_30 :
    checkNode code (Cert.entries cert) 0 0x2a98 [.unk, .unk] t_2a98_c30 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_31 :
    checkNode code (Cert.entries cert) 0 0x2aa3 [.unk] t_2aa3_c31 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_32 :
    checkNode code (Cert.entries cert) 0 0x2bd9 [.unk, .unk] t_2bd9_c32 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_33 :
    checkNode code (Cert.entries cert) 0 0x2f12 [.unk, .unk, .unk, .unk, .unk, .unk, .unk] t_2f12_c33 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_34 :
    checkNode code (Cert.entries cert) 0 0x3104 [] t_3104_c34 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_35 :
    checkNode code (Cert.entries cert) 0 0x332b [.unk, .ret] t_332b_c35 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_36 :
    checkNode code (Cert.entries cert) 0 0x34d2 [.ret] t_34d2_c36 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_37 :
    checkNode code (Cert.entries cert) 0 0x3748 [.unk, .unk, .unk, .ret] t_3748_c37 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_38 :
    checkNode code (Cert.entries cert) 0 0x375a [.ret] t_375a_c38 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_39 :
    checkNode code (Cert.entries cert) 0 0x3be8 [.unk, .unk, .unk, .unk, .ret] t_3be8_c39 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_40 :
    checkNode code (Cert.entries cert) 0 0x3bf0 [.ret] t_3bf0_c40 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
