import Blanc.Lift.VyperNonreentrantDeployed.Fixed.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 0..12, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0x52 [.unk] t_0052_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x13a [.unk, .unk, .unk] t_013a_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 0 0x297 [.unk, .unk, .unk] t_0297_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0x538 [.unk, .unk] t_0538_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0x544 [.unk] t_0544_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 0 0x65e [.unk] t_065e_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_7 :
    checkNode code (Cert.entries cert) 0 0xa2f [.unk] t_0a2f_c7 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_8 :
    checkNode code (Cert.entries cert) 0 0xab2 [.unk, .unk] t_0ab2_c8 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_9 :
    checkNode code (Cert.entries cert) 0 0xb33 [.unk, .unk] t_0b33_c9 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_10 :
    checkNode code (Cert.entries cert) 0 0xb6c [.unk] t_0b6c_c10 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_11 :
    checkNode code (Cert.entries cert) 0 0xdf9 [.unk, .unk, .unk, .unk] t_0df9_c11 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_12 :
    checkNode code (Cert.entries cert) 0 0x102c [.unk] t_102c_c12 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
