import Blanc.Lift.VyperNonreentrantDeployed.Fixed.Cert
import Blanc.Lift.VyperNonreentrantDeployed.Fixed.LockAnn
import Blanc.Lift.VyperNonreentrantDeployed.Fixed.LockSpec

/-! GENERATED by scripts/lift/lift.py --lock-spec (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; LockCheck.lock_cert checks these annotations.
Each entry's lock walk is one kernel decision; `lock_cert` assembles them. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Jaune Blanc.Lift.LockCheck

theorem lock_entry_0 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x0 [] lockAnn_0 t_0000_c0 = true := by
  decide +kernel

theorem lock_entry_1 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x52 [.unk] lockAnn_1 t_0052_c1 = true := by
  decide +kernel

theorem lock_entry_2 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x13a [.unk, .unk, .unk] lockAnn_2 t_013a_c2 = true := by
  decide +kernel

theorem lock_entry_3 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x297 [.unk, .unk, .unk] lockAnn_3 t_0297_c3 = true := by
  decide +kernel

theorem lock_entry_4 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x538 [.unk, .unk] lockAnn_4 t_0538_c4 = true := by
  decide +kernel

theorem lock_entry_5 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x544 [.unk] lockAnn_5 t_0544_c5 = true := by
  decide +kernel

theorem lock_entry_6 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x65e [.unk] lockAnn_6 t_065e_c6 = true := by
  decide +kernel

theorem lock_entry_7 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xa2f [.unk] lockAnn_7 t_0a2f_c7 = true := by
  decide +kernel

theorem lock_entry_8 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xab2 [.unk, .unk] lockAnn_8 t_0ab2_c8 = true := by
  decide +kernel

theorem lock_entry_9 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xb33 [.unk, .unk] lockAnn_9 t_0b33_c9 = true := by
  decide +kernel

theorem lock_entry_10 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xb6c [.unk] lockAnn_10 t_0b6c_c10 = true := by
  decide +kernel

theorem lock_entry_11 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xdf9 [.unk, .unk, .unk, .unk] lockAnn_11 t_0df9_c11 = true := by
  decide +kernel

theorem lock_entry_12 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x102c [.unk] lockAnn_12 t_102c_c12 = true := by
  decide +kernel

theorem lock_entry_13 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1363 [.unk] lockAnn_13 t_1363_c13 = true := by
  decide +kernel

theorem lock_entry_14 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x187a [.unk, .unk, .unk] lockAnn_14 t_187a_c14 = true := by
  decide +kernel

theorem lock_entry_15 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1909 [.unk] lockAnn_15 t_1909_c15 = true := by
  decide +kernel

theorem lock_entry_16 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1b9e [.unk] lockAnn_16 t_1b9e_c16 = true := by
  decide +kernel

theorem lock_entry_17 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1d7f [.unk, .unk, .unk, .unk] lockAnn_17 t_1d7f_c17 = true := by
  decide +kernel

theorem lock_entry_18 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1d8b [.unk, .unk, .unk] lockAnn_18 t_1d8b_c18 = true := by
  decide +kernel

theorem lock_entry_19 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1e99 [.unk] lockAnn_19 t_1e99_c19 = true := by
  decide +kernel

theorem lock_entry_20 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x20a7 [.unk, .unk, .unk] lockAnn_20 t_20a7_c20 = true := by
  decide +kernel

theorem lock_entry_21 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x238b [.unk] lockAnn_21 t_238b_c21 = true := by
  decide +kernel

theorem lock_entry_22 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x23fc [.unk, .unk] lockAnn_22 t_23fc_c22 = true := by
  decide +kernel

theorem lock_entry_23 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2408 [.unk] lockAnn_23 t_2408_c23 = true := by
  decide +kernel

theorem lock_entry_24 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x24e9 [.unk] lockAnn_24 t_24e9_c24 = true := by
  decide +kernel

theorem lock_entry_25 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2712 [.unk, .unk] lockAnn_25 t_2712_c25 = true := by
  decide +kernel

theorem lock_entry_26 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x271e [.unk] lockAnn_26 t_271e_c26 = true := by
  decide +kernel

theorem lock_entry_27 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2843 [.unk, .unk] lockAnn_27 t_2843_c27 = true := by
  decide +kernel

theorem lock_entry_28 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x288f [.unk] lockAnn_28 t_288f_c28 = true := by
  decide +kernel

theorem lock_entry_29 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2a2a [.unk] lockAnn_29 t_2a2a_c29 = true := by
  decide +kernel

theorem lock_entry_30 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2a98 [.unk, .unk] lockAnn_30 t_2a98_c30 = true := by
  decide +kernel

theorem lock_entry_31 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2aa3 [.unk] lockAnn_31 t_2aa3_c31 = true := by
  decide +kernel

theorem lock_entry_32 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2bd9 [.unk, .unk] lockAnn_32 t_2bd9_c32 = true := by
  decide +kernel

theorem lock_entry_33 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2f12 [.unk, .unk, .unk, .unk, .unk, .unk, .unk] lockAnn_33 t_2f12_c33 = true := by
  decide +kernel

theorem lock_entry_34 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3104 [] lockAnn_34 t_3104_c34 = true := by
  decide +kernel

theorem lock_entry_35 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x332b [.unk, .ret] lockAnn_35 t_332b_c35 = true := by
  decide +kernel

theorem lock_entry_36 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x34d2 [.ret] lockAnn_36 t_34d2_c36 = true := by
  decide +kernel

theorem lock_entry_37 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3748 [.unk, .unk, .unk, .ret] lockAnn_37 t_3748_c37 = true := by
  decide +kernel

theorem lock_entry_38 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x375a [.ret] lockAnn_38 t_375a_c38 = true := by
  decide +kernel

theorem lock_entry_39 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3be8 [.unk, .unk, .unk, .unk, .ret] lockAnn_39 t_3be8_c39 = true := by
  decide +kernel

theorem lock_entry_40 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3bf0 [.ret] lockAnn_40 t_3bf0_c40 = true := by
  decide +kernel

theorem lock_entry_41 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3d59 [.ret] lockAnn_41 t_3d59_c41 = true := by
  decide +kernel

theorem lock_entry_42 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3dae [.ret] lockAnn_42 t_3dae_c42 = true := by
  decide +kernel

theorem lock_entry_43 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3e7e [.unk, .ret] lockAnn_43 t_3e7e_c43 = true := by
  decide +kernel

theorem lock_entry_44 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3ef8 [.unk, .unk, .unk, .ret] lockAnn_44 t_3ef8_c44 = true := by
  decide +kernel

theorem lock_entry_45 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3f54 [.unk, .unk, .unk, .ret] lockAnn_45 t_3f54_c45 = true := by
  decide +kernel

theorem lock_entry_46 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x40e5 [.unk, .unk, .unk, .ret] lockAnn_46 t_40e5_c46 = true := by
  decide +kernel

theorem lock_entry_47 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x40f7 [.ret] lockAnn_47 t_40f7_c47 = true := by
  decide +kernel

theorem lock_entry_48 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x41c1 [.unk, .unk, .unk, .ret] lockAnn_48 t_41c1_c48 = true := by
  decide +kernel

theorem lock_entry_49 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x434d [.unk, .unk, .unk, .ret] lockAnn_49 t_434d_c49 = true := by
  decide +kernel

theorem lock_entry_50 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x435f [.ret] lockAnn_50 t_435f_c50 = true := by
  decide +kernel

theorem lock_entry_51 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x458d [.unk, .unk, .unk, .ret] lockAnn_51 t_458d_c51 = true := by
  decide +kernel

theorem lock_entry_52 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x4751 [.unk, .ret] lockAnn_52 t_4751_c52 = true := by
  decide +kernel

theorem lock_entry_53 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xc85 [.unk, .unk, .unk] lockAnn_53 t_0c85_c53 = true := by
  decide +kernel

theorem lock_entry_54 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x310a [.unk, .ret] lockAnn_54 t_310a_c54 = true := by
  decide +kernel

theorem lock_entry_55 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0xde0 [.unk, .unk, .unk, .unk] lockAnn_55 t_0de0_c55 = true := by
  decide +kernel

theorem lock_entry_56 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x314e [.ret] lockAnn_56 t_314e_c56 = true := by
  decide +kernel

theorem lock_entry_57 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x31ce [.unk, .ret] lockAnn_57 t_31ce_c57 = true := by
  decide +kernel

theorem lock_entry_58 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x333b [.unk, .ret] lockAnn_58 t_333b_c58 = true := by
  decide +kernel

theorem lock_entry_59 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x33af [.unk, .ret] lockAnn_59 t_33af_c59 = true := by
  decide +kernel

theorem lock_entry_60 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x34d4 [.unk, .ret] lockAnn_60 t_34d4_c60 = true := by
  decide +kernel

theorem lock_entry_61 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x355b [.unk, .ret] lockAnn_61 t_355b_c61 = true := by
  decide +kernel

theorem lock_entry_62 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x37bf [.unk, .ret] lockAnn_62 t_37bf_c62 = true := by
  decide +kernel

theorem lock_entry_63 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3bf2 [.unk, .ret] lockAnn_63 t_3bf2_c63 = true := by
  decide +kernel

theorem lock_entry_64 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x375c [.unk, .ret] lockAnn_64 t_375c_c64 = true := by
  decide +kernel

theorem lock_entry_65 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3df1 [.unk, .ret] lockAnn_65 t_3df1_c65 = true := by
  decide +kernel

theorem lock_entry_66 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x4361 [.unk, .ret] lockAnn_66 t_4361_c66 = true := by
  decide +kernel

theorem lock_entry_67 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x2efb [.unk, .unk, .unk, .unk, .unk, .unk, .unk] lockAnn_67 t_2efb_c67 = true := by
  decide +kernel

theorem lock_entry_68 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x10c [.unk, .unk, .unk] lockAnn_68 t_010c_c68 = true := by
  decide +kernel

theorem lock_entry_69 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1ec [.unk, .unk, .unk] lockAnn_69 t_01ec_c69 = true := by
  decide +kernel

theorem lock_entry_70 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3db0 [.ret] lockAnn_70 t_3db0_c70 = true := by
  decide +kernel

theorem lock_entry_71 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x17fc [.unk, .unk, .unk] lockAnn_71 t_17fc_c71 = true := by
  decide +kernel

theorem lock_entry_72 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1bdb [.unk, .unk, .unk] lockAnn_72 t_1bdb_c72 = true := by
  decide +kernel

theorem lock_entry_73 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1f4d [.unk, .unk, .unk] lockAnn_73 t_1f4d_c73 = true := by
  decide +kernel

theorem lock_entry_74 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x1ffc [.unk, .unk, .unk] lockAnn_74 t_1ffc_c74 = true := by
  decide +kernel

theorem lock_entry_75 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3d5b [.ret] lockAnn_75 t_3d5b_c75 = true := by
  decide +kernel

theorem lock_entry_76 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x35c7 [.unk, .unk, .unk, .ret] lockAnn_76 t_35c7_c76 = true := by
  decide +kernel

theorem lock_entry_77 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3eab [.unk, .unk, .unk, .ret] lockAnn_77 t_3eab_c77 = true := by
  decide +kernel

theorem lock_entry_78 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3ffa [.unk, .unk, .unk, .ret] lockAnn_78 t_3ffa_c78 = true := by
  decide +kernel

theorem lock_entry_79 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x4137 [.unk, .unk, .unk, .ret] lockAnn_79 t_4137_c79 = true := by
  decide +kernel

theorem lock_entry_80 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x4263 [.unk, .unk, .unk, .ret] lockAnn_80 t_4263_c80 = true := by
  decide +kernel

theorem lock_entry_81 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x44d1 [.unk, .unk, .unk, .ret] lockAnn_81 t_44d1_c81 = true := by
  decide +kernel

theorem lock_entry_82 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x40f9 [.unk, .ret] lockAnn_82 t_40f9_c82 = true := by
  decide +kernel

theorem lock_entry_83 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x34e0 [.unk, .unk, .unk, .ret] lockAnn_83 t_34e0_c83 = true := by
  decide +kernel

theorem lock_entry_84 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x3566 [.unk, .unk, .unk, .ret] lockAnn_84 t_3566_c84 = true := by
  decide +kernel

theorem lock_entry_85 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x37e7 [.unk, .unk, .unk, .ret] lockAnn_85 t_37e7_c85 = true := by
  decide +kernel

theorem lock_entry_86 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x38ee [.unk, .ret] lockAnn_86 t_38ee_c86 = true := by
  decide +kernel

theorem lock_entry_87 :
    lockNode lockSpec (Cert.entries cert) lockAnn 0x4168 [.unk, .unk, .unk, .ret] lockAnn_87 t_4168_c87 = true := by
  decide +kernel

theorem lock_cert : lockCert lockSpec cert lockAnn = true := by
  unfold lockCert
  rw [Bool.and_eq_true, Bool.and_eq_true]
  refine ⟨⟨by decide +kernel, by decide +kernel⟩, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, lockAnn, List.zip_cons_cons, List.zip_nil_left, List.mem_cons,
    List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact lock_entry_0
  · exact lock_entry_1
  · exact lock_entry_2
  · exact lock_entry_3
  · exact lock_entry_4
  · exact lock_entry_5
  · exact lock_entry_6
  · exact lock_entry_7
  · exact lock_entry_8
  · exact lock_entry_9
  · exact lock_entry_10
  · exact lock_entry_11
  · exact lock_entry_12
  · exact lock_entry_13
  · exact lock_entry_14
  · exact lock_entry_15
  · exact lock_entry_16
  · exact lock_entry_17
  · exact lock_entry_18
  · exact lock_entry_19
  · exact lock_entry_20
  · exact lock_entry_21
  · exact lock_entry_22
  · exact lock_entry_23
  · exact lock_entry_24
  · exact lock_entry_25
  · exact lock_entry_26
  · exact lock_entry_27
  · exact lock_entry_28
  · exact lock_entry_29
  · exact lock_entry_30
  · exact lock_entry_31
  · exact lock_entry_32
  · exact lock_entry_33
  · exact lock_entry_34
  · exact lock_entry_35
  · exact lock_entry_36
  · exact lock_entry_37
  · exact lock_entry_38
  · exact lock_entry_39
  · exact lock_entry_40
  · exact lock_entry_41
  · exact lock_entry_42
  · exact lock_entry_43
  · exact lock_entry_44
  · exact lock_entry_45
  · exact lock_entry_46
  · exact lock_entry_47
  · exact lock_entry_48
  · exact lock_entry_49
  · exact lock_entry_50
  · exact lock_entry_51
  · exact lock_entry_52
  · exact lock_entry_53
  · exact lock_entry_54
  · exact lock_entry_55
  · exact lock_entry_56
  · exact lock_entry_57
  · exact lock_entry_58
  · exact lock_entry_59
  · exact lock_entry_60
  · exact lock_entry_61
  · exact lock_entry_62
  · exact lock_entry_63
  · exact lock_entry_64
  · exact lock_entry_65
  · exact lock_entry_66
  · exact lock_entry_67
  · exact lock_entry_68
  · exact lock_entry_69
  · exact lock_entry_70
  · exact lock_entry_71
  · exact lock_entry_72
  · exact lock_entry_73
  · exact lock_entry_74
  · exact lock_entry_75
  · exact lock_entry_76
  · exact lock_entry_77
  · exact lock_entry_78
  · exact lock_entry_79
  · exact lock_entry_80
  · exact lock_entry_81
  · exact lock_entry_82
  · exact lock_entry_83
  · exact lock_entry_84
  · exact lock_entry_85
  · exact lock_entry_86
  · exact lock_entry_87

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
