import Blanc.Lift.LockCheck

/-! GENERATED by scripts/lift/lift.py --lock-spec (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; LockCheck.lock_cert checks these annotations.
One reentrancy-lock annotation per certificate entry (`Blanc/Lift/LockCheck.lean`). -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed

open Blanc.Lift.LockCheck

def lockAnn_0 : LSt := ⟨[], [], false, false, true⟩
def lockAnn_1 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_2 : LSt := ⟨[0, 1, 2], [(.bnd 0 0 1), (.bnd 1 2 2)], true, false, false⟩
def lockAnn_3 : LSt := ⟨[0, 1, 2], [(.bnd 0 0 1), (.bnd 1 2 2)], true, false, false⟩
def lockAnn_4 : LSt := ⟨[0, 1], [], true, false, false⟩
def lockAnn_5 : LSt := ⟨[0], [], true, false, false⟩
def lockAnn_6 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_7 : LSt := ⟨[0], [], true, false, false⟩
def lockAnn_8 : LSt := ⟨[0, 1], [], true, false, false⟩
def lockAnn_9 : LSt := ⟨[0, 1], [], true, false, false⟩
def lockAnn_10 : LSt := ⟨[0], [], true, false, false⟩
def lockAnn_11 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 0 0), (.bnd 1 0 0)], false, false, false⟩
def lockAnn_12 : LSt := ⟨[0], [], false, false, false⟩
def lockAnn_13 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_14 : LSt := ⟨[0, 1, 2], [(.bnd 0 0 1), (.bnd 1 2 2)], false, false, false⟩
def lockAnn_15 : LSt := ⟨[0], [], false, false, false⟩
def lockAnn_16 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_17 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 0 1), (.bnd 2 2 2)], true, false, false⟩
def lockAnn_18 : LSt := ⟨[0, 1, 2], [(.bnd 0 0 1), (.bnd 1 2 2)], true, false, false⟩
def lockAnn_19 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_20 : LSt := ⟨[0, 1, 2], [(.bnd 0 0 1), (.bnd 1 2 2)], true, false, false⟩
def lockAnn_21 : LSt := ⟨[0], [], true, false, false⟩
def lockAnn_22 : LSt := ⟨[0, 1], [], true, false, false⟩
def lockAnn_23 : LSt := ⟨[0], [], true, false, false⟩
def lockAnn_24 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_25 : LSt := ⟨[0, 1], [], true, false, false⟩
def lockAnn_26 : LSt := ⟨[0], [], true, false, false⟩
def lockAnn_27 : LSt := ⟨[0, 1], [], false, false, false⟩
def lockAnn_28 : LSt := ⟨[0], [], false, false, false⟩
def lockAnn_29 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_30 : LSt := ⟨[0, 1], [], false, false, true⟩
def lockAnn_31 : LSt := ⟨[0], [], false, false, true⟩
def lockAnn_32 : LSt := ⟨[0, 1], [], false, false, true⟩
def lockAnn_33 : LSt := ⟨[0, 1, 2, 3, 4, 5, 6], [(.bnd 0 0 0), (.bnd 1 0 0), (.bnd 2 128 128), (.bnd 4 96 96), (.bnd 5 32 32)], false, false, true⟩
def lockAnn_34 : LSt := ⟨[], [], false, false, true⟩
def lockAnn_35 : LSt := ⟨[0, 1], [(.bnd 0 352 1056), (.bnd 1 161 17279)], false, false, false⟩
def lockAnn_36 : LSt := ⟨[0], [(.bnd 0 108 17260)], false, false, false⟩
def lockAnn_37 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 255 255), (.bnd 2 480 1376), (.bnd 3 969 17439)], false, false, false⟩
def lockAnn_38 : LSt := ⟨[0], [(.bnd 0 969 17439)], false, false, false⟩
def lockAnn_39 : LSt := ⟨[0, 1, 2, 3, 4], [(.bnd 3 416 416), (.bnd 4 15582 15582)], true, false, false⟩
def lockAnn_40 : LSt := ⟨[0], [(.bnd 0 15582 15582)], true, false, false⟩
def lockAnn_41 : LSt := ⟨[0], [(.bnd 0 5680 15735)], true, false, false⟩
def lockAnn_42 : LSt := ⟨[0], [(.bnd 0 10093 15855)], true, false, false⟩
def lockAnn_43 : LSt := ⟨[0, 1], [(.bnd 0 1152 1312), (.bnd 1 2021 6808)], false, false, false⟩
def lockAnn_44 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 0 1), (.bnd 1 2 2), (.bnd 2 1152 1312), (.bnd 3 2021 6808)], false, false, false⟩
def lockAnn_45 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 0 1), (.bnd 1 2 2), (.bnd 2 1152 1312), (.bnd 3 2021 6808)], false, false, false⟩
def lockAnn_46 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 255 255), (.bnd 2 1152 1312), (.bnd 3 2021 6808)], false, false, false⟩
def lockAnn_47 : LSt := ⟨[0], [(.bnd 0 2021 6808)], false, false, false⟩
def lockAnn_48 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 0 1), (.bnd 1 2 2), (.bnd 2 832 960), (.bnd 3 17567 17959)], false, false, false⟩
def lockAnn_49 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 255 255), (.bnd 2 832 960), (.bnd 3 17567 17959)], false, false, false⟩
def lockAnn_50 : LSt := ⟨[0], [(.bnd 0 17567 17959)], false, false, false⟩
def lockAnn_51 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 0 1), (.bnd 1 2 2), (.bnd 2 1088 1216), (.bnd 3 9380 9507)], false, false, false⟩
def lockAnn_52 : LSt := ⟨[0, 1], [(.bnd 0 1088 1216), (.bnd 1 9380 9507)], false, false, false⟩
def lockAnn_53 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], false, false, true⟩
def lockAnn_54 : LSt := ⟨[0, 1], [(.bnd 0 416 512), (.bnd 1 3381 15768)], false, false, false⟩
def lockAnn_55 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], false, false, false⟩
def lockAnn_56 : LSt := ⟨[0], [(.bnd 0 3924 4008)], false, false, true⟩
def lockAnn_57 : LSt := ⟨[0, 1], [(.bnd 0 352 1056), (.bnd 1 161 17279)], false, false, false⟩
def lockAnn_58 : LSt := ⟨[0, 1], [(.bnd 0 160 1120), (.bnd 1 131 17330)], false, false, false⟩
def lockAnn_59 : LSt := ⟨[0, 1], [(.bnd 0 192 1248), (.bnd 1 108 17260)], false, false, false⟩
def lockAnn_60 : LSt := ⟨[0, 1], [(.bnd 0 576 1344), (.bnd 1 918 17388)], false, false, false⟩
def lockAnn_61 : LSt := ⟨[0, 1], [(.bnd 0 480 1376), (.bnd 1 969 17439)], false, false, false⟩
def lockAnn_62 : LSt := ⟨[0, 1], [(.bnd 0 480 1024), (.bnd 1 5633 18248)], false, false, false⟩
def lockAnn_63 : LSt := ⟨[0, 1], [(.bnd 0 448 480), (.bnd 1 5680 15735)], true, false, false⟩
def lockAnn_64 : LSt := ⟨[0, 1], [(.bnd 0 864 1152), (.bnd 1 231 8138)], false, false, false⟩
def lockAnn_65 : LSt := ⟨[0, 1], [(.bnd 0 1152 1312), (.bnd 1 2021 6808)], false, false, false⟩
def lockAnn_66 : LSt := ⟨[0, 1], [(.bnd 0 1088 1216), (.bnd 1 9380 9507)], false, false, false⟩
def lockAnn_67 : LSt := ⟨[0, 1, 2, 3, 4, 5, 6], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 128 128), (.bnd 4 96 96), (.bnd 5 32 32), (.le 0 1), (.le 0 2), (.le 0 4), (.le 0 5), (.lt 0 1)], false, false, true⟩
def lockAnn_68 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], true, false, false⟩
def lockAnn_69 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], true, false, false⟩
def lockAnn_70 : LSt := ⟨[0], [(.bnd 0 1097 8713)], true, false, false⟩
def lockAnn_71 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], false, false, false⟩
def lockAnn_72 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], true, false, false⟩
def lockAnn_73 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], true, false, false⟩
def lockAnn_74 : LSt := ⟨[0, 1, 2], [(.bnd 0 1 1), (.bnd 1 2 2), (.le 0 1), (.lt 0 1)], true, false, false⟩
def lockAnn_75 : LSt := ⟨[0], [(.bnd 0 10093 15855)], true, false, false⟩
def lockAnn_76 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 255 255), (.bnd 2 480 1376), (.bnd 3 969 17439)], false, false, false⟩
def lockAnn_77 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 1152 1312), (.bnd 3 2021 6808), (.le 0 1), (.le 0 2), (.le 0 3), (.lt 0 1)], false, false, false⟩
def lockAnn_78 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 255 255), (.bnd 2 1152 1312), (.bnd 3 2021 6808)], false, false, false⟩
def lockAnn_79 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 832 960), (.bnd 3 17567 17959), (.le 0 1), (.le 0 2), (.le 0 3), (.lt 0 1)], false, false, false⟩
def lockAnn_80 : LSt := ⟨[0, 1, 2, 3], [(.bnd 1 255 255), (.bnd 2 832 960), (.bnd 3 17567 17959)], false, false, false⟩
def lockAnn_81 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 1088 1216), (.bnd 3 9380 9507), (.le 0 1), (.le 0 2), (.le 0 3), (.lt 0 1)], false, false, false⟩
def lockAnn_82 : LSt := ⟨[0, 1], [(.bnd 0 832 960), (.bnd 1 17567 17959)], false, false, false⟩
def lockAnn_83 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 576 1344), (.bnd 3 918 17388), (.le 0 1), (.le 0 2), (.le 0 3), (.lt 0 1)], false, false, false⟩
def lockAnn_84 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 480 1376), (.bnd 3 969 17439), (.le 0 1), (.le 0 2), (.le 0 3), (.lt 0 1)], false, false, false⟩
def lockAnn_85 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 1 1), (.bnd 1 2 2), (.bnd 2 480 1024), (.bnd 3 5633 18248), (.le 0 1), (.le 0 2), (.le 0 3), (.lt 0 1)], false, false, false⟩
def lockAnn_86 : LSt := ⟨[0, 1], [(.bnd 0 416 416), (.bnd 1 15582 15582)], true, false, false⟩
def lockAnn_87 : LSt := ⟨[0, 1, 2, 3], [(.bnd 0 0 1), (.bnd 1 2 2), (.bnd 2 832 960), (.bnd 3 17567 17959)], false, false, false⟩

def lockAnn : List LSt := [
  lockAnn_0,
  lockAnn_1,
  lockAnn_2,
  lockAnn_3,
  lockAnn_4,
  lockAnn_5,
  lockAnn_6,
  lockAnn_7,
  lockAnn_8,
  lockAnn_9,
  lockAnn_10,
  lockAnn_11,
  lockAnn_12,
  lockAnn_13,
  lockAnn_14,
  lockAnn_15,
  lockAnn_16,
  lockAnn_17,
  lockAnn_18,
  lockAnn_19,
  lockAnn_20,
  lockAnn_21,
  lockAnn_22,
  lockAnn_23,
  lockAnn_24,
  lockAnn_25,
  lockAnn_26,
  lockAnn_27,
  lockAnn_28,
  lockAnn_29,
  lockAnn_30,
  lockAnn_31,
  lockAnn_32,
  lockAnn_33,
  lockAnn_34,
  lockAnn_35,
  lockAnn_36,
  lockAnn_37,
  lockAnn_38,
  lockAnn_39,
  lockAnn_40,
  lockAnn_41,
  lockAnn_42,
  lockAnn_43,
  lockAnn_44,
  lockAnn_45,
  lockAnn_46,
  lockAnn_47,
  lockAnn_48,
  lockAnn_49,
  lockAnn_50,
  lockAnn_51,
  lockAnn_52,
  lockAnn_53,
  lockAnn_54,
  lockAnn_55,
  lockAnn_56,
  lockAnn_57,
  lockAnn_58,
  lockAnn_59,
  lockAnn_60,
  lockAnn_61,
  lockAnn_62,
  lockAnn_63,
  lockAnn_64,
  lockAnn_65,
  lockAnn_66,
  lockAnn_67,
  lockAnn_68,
  lockAnn_69,
  lockAnn_70,
  lockAnn_71,
  lockAnn_72,
  lockAnn_73,
  lockAnn_74,
  lockAnn_75,
  lockAnn_76,
  lockAnn_77,
  lockAnn_78,
  lockAnn_79,
  lockAnn_80,
  lockAnn_81,
  lockAnn_82,
  lockAnn_83,
  lockAnn_84,
  lockAnn_85,
  lockAnn_86,
  lockAnn_87
]

end Blanc.Lift.VyperNonreentrantDeployed.Fixed
