import Blanc.CreationArtifact
import Blanc.LidoTriggerableWithdrawalsGateway

/-!
Compiler-owned runtime artifacts for the production Lido Triggerable
Withdrawals Gateway port.

The locator immutable spans are derived by compiling a fixed-width marker
world.  Constructor generation consumes the resulting metadata directly, so
there is no second hand-maintained offset table.
-/

namespace Blanc

open Jaune

namespace LidoTriggerableWithdrawalsGateway

/-- The parameterized runtime artifact emitted by Blanc's compiler. -/
def lidoTwgCode (dp : DeployParams) : Bytes :=
  (Prog.compile (runtime dp)).getD []

/-- Universal compiler witness for the locator-parameterized runtime family. -/
theorem lidoTwgCode_compile (dp : DeployParams) :
    Prog.compile (runtime dp) = some (lidoTwgCode dp) := by
  unfold lidoTwgCode
  exact Prog.compile_eq_some_getD_of_compiles _ (runtime_compiles dp)

def zeroDeployParams : DeployParams := ⟨0⟩

/-- The all-zero member is the constructor's parameter-neutral runtime
template. -/
def runtimeTemplateCode : Bytes := lidoTwgCode zeroDeployParams

/-- A compiler-probe world whose locator word is all ones. -/
def locatorMarkerParams : DeployParams := ⟨B256.max⟩

/-- Generated byte offsets of the first payload byte of every PUSH32 carrying
the locator. -/
def locatorWordOffsets : List Nat :=
  CreationArtifact.immutableWordOffsets runtimeTemplateCode
    (lidoTwgCode locatorMarkerParams)

/-- Fail-closed validation of the compiler-derived locator patch metadata. -/
def locatorWordOffsetsValid : Bool :=
  CreationArtifact.immutableWordOffsetsValid runtimeTemplateCode
    (lidoTwgCode locatorMarkerParams)

/-- Reconstruct a runtime-family member from the zero template and the exact
locator patch plan consumed by the constructor. -/
def patchRuntimeTemplate (locator : B256) : Bytes :=
  locatorWordOffsets.foldl
    (fun code offset => CreationArtifact.patchWord code offset locator)
    runtimeTemplateCode

def runtimePatchIdentityValid (dp : DeployParams) : Bool :=
  patchRuntimeTemplate dp.locator = lidoTwgCode dp

/-- Live controls cover the marker endpoints and two unrelated nontrivial
locator worlds used by the evaluator. -/
def runtimePatchControlsValid : Bool :=
  locatorWordOffsetsValid &&
    runtimePatchIdentityValid zeroDeployParams &&
    runtimePatchIdentityValid locatorMarkerParams &&
    runtimePatchIdentityValid ⟨0x111122223333444455556666777788889999aaaa⟩ &&
    runtimePatchIdentityValid ⟨0xabcdefabcdefabcdefabcdefabcdefabcdefabcd⟩

/-- Selector inventory generated from the executable dispatcher owner. -/
def lidoTwgSelectors : List B256 :=
  (funcs zeroDeployParams).map Prod.fst

def eip170RuntimeLimit : Nat := 24576

def lidoTwgCodeSize (dp : DeployParams) : Nat := (lidoTwgCode dp).length

def runtimeTemplateCodeSize : Nat := runtimeTemplateCode.length

def lidoTwgCodeHeadroom (dp : DeployParams) : Nat :=
  eip170RuntimeLimit - lidoTwgCodeSize dp

end LidoTriggerableWithdrawalsGateway
end Blanc
