import Blanc.LidoCircuitBreaker

/-!
Compiler-owned runtime artifacts for the production Lido CircuitBreaker.

The definitions in this module deliberately identify Blanc's parameterized
runtime family; they make no byte-identity claim about Solidity.  Immutable
word locations are derived from compiler output by changing one fixed-width
deployment word at a time, so downstream constructor and differential tooling
do not maintain a second offset table by hand.
-/

namespace Blanc

open Jaune

namespace LidoCircuitBreaker

/-- The parameterized runtime artifact emitted by Blanc's compiler. -/
def lidoCircuitBreakerCode (dp : DeployParams) : Bytes :=
  (Prog.compile (runtime dp)).getD []

/-- Universal compiler witness: every fixed-width deployment-parameter member
of the runtime family compiles to the artifact named above. -/
theorem lidoCircuitBreakerCode_compile (dp : DeployParams) :
    Prog.compile (runtime dp) = some (lidoCircuitBreakerCode dp) := by
  unfold lidoCircuitBreakerCode
  exact Prog.compile_eq_some_getD_of_compiles _ (runtime_compiles dp)

/-- The all-zero member is the constructor's parameter-neutral runtime
template.  The constructor replaces only the generated fixed-width words
described by `immutableWordOffsets`. -/
def zeroDeployParams : DeployParams :=
  { admin := 0
    minPauseDuration := 0
    maxPauseDuration := 0
    minHeartbeatInterval := 0
    maxHeartbeatInterval := 0 }

def runtimeTemplateCode : Bytes :=
  lidoCircuitBreakerCode zeroDeployParams

/-- Each runtime deployment parameter is emitted through `pushDeployWord` and
therefore occupies one or more complete 32-byte payloads without changing
compiler shape. -/
inductive ImmutableParameter
  | admin
  | minPauseDuration
  | maxPauseDuration
  | minHeartbeatInterval
  | maxHeartbeatInterval
deriving DecidableEq

def immutableParameters : List ImmutableParameter :=
  [.admin, .minPauseDuration, .maxPauseDuration,
   .minHeartbeatInterval, .maxHeartbeatInterval]

def ImmutableParameter.value
    (field : ImmutableParameter) (dp : DeployParams) : B256 :=
  match field with
  | .admin => dp.admin
  | .minPauseDuration => dp.minPauseDuration
  | .maxPauseDuration => dp.maxPauseDuration
  | .minHeartbeatInterval => dp.minHeartbeatInterval
  | .maxHeartbeatInterval => dp.maxHeartbeatInterval

/-- A compiler-probe parameter record.  Exactly one immutable field is all
ones; the others remain zero. -/
def immutableMarkerParams (field : ImmutableParameter) : DeployParams :=
  { admin := if field = .admin then B256.max else 0
    minPauseDuration :=
      if field = .minPauseDuration then B256.max else 0
    maxPauseDuration :=
      if field = .maxPauseDuration then B256.max else 0
    minHeartbeatInterval :=
      if field = .minHeartbeatInterval then B256.max else 0
    maxHeartbeatInterval :=
      if field = .maxHeartbeatInterval then B256.max else 0 }

/-- Byte indices at which two compiler artifacts differ.  Unequal lengths are
handled fail-closed by also returning every unmatched tail index. -/
def differingByteOffsets : Nat → Bytes → Bytes → List Nat
  | _, [], [] => []
  | i, [], _ :: ys => i :: differingByteOffsets (i + 1) [] ys
  | i, _ :: xs, [] => i :: differingByteOffsets (i + 1) xs []
  | i, x :: xs, y :: ys =>
      (if x = y then [] else [i]) ++ differingByteOffsets (i + 1) xs ys

/-- First index of every contiguous run in an ordered offset list. -/
def contiguousRunStarts (offsets : List Nat) : List Nat :=
  offsets.filter fun i => i = 0 || !(offsets.contains (i - 1))

/-- Generated byte offsets of the first payload byte of every PUSH32 carrying
the selected deployment parameter.  This is derived from the compiler, not a
hand-maintained runtime literal or offset list. -/
def immutableWordOffsets (field : ImmutableParameter) : List Nat :=
  contiguousRunStarts <|
    differingByteOffsets 0 runtimeTemplateCode
      (lidoCircuitBreakerCode (immutableMarkerParams field))

/-- Expand word-start metadata to the byte indices it claims are mutable. -/
def wordByteOffsets (starts : List Nat) : List Nat :=
  starts.flatMap fun start => (List.range 32).map (start + ·)

/-- Fail-closed executable validation for generated patch metadata: compiler
length must stay fixed and every changed byte must belong to one complete,
nonempty 32-byte word span. -/
def immutableWordOffsetsValid (field : ImmutableParameter) : Bool :=
  let markerCode := lidoCircuitBreakerCode (immutableMarkerParams field)
  markerCode.length = runtimeTemplateCode.length &&
    !(immutableWordOffsets field).isEmpty &&
    differingByteOffsets 0 runtimeTemplateCode markerCode =
      wordByteOffsets (immutableWordOffsets field)

/-- Five named generated lists consumed by constructor generation and emitted
by differential evaluators. -/
def adminWordOffsets : List Nat := immutableWordOffsets .admin
def minPauseDurationWordOffsets : List Nat :=
  immutableWordOffsets .minPauseDuration
def maxPauseDurationWordOffsets : List Nat :=
  immutableWordOffsets .maxPauseDuration
def minHeartbeatIntervalWordOffsets : List Nat :=
  immutableWordOffsets .minHeartbeatInterval
def maxHeartbeatIntervalWordOffsets : List Nat :=
  immutableWordOffsets .maxHeartbeatInterval

def immutableOffsetMetadataValid : Bool :=
  immutableParameters.all immutableWordOffsetsValid

structure ImmutablePatch where
  field : ImmutableParameter
  offset : Nat
  value : B256
deriving DecidableEq

/-- The generated patch plan for a member of the runtime family.  Downstream
creation-code generation consumes this list directly. -/
def runtimeImmutablePatches (dp : DeployParams) : List ImmutablePatch :=
  immutableParameters.flatMap fun field =>
    (immutableWordOffsets field).map fun offset =>
      { field, offset, value := field.value dp }

/-- Replace one generated 32-byte payload in a runtime template. -/
def applyImmutablePatch (code : Bytes) (patch : ImmutablePatch) : Bytes :=
  code.take patch.offset ++ patch.value.toBytes ++
    code.drop (patch.offset + 32)

/-- Reconstruct a runtime-family member from the zero template and the exact
patch plan consumed by the constructor. -/
def patchRuntimeTemplate (dp : DeployParams) : Bytes :=
  (runtimeImmutablePatches dp).foldl applyImmutablePatch runtimeTemplateCode

/-- Executable patch-identity check for an arbitrary evaluator-selected
parameter world. -/
def runtimePatchIdentityValid (dp : DeployParams) : Bool :=
  patchRuntimeTemplate dp = lidoCircuitBreakerCode dp

/-- Live metadata control covering every one-field marker plus the official
and independent constructor worlds. -/
def runtimePatchControlsValid : Bool :=
  immutableOffsetMetadataValid &&
    immutableParameters.all
      (fun field => runtimePatchIdentityValid (immutableMarkerParams field)) &&
    runtimePatchIdentityValid officialParams &&
    runtimePatchIdentityValid independentConstructorArgs.toDeployParams

/-- Selector inventory generated from the executable dispatcher owner. -/
def lidoCircuitBreakerSelectors : List B256 :=
  (funcs zeroDeployParams).map Prod.fst

/-- Artifact size metadata used by EIP-170 checks in deployment evaluators. -/
def eip170RuntimeLimit : Nat := 24576

def lidoCircuitBreakerCodeSize (dp : DeployParams) : Nat :=
  (lidoCircuitBreakerCode dp).length

def runtimeTemplateCodeSize : Nat := runtimeTemplateCode.length

def lidoCircuitBreakerCodeHeadroom (dp : DeployParams) : Nat :=
  eip170RuntimeLimit - lidoCircuitBreakerCodeSize dp

end LidoCircuitBreaker
end Blanc
