import Blanc.Lift.Check
import Blanc.SystemContracts

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit. -/

namespace Blanc.Lift.HistoryStorage

open Jaune

-- Code: 83 bytes, SHA-256: 41cd74981e0201f79ebca054c4e8102a7e6faa28ce015d0048ab2250c1222c67
def code : ByteArray := Blanc.historyStorageCode

def t_0036_c0 : SFunc := (.next (.push [0x1f, 0xff] (by decide)) (.next (.reg (.swap 0)) (.next (.reg .mod) (.next (.reg .sload) (.next (.push [] (by decide)) (.next (.reg .mstore) (.next (.push [0x20] (by decide)) (.next (.push [] (by decide)) (.last .return_)))))))))
def t_0042_c0 : SFunc := (.dest (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.last .revert))))
def t_002c_c0 : SFunc := (.next (.push [0x1f, 0xff] (by decide)) (.next (.reg (.dup 1)) (.next (.reg .number) (.next (.reg .sub) (.next (.reg .gt) (.next (.push [0x42] (by decide)) (.branch t_0036_c0 t_0042_c0)))))))
def t_0021_c0 : SFunc := (.next (.push [] (by decide)) (.next (.reg .calldataload) (.next (.push [0x01] (by decide)) (.next (.reg .number) (.next (.reg .sub) (.next (.reg (.dup 1)) (.next (.reg .gt) (.next (.push [0x42] (by decide)) (.branch t_002c_c0 t_0042_c0)))))))))
def t_001a_c0 : SFunc := (.next (.push [0x20] (by decide)) (.next (.reg .calldatasize) (.next (.reg .sub) (.next (.push [0x42] (by decide)) (.branch t_0021_c0 t_0042_c0)))))
def t_0046_c0 : SFunc := (.dest (.next (.push [] (by decide)) (.next (.reg .calldataload) (.next (.push [0x1f, 0xff] (by decide)) (.next (.push [0x01] (by decide)) (.next (.reg .number) (.next (.reg .sub) (.next (.reg .mod) (.next (.reg .sstore) (.last .stop))))))))))
def t_0000_c0 : SFunc := (.next (.reg .caller) (.next (.push [0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe] (by decide)) (.next (.reg .eq) (.next (.push [0x46] (by decide)) (.branch t_001a_c0 t_0046_c0)))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.HistoryStorage
