import Blanc.Lift.Check

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Check.cert_check checks the flood-looper bytes. -/

namespace Blanc.Lift.FloodLooper

open Jaune

-- Code: 54 bytes, SHA-256: 26f1a187d9290d1d1468313692e9399155133a51480880e757930a76d0833624
def code : ByteArray := ⟨#[
  0x60, 0x38, 0x60, 0x20, 0x5f, 0x37, 0x5f, 0x5b, 0x80, 0x5f, 0x35, 0x14, 0x60, 0x34, 0x57, 0x5f,
  0x5f, 0x60, 0x38, 0x5f, 0x60, 0x01, 0x73, 0x00, 0x00, 0x09, 0x61, 0xef, 0x48, 0x0e, 0xb5, 0x5e,
  0x80, 0xd1, 0x9a, 0xd8, 0x35, 0x79, 0xa6, 0x4c, 0x00, 0x70, 0x02, 0x5a, 0xf1, 0x50, 0x60, 0x01,
  0x01, 0x60, 0x07, 0x56, 0x5b, 0x00
]⟩

def t_000f_c0 : SFunc := (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.next (.push [0x38] (by decide)) (.next (.push [] (by decide)) (.next (.push [0x01] (by decide)) (.next (.push [0x00, 0x00, 0x09, 0x61, 0xef, 0x48, 0x0e, 0xb5, 0x5e, 0x80, 0xd1, 0x9a, 0xd8, 0x35, 0x79, 0xa6, 0x4c, 0x00, 0x70, 0x02] (by decide)) (.next (.reg .gas) (.next (.exec .call) (.next (.reg .pop) (.next (.push [0x01] (by decide)) (.next (.reg .add) (.next (.push [0x07] (by decide)) (.jump 1)))))))))))))
def t_0034_c0 : SFunc := (.dest (.last .stop))
def t_0007_c0 : SFunc := (.dest (.next (.reg (.dup 0)) (.next (.push [] (by decide)) (.next (.reg .calldataload) (.next (.reg .eq) (.next (.push [0x34] (by decide)) (.branch t_000f_c0 t_0034_c0)))))))
def t_0000_c0 : SFunc := (.next (.push [0x38] (by decide)) (.next (.push [0x20] (by decide)) (.next (.push [] (by decide)) (.next (.reg .calldatacopy) (.next (.push [] (by decide)) t_0007_c0)))))
def t_000f_c1 : SFunc := (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.next (.push [0x38] (by decide)) (.next (.push [] (by decide)) (.next (.push [0x01] (by decide)) (.next (.push [0x00, 0x00, 0x09, 0x61, 0xef, 0x48, 0x0e, 0xb5, 0x5e, 0x80, 0xd1, 0x9a, 0xd8, 0x35, 0x79, 0xa6, 0x4c, 0x00, 0x70, 0x02] (by decide)) (.next (.reg .gas) (.next (.exec .call) (.next (.reg .pop) (.next (.push [0x01] (by decide)) (.next (.reg .add) (.next (.push [0x07] (by decide)) (.jump 1)))))))))))))
def t_0034_c1 : SFunc := (.dest (.last .stop))
def t_0007_c1 : SFunc := (.dest (.next (.reg (.dup 0)) (.next (.push [] (by decide)) (.next (.reg .calldataload) (.next (.reg .eq) (.next (.push [0x34] (by decide)) (.branch t_000f_c1 t_0034_c1)))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0),
  (⟨0x7, [.unk], 0⟩, t_0007_c1)
]

end Blanc.Lift.FloodLooper
