import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 0..33, each decided against trie-backed reads of the exact runtime.
The generic equalities rewrite each result to Cert.checkM / Cert.jumpsOkM. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable

open Jaune

theorem entry_0 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[0]'(by decide +kernel)).1.rets (cert[0]'(by decide +kernel)).1.pc
      (cert[0]'(by decide +kernel)).1.frame (mems.getD 0 []) (cert[0]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_0 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[0]'(by decide +kernel)).2 (cert[0]'(by decide +kernel)).1.frame (mems.getD 0 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[1]'(by decide +kernel)).1.rets (cert[1]'(by decide +kernel)).1.pc
      (cert[1]'(by decide +kernel)).1.frame (mems.getD 1 []) (cert[1]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_1 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[1]'(by decide +kernel)).2 (cert[1]'(by decide +kernel)).1.frame (mems.getD 1 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[2]'(by decide +kernel)).1.rets (cert[2]'(by decide +kernel)).1.pc
      (cert[2]'(by decide +kernel)).1.frame (mems.getD 2 []) (cert[2]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_2 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[2]'(by decide +kernel)).2 (cert[2]'(by decide +kernel)).1.frame (mems.getD 2 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[3]'(by decide +kernel)).1.rets (cert[3]'(by decide +kernel)).1.pc
      (cert[3]'(by decide +kernel)).1.frame (mems.getD 3 []) (cert[3]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_3 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[3]'(by decide +kernel)).2 (cert[3]'(by decide +kernel)).1.frame (mems.getD 3 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[4]'(by decide +kernel)).1.rets (cert[4]'(by decide +kernel)).1.pc
      (cert[4]'(by decide +kernel)).1.frame (mems.getD 4 []) (cert[4]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_4 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[4]'(by decide +kernel)).2 (cert[4]'(by decide +kernel)).1.frame (mems.getD 4 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[5]'(by decide +kernel)).1.rets (cert[5]'(by decide +kernel)).1.pc
      (cert[5]'(by decide +kernel)).1.frame (mems.getD 5 []) (cert[5]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_5 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[5]'(by decide +kernel)).2 (cert[5]'(by decide +kernel)).1.frame (mems.getD 5 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[6]'(by decide +kernel)).1.rets (cert[6]'(by decide +kernel)).1.pc
      (cert[6]'(by decide +kernel)).1.frame (mems.getD 6 []) (cert[6]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_6 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[6]'(by decide +kernel)).2 (cert[6]'(by decide +kernel)).1.frame (mems.getD 6 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_7 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[7]'(by decide +kernel)).1.rets (cert[7]'(by decide +kernel)).1.pc
      (cert[7]'(by decide +kernel)).1.frame (mems.getD 7 []) (cert[7]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_7 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[7]'(by decide +kernel)).2 (cert[7]'(by decide +kernel)).1.frame (mems.getD 7 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_8 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[8]'(by decide +kernel)).1.rets (cert[8]'(by decide +kernel)).1.pc
      (cert[8]'(by decide +kernel)).1.frame (mems.getD 8 []) (cert[8]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_8 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[8]'(by decide +kernel)).2 (cert[8]'(by decide +kernel)).1.frame (mems.getD 8 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_9 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[9]'(by decide +kernel)).1.rets (cert[9]'(by decide +kernel)).1.pc
      (cert[9]'(by decide +kernel)).1.frame (mems.getD 9 []) (cert[9]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_9 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[9]'(by decide +kernel)).2 (cert[9]'(by decide +kernel)).1.frame (mems.getD 9 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_10 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[10]'(by decide +kernel)).1.rets (cert[10]'(by decide +kernel)).1.pc
      (cert[10]'(by decide +kernel)).1.frame (mems.getD 10 []) (cert[10]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_10 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[10]'(by decide +kernel)).2 (cert[10]'(by decide +kernel)).1.frame (mems.getD 10 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_11 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[11]'(by decide +kernel)).1.rets (cert[11]'(by decide +kernel)).1.pc
      (cert[11]'(by decide +kernel)).1.frame (mems.getD 11 []) (cert[11]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_11 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[11]'(by decide +kernel)).2 (cert[11]'(by decide +kernel)).1.frame (mems.getD 11 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_12 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[12]'(by decide +kernel)).1.rets (cert[12]'(by decide +kernel)).1.pc
      (cert[12]'(by decide +kernel)).1.frame (mems.getD 12 []) (cert[12]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_12 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[12]'(by decide +kernel)).2 (cert[12]'(by decide +kernel)).1.frame (mems.getD 12 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_13 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[13]'(by decide +kernel)).1.rets (cert[13]'(by decide +kernel)).1.pc
      (cert[13]'(by decide +kernel)).1.frame (mems.getD 13 []) (cert[13]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_13 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[13]'(by decide +kernel)).2 (cert[13]'(by decide +kernel)).1.frame (mems.getD 13 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_14 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[14]'(by decide +kernel)).1.rets (cert[14]'(by decide +kernel)).1.pc
      (cert[14]'(by decide +kernel)).1.frame (mems.getD 14 []) (cert[14]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_14 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[14]'(by decide +kernel)).2 (cert[14]'(by decide +kernel)).1.frame (mems.getD 14 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_15 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[15]'(by decide +kernel)).1.rets (cert[15]'(by decide +kernel)).1.pc
      (cert[15]'(by decide +kernel)).1.frame (mems.getD 15 []) (cert[15]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_15 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[15]'(by decide +kernel)).2 (cert[15]'(by decide +kernel)).1.frame (mems.getD 15 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_16 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[16]'(by decide +kernel)).1.rets (cert[16]'(by decide +kernel)).1.pc
      (cert[16]'(by decide +kernel)).1.frame (mems.getD 16 []) (cert[16]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_16 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[16]'(by decide +kernel)).2 (cert[16]'(by decide +kernel)).1.frame (mems.getD 16 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_17 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[17]'(by decide +kernel)).1.rets (cert[17]'(by decide +kernel)).1.pc
      (cert[17]'(by decide +kernel)).1.frame (mems.getD 17 []) (cert[17]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_17 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[17]'(by decide +kernel)).2 (cert[17]'(by decide +kernel)).1.frame (mems.getD 17 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_18 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[18]'(by decide +kernel)).1.rets (cert[18]'(by decide +kernel)).1.pc
      (cert[18]'(by decide +kernel)).1.frame (mems.getD 18 []) (cert[18]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_18 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[18]'(by decide +kernel)).2 (cert[18]'(by decide +kernel)).1.frame (mems.getD 18 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_19 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[19]'(by decide +kernel)).1.rets (cert[19]'(by decide +kernel)).1.pc
      (cert[19]'(by decide +kernel)).1.frame (mems.getD 19 []) (cert[19]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_19 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[19]'(by decide +kernel)).2 (cert[19]'(by decide +kernel)).1.frame (mems.getD 19 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_20 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[20]'(by decide +kernel)).1.rets (cert[20]'(by decide +kernel)).1.pc
      (cert[20]'(by decide +kernel)).1.frame (mems.getD 20 []) (cert[20]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_20 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[20]'(by decide +kernel)).2 (cert[20]'(by decide +kernel)).1.frame (mems.getD 20 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_21 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[21]'(by decide +kernel)).1.rets (cert[21]'(by decide +kernel)).1.pc
      (cert[21]'(by decide +kernel)).1.frame (mems.getD 21 []) (cert[21]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_21 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[21]'(by decide +kernel)).2 (cert[21]'(by decide +kernel)).1.frame (mems.getD 21 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_22 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[22]'(by decide +kernel)).1.rets (cert[22]'(by decide +kernel)).1.pc
      (cert[22]'(by decide +kernel)).1.frame (mems.getD 22 []) (cert[22]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_22 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[22]'(by decide +kernel)).2 (cert[22]'(by decide +kernel)).1.frame (mems.getD 22 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_23 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[23]'(by decide +kernel)).1.rets (cert[23]'(by decide +kernel)).1.pc
      (cert[23]'(by decide +kernel)).1.frame (mems.getD 23 []) (cert[23]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_23 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[23]'(by decide +kernel)).2 (cert[23]'(by decide +kernel)).1.frame (mems.getD 23 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_24 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[24]'(by decide +kernel)).1.rets (cert[24]'(by decide +kernel)).1.pc
      (cert[24]'(by decide +kernel)).1.frame (mems.getD 24 []) (cert[24]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_24 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[24]'(by decide +kernel)).2 (cert[24]'(by decide +kernel)).1.frame (mems.getD 24 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_25 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[25]'(by decide +kernel)).1.rets (cert[25]'(by decide +kernel)).1.pc
      (cert[25]'(by decide +kernel)).1.frame (mems.getD 25 []) (cert[25]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_25 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[25]'(by decide +kernel)).2 (cert[25]'(by decide +kernel)).1.frame (mems.getD 25 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_26 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[26]'(by decide +kernel)).1.rets (cert[26]'(by decide +kernel)).1.pc
      (cert[26]'(by decide +kernel)).1.frame (mems.getD 26 []) (cert[26]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_26 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[26]'(by decide +kernel)).2 (cert[26]'(by decide +kernel)).1.frame (mems.getD 26 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_27 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[27]'(by decide +kernel)).1.rets (cert[27]'(by decide +kernel)).1.pc
      (cert[27]'(by decide +kernel)).1.frame (mems.getD 27 []) (cert[27]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_27 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[27]'(by decide +kernel)).2 (cert[27]'(by decide +kernel)).1.frame (mems.getD 27 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_28 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[28]'(by decide +kernel)).1.rets (cert[28]'(by decide +kernel)).1.pc
      (cert[28]'(by decide +kernel)).1.frame (mems.getD 28 []) (cert[28]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_28 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[28]'(by decide +kernel)).2 (cert[28]'(by decide +kernel)).1.frame (mems.getD 28 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_29 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[29]'(by decide +kernel)).1.rets (cert[29]'(by decide +kernel)).1.pc
      (cert[29]'(by decide +kernel)).1.frame (mems.getD 29 []) (cert[29]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_29 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[29]'(by decide +kernel)).2 (cert[29]'(by decide +kernel)).1.frame (mems.getD 29 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_30 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[30]'(by decide +kernel)).1.rets (cert[30]'(by decide +kernel)).1.pc
      (cert[30]'(by decide +kernel)).1.frame (mems.getD 30 []) (cert[30]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_30 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[30]'(by decide +kernel)).2 (cert[30]'(by decide +kernel)).1.frame (mems.getD 30 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_31 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[31]'(by decide +kernel)).1.rets (cert[31]'(by decide +kernel)).1.pc
      (cert[31]'(by decide +kernel)).1.frame (mems.getD 31 []) (cert[31]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_31 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[31]'(by decide +kernel)).2 (cert[31]'(by decide +kernel)).1.frame (mems.getD 31 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_32 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[32]'(by decide +kernel)).1.rets (cert[32]'(by decide +kernel)).1.pc
      (cert[32]'(by decide +kernel)).1.frame (mems.getD 32 []) (cert[32]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_32 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[32]'(by decide +kernel)).2 (cert[32]'(by decide +kernel)).1.frame (mems.getD 32 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_33 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[33]'(by decide +kernel)).1.rets (cert[33]'(by decide +kernel)).1.pc
      (cert[33]'(by decide +kernel)).1.frame (mems.getD 33 []) (cert[33]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_33 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[33]'(by decide +kernel)).2 (cert[33]'(by decide +kernel)).1.frame (mems.getD 33 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable
