import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 121..167, each decided against trie-backed reads of the exact runtime.
The generic equalities rewrite each result to Cert.checkM / Cert.jumpsOkM. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable

open Jaune

theorem entry_121 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[121]'(by decide +kernel)).1.rets (cert[121]'(by decide +kernel)).1.pc
      (cert[121]'(by decide +kernel)).1.frame (mems.getD 121 []) (cert[121]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_121 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[121]'(by decide +kernel)).2 (cert[121]'(by decide +kernel)).1.frame (mems.getD 121 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_122 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[122]'(by decide +kernel)).1.rets (cert[122]'(by decide +kernel)).1.pc
      (cert[122]'(by decide +kernel)).1.frame (mems.getD 122 []) (cert[122]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_122 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[122]'(by decide +kernel)).2 (cert[122]'(by decide +kernel)).1.frame (mems.getD 122 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_123 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[123]'(by decide +kernel)).1.rets (cert[123]'(by decide +kernel)).1.pc
      (cert[123]'(by decide +kernel)).1.frame (mems.getD 123 []) (cert[123]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_123 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[123]'(by decide +kernel)).2 (cert[123]'(by decide +kernel)).1.frame (mems.getD 123 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_124 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[124]'(by decide +kernel)).1.rets (cert[124]'(by decide +kernel)).1.pc
      (cert[124]'(by decide +kernel)).1.frame (mems.getD 124 []) (cert[124]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_124 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[124]'(by decide +kernel)).2 (cert[124]'(by decide +kernel)).1.frame (mems.getD 124 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_125 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[125]'(by decide +kernel)).1.rets (cert[125]'(by decide +kernel)).1.pc
      (cert[125]'(by decide +kernel)).1.frame (mems.getD 125 []) (cert[125]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_125 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[125]'(by decide +kernel)).2 (cert[125]'(by decide +kernel)).1.frame (mems.getD 125 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_126 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[126]'(by decide +kernel)).1.rets (cert[126]'(by decide +kernel)).1.pc
      (cert[126]'(by decide +kernel)).1.frame (mems.getD 126 []) (cert[126]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_126 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[126]'(by decide +kernel)).2 (cert[126]'(by decide +kernel)).1.frame (mems.getD 126 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_127 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[127]'(by decide +kernel)).1.rets (cert[127]'(by decide +kernel)).1.pc
      (cert[127]'(by decide +kernel)).1.frame (mems.getD 127 []) (cert[127]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_127 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[127]'(by decide +kernel)).2 (cert[127]'(by decide +kernel)).1.frame (mems.getD 127 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_128 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[128]'(by decide +kernel)).1.rets (cert[128]'(by decide +kernel)).1.pc
      (cert[128]'(by decide +kernel)).1.frame (mems.getD 128 []) (cert[128]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_128 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[128]'(by decide +kernel)).2 (cert[128]'(by decide +kernel)).1.frame (mems.getD 128 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_129 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[129]'(by decide +kernel)).1.rets (cert[129]'(by decide +kernel)).1.pc
      (cert[129]'(by decide +kernel)).1.frame (mems.getD 129 []) (cert[129]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_129 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[129]'(by decide +kernel)).2 (cert[129]'(by decide +kernel)).1.frame (mems.getD 129 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_130 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[130]'(by decide +kernel)).1.rets (cert[130]'(by decide +kernel)).1.pc
      (cert[130]'(by decide +kernel)).1.frame (mems.getD 130 []) (cert[130]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_130 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[130]'(by decide +kernel)).2 (cert[130]'(by decide +kernel)).1.frame (mems.getD 130 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_131 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[131]'(by decide +kernel)).1.rets (cert[131]'(by decide +kernel)).1.pc
      (cert[131]'(by decide +kernel)).1.frame (mems.getD 131 []) (cert[131]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_131 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[131]'(by decide +kernel)).2 (cert[131]'(by decide +kernel)).1.frame (mems.getD 131 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_132 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[132]'(by decide +kernel)).1.rets (cert[132]'(by decide +kernel)).1.pc
      (cert[132]'(by decide +kernel)).1.frame (mems.getD 132 []) (cert[132]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_132 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[132]'(by decide +kernel)).2 (cert[132]'(by decide +kernel)).1.frame (mems.getD 132 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_133 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[133]'(by decide +kernel)).1.rets (cert[133]'(by decide +kernel)).1.pc
      (cert[133]'(by decide +kernel)).1.frame (mems.getD 133 []) (cert[133]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_133 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[133]'(by decide +kernel)).2 (cert[133]'(by decide +kernel)).1.frame (mems.getD 133 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_134 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[134]'(by decide +kernel)).1.rets (cert[134]'(by decide +kernel)).1.pc
      (cert[134]'(by decide +kernel)).1.frame (mems.getD 134 []) (cert[134]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_134 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[134]'(by decide +kernel)).2 (cert[134]'(by decide +kernel)).1.frame (mems.getD 134 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_135 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[135]'(by decide +kernel)).1.rets (cert[135]'(by decide +kernel)).1.pc
      (cert[135]'(by decide +kernel)).1.frame (mems.getD 135 []) (cert[135]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_135 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[135]'(by decide +kernel)).2 (cert[135]'(by decide +kernel)).1.frame (mems.getD 135 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_136 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[136]'(by decide +kernel)).1.rets (cert[136]'(by decide +kernel)).1.pc
      (cert[136]'(by decide +kernel)).1.frame (mems.getD 136 []) (cert[136]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_136 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[136]'(by decide +kernel)).2 (cert[136]'(by decide +kernel)).1.frame (mems.getD 136 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_137 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[137]'(by decide +kernel)).1.rets (cert[137]'(by decide +kernel)).1.pc
      (cert[137]'(by decide +kernel)).1.frame (mems.getD 137 []) (cert[137]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_137 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[137]'(by decide +kernel)).2 (cert[137]'(by decide +kernel)).1.frame (mems.getD 137 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_138 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[138]'(by decide +kernel)).1.rets (cert[138]'(by decide +kernel)).1.pc
      (cert[138]'(by decide +kernel)).1.frame (mems.getD 138 []) (cert[138]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_138 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[138]'(by decide +kernel)).2 (cert[138]'(by decide +kernel)).1.frame (mems.getD 138 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_139 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[139]'(by decide +kernel)).1.rets (cert[139]'(by decide +kernel)).1.pc
      (cert[139]'(by decide +kernel)).1.frame (mems.getD 139 []) (cert[139]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_139 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[139]'(by decide +kernel)).2 (cert[139]'(by decide +kernel)).1.frame (mems.getD 139 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_140 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[140]'(by decide +kernel)).1.rets (cert[140]'(by decide +kernel)).1.pc
      (cert[140]'(by decide +kernel)).1.frame (mems.getD 140 []) (cert[140]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_140 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[140]'(by decide +kernel)).2 (cert[140]'(by decide +kernel)).1.frame (mems.getD 140 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_141 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[141]'(by decide +kernel)).1.rets (cert[141]'(by decide +kernel)).1.pc
      (cert[141]'(by decide +kernel)).1.frame (mems.getD 141 []) (cert[141]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_141 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[141]'(by decide +kernel)).2 (cert[141]'(by decide +kernel)).1.frame (mems.getD 141 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_142 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[142]'(by decide +kernel)).1.rets (cert[142]'(by decide +kernel)).1.pc
      (cert[142]'(by decide +kernel)).1.frame (mems.getD 142 []) (cert[142]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_142 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[142]'(by decide +kernel)).2 (cert[142]'(by decide +kernel)).1.frame (mems.getD 142 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_143 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[143]'(by decide +kernel)).1.rets (cert[143]'(by decide +kernel)).1.pc
      (cert[143]'(by decide +kernel)).1.frame (mems.getD 143 []) (cert[143]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_143 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[143]'(by decide +kernel)).2 (cert[143]'(by decide +kernel)).1.frame (mems.getD 143 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_144 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[144]'(by decide +kernel)).1.rets (cert[144]'(by decide +kernel)).1.pc
      (cert[144]'(by decide +kernel)).1.frame (mems.getD 144 []) (cert[144]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_144 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[144]'(by decide +kernel)).2 (cert[144]'(by decide +kernel)).1.frame (mems.getD 144 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_145 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[145]'(by decide +kernel)).1.rets (cert[145]'(by decide +kernel)).1.pc
      (cert[145]'(by decide +kernel)).1.frame (mems.getD 145 []) (cert[145]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_145 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[145]'(by decide +kernel)).2 (cert[145]'(by decide +kernel)).1.frame (mems.getD 145 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_146 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[146]'(by decide +kernel)).1.rets (cert[146]'(by decide +kernel)).1.pc
      (cert[146]'(by decide +kernel)).1.frame (mems.getD 146 []) (cert[146]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_146 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[146]'(by decide +kernel)).2 (cert[146]'(by decide +kernel)).1.frame (mems.getD 146 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_147 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[147]'(by decide +kernel)).1.rets (cert[147]'(by decide +kernel)).1.pc
      (cert[147]'(by decide +kernel)).1.frame (mems.getD 147 []) (cert[147]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_147 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[147]'(by decide +kernel)).2 (cert[147]'(by decide +kernel)).1.frame (mems.getD 147 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_148 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[148]'(by decide +kernel)).1.rets (cert[148]'(by decide +kernel)).1.pc
      (cert[148]'(by decide +kernel)).1.frame (mems.getD 148 []) (cert[148]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_148 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[148]'(by decide +kernel)).2 (cert[148]'(by decide +kernel)).1.frame (mems.getD 148 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_149 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[149]'(by decide +kernel)).1.rets (cert[149]'(by decide +kernel)).1.pc
      (cert[149]'(by decide +kernel)).1.frame (mems.getD 149 []) (cert[149]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_149 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[149]'(by decide +kernel)).2 (cert[149]'(by decide +kernel)).1.frame (mems.getD 149 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_150 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[150]'(by decide +kernel)).1.rets (cert[150]'(by decide +kernel)).1.pc
      (cert[150]'(by decide +kernel)).1.frame (mems.getD 150 []) (cert[150]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_150 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[150]'(by decide +kernel)).2 (cert[150]'(by decide +kernel)).1.frame (mems.getD 150 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_151 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[151]'(by decide +kernel)).1.rets (cert[151]'(by decide +kernel)).1.pc
      (cert[151]'(by decide +kernel)).1.frame (mems.getD 151 []) (cert[151]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_151 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[151]'(by decide +kernel)).2 (cert[151]'(by decide +kernel)).1.frame (mems.getD 151 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_152 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[152]'(by decide +kernel)).1.rets (cert[152]'(by decide +kernel)).1.pc
      (cert[152]'(by decide +kernel)).1.frame (mems.getD 152 []) (cert[152]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_152 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[152]'(by decide +kernel)).2 (cert[152]'(by decide +kernel)).1.frame (mems.getD 152 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_153 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[153]'(by decide +kernel)).1.rets (cert[153]'(by decide +kernel)).1.pc
      (cert[153]'(by decide +kernel)).1.frame (mems.getD 153 []) (cert[153]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_153 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[153]'(by decide +kernel)).2 (cert[153]'(by decide +kernel)).1.frame (mems.getD 153 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_154 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[154]'(by decide +kernel)).1.rets (cert[154]'(by decide +kernel)).1.pc
      (cert[154]'(by decide +kernel)).1.frame (mems.getD 154 []) (cert[154]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_154 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[154]'(by decide +kernel)).2 (cert[154]'(by decide +kernel)).1.frame (mems.getD 154 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_155 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[155]'(by decide +kernel)).1.rets (cert[155]'(by decide +kernel)).1.pc
      (cert[155]'(by decide +kernel)).1.frame (mems.getD 155 []) (cert[155]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_155 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[155]'(by decide +kernel)).2 (cert[155]'(by decide +kernel)).1.frame (mems.getD 155 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_156 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[156]'(by decide +kernel)).1.rets (cert[156]'(by decide +kernel)).1.pc
      (cert[156]'(by decide +kernel)).1.frame (mems.getD 156 []) (cert[156]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_156 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[156]'(by decide +kernel)).2 (cert[156]'(by decide +kernel)).1.frame (mems.getD 156 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_157 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[157]'(by decide +kernel)).1.rets (cert[157]'(by decide +kernel)).1.pc
      (cert[157]'(by decide +kernel)).1.frame (mems.getD 157 []) (cert[157]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_157 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[157]'(by decide +kernel)).2 (cert[157]'(by decide +kernel)).1.frame (mems.getD 157 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_158 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[158]'(by decide +kernel)).1.rets (cert[158]'(by decide +kernel)).1.pc
      (cert[158]'(by decide +kernel)).1.frame (mems.getD 158 []) (cert[158]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_158 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[158]'(by decide +kernel)).2 (cert[158]'(by decide +kernel)).1.frame (mems.getD 158 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_159 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[159]'(by decide +kernel)).1.rets (cert[159]'(by decide +kernel)).1.pc
      (cert[159]'(by decide +kernel)).1.frame (mems.getD 159 []) (cert[159]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_159 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[159]'(by decide +kernel)).2 (cert[159]'(by decide +kernel)).1.frame (mems.getD 159 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_160 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[160]'(by decide +kernel)).1.rets (cert[160]'(by decide +kernel)).1.pc
      (cert[160]'(by decide +kernel)).1.frame (mems.getD 160 []) (cert[160]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_160 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[160]'(by decide +kernel)).2 (cert[160]'(by decide +kernel)).1.frame (mems.getD 160 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_161 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[161]'(by decide +kernel)).1.rets (cert[161]'(by decide +kernel)).1.pc
      (cert[161]'(by decide +kernel)).1.frame (mems.getD 161 []) (cert[161]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_161 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[161]'(by decide +kernel)).2 (cert[161]'(by decide +kernel)).1.frame (mems.getD 161 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_162 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[162]'(by decide +kernel)).1.rets (cert[162]'(by decide +kernel)).1.pc
      (cert[162]'(by decide +kernel)).1.frame (mems.getD 162 []) (cert[162]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_162 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[162]'(by decide +kernel)).2 (cert[162]'(by decide +kernel)).1.frame (mems.getD 162 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_163 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[163]'(by decide +kernel)).1.rets (cert[163]'(by decide +kernel)).1.pc
      (cert[163]'(by decide +kernel)).1.frame (mems.getD 163 []) (cert[163]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_163 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[163]'(by decide +kernel)).2 (cert[163]'(by decide +kernel)).1.frame (mems.getD 163 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_164 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[164]'(by decide +kernel)).1.rets (cert[164]'(by decide +kernel)).1.pc
      (cert[164]'(by decide +kernel)).1.frame (mems.getD 164 []) (cert[164]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_164 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[164]'(by decide +kernel)).2 (cert[164]'(by decide +kernel)).1.frame (mems.getD 164 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_165 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[165]'(by decide +kernel)).1.rets (cert[165]'(by decide +kernel)).1.pc
      (cert[165]'(by decide +kernel)).1.frame (mems.getD 165 []) (cert[165]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_165 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[165]'(by decide +kernel)).2 (cert[165]'(by decide +kernel)).1.frame (mems.getD 165 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_166 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[166]'(by decide +kernel)).1.rets (cert[166]'(by decide +kernel)).1.pc
      (cert[166]'(by decide +kernel)).1.frame (mems.getD 166 []) (cert[166]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_166 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[166]'(by decide +kernel)).2 (cert[166]'(by decide +kernel)).1.frame (mems.getD 166 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_167 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[167]'(by decide +kernel)).1.rets (cert[167]'(by decide +kernel)).1.pc
      (cert[167]'(by decide +kernel)).1.frame (mems.getD 167 []) (cert[167]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_167 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[167]'(by decide +kernel)).2 (cert[167]'(by decide +kernel)).1.frame (mems.getD 167 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable
