import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 62..86, each decided against trie-backed reads of the exact runtime.
The generic equalities rewrite each result to Cert.checkM / Cert.jumpsOkM. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable

open Jaune

theorem entry_62 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[62]'(by decide +kernel)).1.rets (cert[62]'(by decide +kernel)).1.pc
      (cert[62]'(by decide +kernel)).1.frame (mems.getD 62 []) (cert[62]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_62 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[62]'(by decide +kernel)).2 (cert[62]'(by decide +kernel)).1.frame (mems.getD 62 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_63 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[63]'(by decide +kernel)).1.rets (cert[63]'(by decide +kernel)).1.pc
      (cert[63]'(by decide +kernel)).1.frame (mems.getD 63 []) (cert[63]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_63 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[63]'(by decide +kernel)).2 (cert[63]'(by decide +kernel)).1.frame (mems.getD 63 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_64 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[64]'(by decide +kernel)).1.rets (cert[64]'(by decide +kernel)).1.pc
      (cert[64]'(by decide +kernel)).1.frame (mems.getD 64 []) (cert[64]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_64 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[64]'(by decide +kernel)).2 (cert[64]'(by decide +kernel)).1.frame (mems.getD 64 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_65 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[65]'(by decide +kernel)).1.rets (cert[65]'(by decide +kernel)).1.pc
      (cert[65]'(by decide +kernel)).1.frame (mems.getD 65 []) (cert[65]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_65 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[65]'(by decide +kernel)).2 (cert[65]'(by decide +kernel)).1.frame (mems.getD 65 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_66 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[66]'(by decide +kernel)).1.rets (cert[66]'(by decide +kernel)).1.pc
      (cert[66]'(by decide +kernel)).1.frame (mems.getD 66 []) (cert[66]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_66 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[66]'(by decide +kernel)).2 (cert[66]'(by decide +kernel)).1.frame (mems.getD 66 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_67 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[67]'(by decide +kernel)).1.rets (cert[67]'(by decide +kernel)).1.pc
      (cert[67]'(by decide +kernel)).1.frame (mems.getD 67 []) (cert[67]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_67 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[67]'(by decide +kernel)).2 (cert[67]'(by decide +kernel)).1.frame (mems.getD 67 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_68 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[68]'(by decide +kernel)).1.rets (cert[68]'(by decide +kernel)).1.pc
      (cert[68]'(by decide +kernel)).1.frame (mems.getD 68 []) (cert[68]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_68 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[68]'(by decide +kernel)).2 (cert[68]'(by decide +kernel)).1.frame (mems.getD 68 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_69 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[69]'(by decide +kernel)).1.rets (cert[69]'(by decide +kernel)).1.pc
      (cert[69]'(by decide +kernel)).1.frame (mems.getD 69 []) (cert[69]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_69 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[69]'(by decide +kernel)).2 (cert[69]'(by decide +kernel)).1.frame (mems.getD 69 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_70 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[70]'(by decide +kernel)).1.rets (cert[70]'(by decide +kernel)).1.pc
      (cert[70]'(by decide +kernel)).1.frame (mems.getD 70 []) (cert[70]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_70 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[70]'(by decide +kernel)).2 (cert[70]'(by decide +kernel)).1.frame (mems.getD 70 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_71 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[71]'(by decide +kernel)).1.rets (cert[71]'(by decide +kernel)).1.pc
      (cert[71]'(by decide +kernel)).1.frame (mems.getD 71 []) (cert[71]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_71 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[71]'(by decide +kernel)).2 (cert[71]'(by decide +kernel)).1.frame (mems.getD 71 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_72 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[72]'(by decide +kernel)).1.rets (cert[72]'(by decide +kernel)).1.pc
      (cert[72]'(by decide +kernel)).1.frame (mems.getD 72 []) (cert[72]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_72 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[72]'(by decide +kernel)).2 (cert[72]'(by decide +kernel)).1.frame (mems.getD 72 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_73 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[73]'(by decide +kernel)).1.rets (cert[73]'(by decide +kernel)).1.pc
      (cert[73]'(by decide +kernel)).1.frame (mems.getD 73 []) (cert[73]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_73 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[73]'(by decide +kernel)).2 (cert[73]'(by decide +kernel)).1.frame (mems.getD 73 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_74 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[74]'(by decide +kernel)).1.rets (cert[74]'(by decide +kernel)).1.pc
      (cert[74]'(by decide +kernel)).1.frame (mems.getD 74 []) (cert[74]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_74 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[74]'(by decide +kernel)).2 (cert[74]'(by decide +kernel)).1.frame (mems.getD 74 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_75 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[75]'(by decide +kernel)).1.rets (cert[75]'(by decide +kernel)).1.pc
      (cert[75]'(by decide +kernel)).1.frame (mems.getD 75 []) (cert[75]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_75 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[75]'(by decide +kernel)).2 (cert[75]'(by decide +kernel)).1.frame (mems.getD 75 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_76 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[76]'(by decide +kernel)).1.rets (cert[76]'(by decide +kernel)).1.pc
      (cert[76]'(by decide +kernel)).1.frame (mems.getD 76 []) (cert[76]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_76 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[76]'(by decide +kernel)).2 (cert[76]'(by decide +kernel)).1.frame (mems.getD 76 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_77 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[77]'(by decide +kernel)).1.rets (cert[77]'(by decide +kernel)).1.pc
      (cert[77]'(by decide +kernel)).1.frame (mems.getD 77 []) (cert[77]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_77 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[77]'(by decide +kernel)).2 (cert[77]'(by decide +kernel)).1.frame (mems.getD 77 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_78 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[78]'(by decide +kernel)).1.rets (cert[78]'(by decide +kernel)).1.pc
      (cert[78]'(by decide +kernel)).1.frame (mems.getD 78 []) (cert[78]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_78 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[78]'(by decide +kernel)).2 (cert[78]'(by decide +kernel)).1.frame (mems.getD 78 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_79 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[79]'(by decide +kernel)).1.rets (cert[79]'(by decide +kernel)).1.pc
      (cert[79]'(by decide +kernel)).1.frame (mems.getD 79 []) (cert[79]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_79 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[79]'(by decide +kernel)).2 (cert[79]'(by decide +kernel)).1.frame (mems.getD 79 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_80 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[80]'(by decide +kernel)).1.rets (cert[80]'(by decide +kernel)).1.pc
      (cert[80]'(by decide +kernel)).1.frame (mems.getD 80 []) (cert[80]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_80 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[80]'(by decide +kernel)).2 (cert[80]'(by decide +kernel)).1.frame (mems.getD 80 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_81 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[81]'(by decide +kernel)).1.rets (cert[81]'(by decide +kernel)).1.pc
      (cert[81]'(by decide +kernel)).1.frame (mems.getD 81 []) (cert[81]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_81 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[81]'(by decide +kernel)).2 (cert[81]'(by decide +kernel)).1.frame (mems.getD 81 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_82 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[82]'(by decide +kernel)).1.rets (cert[82]'(by decide +kernel)).1.pc
      (cert[82]'(by decide +kernel)).1.frame (mems.getD 82 []) (cert[82]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_82 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[82]'(by decide +kernel)).2 (cert[82]'(by decide +kernel)).1.frame (mems.getD 82 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_83 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[83]'(by decide +kernel)).1.rets (cert[83]'(by decide +kernel)).1.pc
      (cert[83]'(by decide +kernel)).1.frame (mems.getD 83 []) (cert[83]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_83 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[83]'(by decide +kernel)).2 (cert[83]'(by decide +kernel)).1.frame (mems.getD 83 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_84 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[84]'(by decide +kernel)).1.rets (cert[84]'(by decide +kernel)).1.pc
      (cert[84]'(by decide +kernel)).1.frame (mems.getD 84 []) (cert[84]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_84 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[84]'(by decide +kernel)).2 (cert[84]'(by decide +kernel)).1.frame (mems.getD 84 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_85 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[85]'(by decide +kernel)).1.rets (cert[85]'(by decide +kernel)).1.pc
      (cert[85]'(by decide +kernel)).1.frame (mems.getD 85 []) (cert[85]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_85 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[85]'(by decide +kernel)).2 (cert[85]'(by decide +kernel)).1.frame (mems.getD 85 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_86 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[86]'(by decide +kernel)).1.rets (cert[86]'(by decide +kernel)).1.pc
      (cert[86]'(by decide +kernel)).1.frame (mems.getD 86 []) (cert[86]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_86 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[86]'(by decide +kernel)).2 (cert[86]'(by decide +kernel)).1.frame (mems.getD 86 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable
