import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Cert
import Blanc.Lift.CheckFast

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Each entry is decided against trie-backed reads of the exact runtime.
The generic equalities rewrite each result to Cert.checkM / Cert.jumpsOkM. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable

open Jaune

/-- Depth 15 covers all 17535 runtime byte positions. -/
def codeTries : CodeTries code 15 :=
  CodeTries.ofCode code 15 (by decide +kernel) (by decide +kernel)

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable
