import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 34..61, each decided against trie-backed reads of the exact runtime.
The generic equalities rewrite each result to Cert.checkM / Cert.jumpsOkM. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable

open Jaune

theorem entry_34 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[34]'(by decide +kernel)).1.rets (cert[34]'(by decide +kernel)).1.pc
      (cert[34]'(by decide +kernel)).1.frame (mems.getD 34 []) (cert[34]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_34 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[34]'(by decide +kernel)).2 (cert[34]'(by decide +kernel)).1.frame (mems.getD 34 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_35 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[35]'(by decide +kernel)).1.rets (cert[35]'(by decide +kernel)).1.pc
      (cert[35]'(by decide +kernel)).1.frame (mems.getD 35 []) (cert[35]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_35 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[35]'(by decide +kernel)).2 (cert[35]'(by decide +kernel)).1.frame (mems.getD 35 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_36 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[36]'(by decide +kernel)).1.rets (cert[36]'(by decide +kernel)).1.pc
      (cert[36]'(by decide +kernel)).1.frame (mems.getD 36 []) (cert[36]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_36 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[36]'(by decide +kernel)).2 (cert[36]'(by decide +kernel)).1.frame (mems.getD 36 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_37 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[37]'(by decide +kernel)).1.rets (cert[37]'(by decide +kernel)).1.pc
      (cert[37]'(by decide +kernel)).1.frame (mems.getD 37 []) (cert[37]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_37 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[37]'(by decide +kernel)).2 (cert[37]'(by decide +kernel)).1.frame (mems.getD 37 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_38 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[38]'(by decide +kernel)).1.rets (cert[38]'(by decide +kernel)).1.pc
      (cert[38]'(by decide +kernel)).1.frame (mems.getD 38 []) (cert[38]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_38 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[38]'(by decide +kernel)).2 (cert[38]'(by decide +kernel)).1.frame (mems.getD 38 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_39 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[39]'(by decide +kernel)).1.rets (cert[39]'(by decide +kernel)).1.pc
      (cert[39]'(by decide +kernel)).1.frame (mems.getD 39 []) (cert[39]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_39 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[39]'(by decide +kernel)).2 (cert[39]'(by decide +kernel)).1.frame (mems.getD 39 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_40 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[40]'(by decide +kernel)).1.rets (cert[40]'(by decide +kernel)).1.pc
      (cert[40]'(by decide +kernel)).1.frame (mems.getD 40 []) (cert[40]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_40 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[40]'(by decide +kernel)).2 (cert[40]'(by decide +kernel)).1.frame (mems.getD 40 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_41 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[41]'(by decide +kernel)).1.rets (cert[41]'(by decide +kernel)).1.pc
      (cert[41]'(by decide +kernel)).1.frame (mems.getD 41 []) (cert[41]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_41 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[41]'(by decide +kernel)).2 (cert[41]'(by decide +kernel)).1.frame (mems.getD 41 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_42 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[42]'(by decide +kernel)).1.rets (cert[42]'(by decide +kernel)).1.pc
      (cert[42]'(by decide +kernel)).1.frame (mems.getD 42 []) (cert[42]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_42 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[42]'(by decide +kernel)).2 (cert[42]'(by decide +kernel)).1.frame (mems.getD 42 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_43 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[43]'(by decide +kernel)).1.rets (cert[43]'(by decide +kernel)).1.pc
      (cert[43]'(by decide +kernel)).1.frame (mems.getD 43 []) (cert[43]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_43 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[43]'(by decide +kernel)).2 (cert[43]'(by decide +kernel)).1.frame (mems.getD 43 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_44 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[44]'(by decide +kernel)).1.rets (cert[44]'(by decide +kernel)).1.pc
      (cert[44]'(by decide +kernel)).1.frame (mems.getD 44 []) (cert[44]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_44 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[44]'(by decide +kernel)).2 (cert[44]'(by decide +kernel)).1.frame (mems.getD 44 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_45 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[45]'(by decide +kernel)).1.rets (cert[45]'(by decide +kernel)).1.pc
      (cert[45]'(by decide +kernel)).1.frame (mems.getD 45 []) (cert[45]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_45 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[45]'(by decide +kernel)).2 (cert[45]'(by decide +kernel)).1.frame (mems.getD 45 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_46 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[46]'(by decide +kernel)).1.rets (cert[46]'(by decide +kernel)).1.pc
      (cert[46]'(by decide +kernel)).1.frame (mems.getD 46 []) (cert[46]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_46 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[46]'(by decide +kernel)).2 (cert[46]'(by decide +kernel)).1.frame (mems.getD 46 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_47 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[47]'(by decide +kernel)).1.rets (cert[47]'(by decide +kernel)).1.pc
      (cert[47]'(by decide +kernel)).1.frame (mems.getD 47 []) (cert[47]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_47 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[47]'(by decide +kernel)).2 (cert[47]'(by decide +kernel)).1.frame (mems.getD 47 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_48 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[48]'(by decide +kernel)).1.rets (cert[48]'(by decide +kernel)).1.pc
      (cert[48]'(by decide +kernel)).1.frame (mems.getD 48 []) (cert[48]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_48 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[48]'(by decide +kernel)).2 (cert[48]'(by decide +kernel)).1.frame (mems.getD 48 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_49 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[49]'(by decide +kernel)).1.rets (cert[49]'(by decide +kernel)).1.pc
      (cert[49]'(by decide +kernel)).1.frame (mems.getD 49 []) (cert[49]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_49 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[49]'(by decide +kernel)).2 (cert[49]'(by decide +kernel)).1.frame (mems.getD 49 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_50 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[50]'(by decide +kernel)).1.rets (cert[50]'(by decide +kernel)).1.pc
      (cert[50]'(by decide +kernel)).1.frame (mems.getD 50 []) (cert[50]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_50 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[50]'(by decide +kernel)).2 (cert[50]'(by decide +kernel)).1.frame (mems.getD 50 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_51 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[51]'(by decide +kernel)).1.rets (cert[51]'(by decide +kernel)).1.pc
      (cert[51]'(by decide +kernel)).1.frame (mems.getD 51 []) (cert[51]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_51 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[51]'(by decide +kernel)).2 (cert[51]'(by decide +kernel)).1.frame (mems.getD 51 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_52 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[52]'(by decide +kernel)).1.rets (cert[52]'(by decide +kernel)).1.pc
      (cert[52]'(by decide +kernel)).1.frame (mems.getD 52 []) (cert[52]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_52 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[52]'(by decide +kernel)).2 (cert[52]'(by decide +kernel)).1.frame (mems.getD 52 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_53 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[53]'(by decide +kernel)).1.rets (cert[53]'(by decide +kernel)).1.pc
      (cert[53]'(by decide +kernel)).1.frame (mems.getD 53 []) (cert[53]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_53 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[53]'(by decide +kernel)).2 (cert[53]'(by decide +kernel)).1.frame (mems.getD 53 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_54 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[54]'(by decide +kernel)).1.rets (cert[54]'(by decide +kernel)).1.pc
      (cert[54]'(by decide +kernel)).1.frame (mems.getD 54 []) (cert[54]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_54 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[54]'(by decide +kernel)).2 (cert[54]'(by decide +kernel)).1.frame (mems.getD 54 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_55 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[55]'(by decide +kernel)).1.rets (cert[55]'(by decide +kernel)).1.pc
      (cert[55]'(by decide +kernel)).1.frame (mems.getD 55 []) (cert[55]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_55 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[55]'(by decide +kernel)).2 (cert[55]'(by decide +kernel)).1.frame (mems.getD 55 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_56 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[56]'(by decide +kernel)).1.rets (cert[56]'(by decide +kernel)).1.pc
      (cert[56]'(by decide +kernel)).1.frame (mems.getD 56 []) (cert[56]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_56 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[56]'(by decide +kernel)).2 (cert[56]'(by decide +kernel)).1.frame (mems.getD 56 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_57 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[57]'(by decide +kernel)).1.rets (cert[57]'(by decide +kernel)).1.pc
      (cert[57]'(by decide +kernel)).1.frame (mems.getD 57 []) (cert[57]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_57 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[57]'(by decide +kernel)).2 (cert[57]'(by decide +kernel)).1.frame (mems.getD 57 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_58 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[58]'(by decide +kernel)).1.rets (cert[58]'(by decide +kernel)).1.pc
      (cert[58]'(by decide +kernel)).1.frame (mems.getD 58 []) (cert[58]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_58 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[58]'(by decide +kernel)).2 (cert[58]'(by decide +kernel)).1.frame (mems.getD 58 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_59 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[59]'(by decide +kernel)).1.rets (cert[59]'(by decide +kernel)).1.pc
      (cert[59]'(by decide +kernel)).1.frame (mems.getD 59 []) (cert[59]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_59 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[59]'(by decide +kernel)).2 (cert[59]'(by decide +kernel)).1.frame (mems.getD 59 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_60 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[60]'(by decide +kernel)).1.rets (cert[60]'(by decide +kernel)).1.pc
      (cert[60]'(by decide +kernel)).1.frame (mems.getD 60 []) (cert[60]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_60 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[60]'(by decide +kernel)).2 (cert[60]'(by decide +kernel)).1.frame (mems.getD 60 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

theorem entry_61 :
    checkNodeM code (Cert.entries cert) mems true
      (cert[61]'(by decide +kernel)).1.rets (cert[61]'(by decide +kernel)).1.pc
      (cert[61]'(by decide +kernel)).1.frame (mems.getD 61 []) (cert[61]'(by decide +kernel)).2 = true := by
  rw [← checkNodeMT_eq codeTries]
  decide +kernel

theorem jumps_61 :
    jumpsOkNodeM code (Cert.entries cert) true
      (cert[61]'(by decide +kernel)).2 (cert[61]'(by decide +kernel)).1.frame (mems.getD 61 []) = true := by
  rw [← jumpsOkNodeMT_eq codeTries]
  decide +kernel

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable
