import Blanc.Lift.Curve3Crv.Cert
import Blanc.Lift.CheckFast

/-! The deployed 3Crv certificate checks against the pinned runtime bytes: one kernel decision
per entry, assembled into `cert_check`. Each decision runs on the trie-reading copy
`checkNodeT` (`Blanc/Lift/CheckFast.lean`), which `checkNodeT_eq` equates with `checkNode`.
GENERATED by Plans
evidence/vyper-3crv-bytecode-v1/v1/gen_family.py -- do not edit. -/

namespace Blanc.Lift.Curve3Crv

/-- The code's byte and instruction-start tries (depth 12: 4096 ≥ 2276 positions). -/
def codeTries : CodeTries code 12 :=
  CodeTries.ofCode code 12 (by decide +kernel) (by decide +kernel)

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0x1cf [.unk, .unk, .unk, .unk, .unk, .unk] t_01cf_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x229 [.unk, .unk, .unk, .unk, .unk, .unk] t_0229_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 0 0x45b [] t_045b_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0x4f6 [.unk] t_04f6_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0x774 [.unk, .unk, .unk, .unk, .unk, .unk] t_0774_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 0 0x828 [.unk, .unk, .unk, .unk, .unk, .unk] t_0828_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_7 :
    checkNode code (Cert.entries cert) 0 0x8de [] t_08de_c7 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_8 :
    checkNode code (Cert.entries cert) 0 0x19a [.unk, .unk, .unk, .unk, .unk, .unk] t_019a_c8 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_9 :
    checkNode code (Cert.entries cert) 0 0x73f [.unk, .unk, .unk, .unk, .unk, .unk] t_073f_c9 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_10 :
    checkNode code (Cert.entries cert) 0 0x7f3 [.unk, .unk, .unk, .unk, .unk, .unk] t_07f3_c10 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_11 :
    checkNode code (Cert.entries cert) 0 0x1f4 [.unk, .unk, .unk, .unk, .unk, .unk] t_01f4_c11 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem cert_check : Cert.check code cert = true := by
  unfold Cert.check
  rw [Bool.and_eq_true]
  refine ⟨by decide +kernel, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact entry_0
  · exact entry_1
  · exact entry_2
  · exact entry_3
  · exact entry_4
  · exact entry_5
  · exact entry_6
  · exact entry_7
  · exact entry_8
  · exact entry_9
  · exact entry_10
  · exact entry_11

end Blanc.Lift.Curve3Crv
