import Blanc.Lift.Exact
import Blanc.Lift.Curve3Crv.Lift

/-! The deployed 3Crv certificate's jump destinations are valid: one kernel decision per entry.
GENERATED by Plans evidence/vyper-3crv-bytecode-v1/v1/gen_family.py -- do not edit. -/

namespace Blanc.Lift.Curve3Crv

open Jaune

theorem jumps_0 :
    jumpsOkNode code (Cert.entries cert) t_0000_c0 [] = true := by
  decide +kernel

theorem jumps_1 :
    jumpsOkNode code (Cert.entries cert) t_01cf_c1 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_2 :
    jumpsOkNode code (Cert.entries cert) t_0229_c2 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_3 :
    jumpsOkNode code (Cert.entries cert) t_045b_c3 [] = true := by
  decide +kernel

theorem jumps_4 :
    jumpsOkNode code (Cert.entries cert) t_04f6_c4 [.unk] = true := by
  decide +kernel

theorem jumps_5 :
    jumpsOkNode code (Cert.entries cert) t_0774_c5 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_6 :
    jumpsOkNode code (Cert.entries cert) t_0828_c6 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_7 :
    jumpsOkNode code (Cert.entries cert) t_08de_c7 [] = true := by
  decide +kernel

theorem jumps_8 :
    jumpsOkNode code (Cert.entries cert) t_019a_c8 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_9 :
    jumpsOkNode code (Cert.entries cert) t_073f_c9 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_10 :
    jumpsOkNode code (Cert.entries cert) t_07f3_c10 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_11 :
    jumpsOkNode code (Cert.entries cert) t_01f4_c11 [.unk, .unk, .unk, .unk, .unk, .unk] = true := by
  decide +kernel

theorem jumps_ok : Cert.jumpsOk code cert = true := by
  unfold Cert.jumpsOk
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact jumps_0
  · exact jumps_1
  · exact jumps_2
  · exact jumps_3
  · exact jumps_4
  · exact jumps_5
  · exact jumps_6
  · exact jumps_7
  · exact jumps_8
  · exact jumps_9
  · exact jumps_10
  · exact jumps_11

/-- The converse bridge at the pinned deployed 3Crv bytes: a gas-exact synthetic run of the lifted
program is a real Jaune execution of the deployed code. -/
theorem exec_of_runExact {sevm : Sevm} {pre post : Devm} (hcode : sevm.code = code)
    (hfork : CoveredFork sevm.benvStat.fork) (hrun : SProg.RunExact prog sevm pre post) :
    Nonempty (Exec 0 sevm pre (.ok post)) :=
  lift_exact cert_check jumps_ok hcode hfork hrun

end Blanc.Lift.Curve3Crv
