import Blanc.Lift.Check
import Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation.Input

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Token20.Creation.Check.cert_check checks the synthetic token creation input. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation

open Jaune

-- Code: 315 bytes, SHA-256: 66682b144c4be426ec7f993606ee7d8078011b4a024e4d09f11f251121810e89
def code : ByteArray := Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation.creationCode

def t_0000_c0 : SFunc := (.next (.push [0x0f, 0x42, 0x40] (by decide)) (.next (.reg .caller) (.next (.reg .sstore) (.next (.push [0x01, 0x2b] (by decide)) (.next (.reg .returndatasize) (.next (.reg (.dup 1)) (.next (.push [0x10] (by decide)) (.next (.reg .returndatasize) (.next (.reg .codecopy) (.last .return_))))))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation
