import Blanc.Lift.CheckAssembly
import Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation.Cert
import Blanc.Lift.CheckFast

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Each entry is decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation

open Jaune

/-- Depth 9 covers all 315 runtime byte positions. -/
def codeTries : CodeTries code 9 :=
  CodeTries.ofCode code 9 (by decide +kernel) (by decide +kernel)

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem cert_check : Cert.check code cert = true := by
  exact Cert.check_singleton (by decide +kernel) entry_0

end Blanc.Lift.VyperNonreentrantDeployed.Token20.Creation
