import Blanc.Lift.Check
import Blanc.SystemContracts

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit. -/

namespace Blanc.Lift.BeaconRoots

open Jaune

-- Code: 97 bytes, SHA-256: cb7bd3e115730f7d57c15cd892880ed517ff4421bf43dfc7591198868fffe31d
def code : ByteArray := Blanc.beaconRootsCode

def t_0021_c0 : SFunc := (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.last .revert)))
def t_0039_c0 : SFunc := (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.last .revert)))
def t_003c_c0 : SFunc := (.dest (.next (.push [0x00, 0x1f, 0xff] (by decide)) (.next (.reg .add) (.next (.reg .sload) (.next (.push [] (by decide)) (.next (.reg .mstore) (.next (.push [0x20] (by decide)) (.next (.push [] (by decide)) (.last .return_)))))))))
def t_002c_c0 : SFunc := (.next (.push [0x00, 0x1f, 0xff] (by decide)) (.next (.reg (.dup 1)) (.next (.reg .mod) (.next (.reg (.swap 0)) (.next (.reg (.dup 1)) (.next (.reg .sload) (.next (.reg .eq) (.next (.push [0x3c] (by decide)) (.branch t_0039_c0 t_003c_c0)))))))))
def t_0049_c0 : SFunc := (.dest (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.last .revert))))
def t_0024_c0 : SFunc := (.dest (.next (.push [] (by decide)) (.next (.reg .calldataload) (.next (.reg (.dup 0)) (.next (.reg .iszero) (.next (.push [0x49] (by decide)) (.branch t_002c_c0 t_0049_c0)))))))
def t_001a_c0 : SFunc := (.next (.push [0x20] (by decide)) (.next (.reg .calldatasize) (.next (.reg .eq) (.next (.push [0x24] (by decide)) (.branch t_0021_c0 t_0024_c0)))))
def t_004d_c0 : SFunc := (.dest (.next (.push [0x00, 0x1f, 0xff] (by decide)) (.next (.reg .timestamp) (.next (.reg .mod) (.next (.reg .timestamp) (.next (.reg (.dup 1)) (.next (.reg .sstore) (.next (.push [] (by decide)) (.next (.reg .calldataload) (.next (.reg (.swap 0)) (.next (.push [0x00, 0x1f, 0xff] (by decide)) (.next (.reg .add) (.next (.reg .sstore) (.last .stop))))))))))))))
def t_0000_c0 : SFunc := (.next (.reg .caller) (.next (.push [0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe] (by decide)) (.next (.reg .eq) (.next (.push [0x4d] (by decide)) (.branch t_001a_c0 t_004d_c0)))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.BeaconRoots
