import Blanc.Lift.LidoCircuitBreakerDeployed.Cert
import Blanc.Lift.CheckFast

/-! GENERATED by Plans evidence/deployed-lido-vyper-v1/certificate/generate.py -- do not edit.
Each entry is decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.LidoCircuitBreakerDeployed

open Jaune

/-- Depth 13 covers all 4584 runtime byte positions. -/
def codeTries : CodeTries code 13 :=
  CodeTries.ofCode code 13 (by decide +kernel) (by decide +kernel)

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0x121 [.unk, (.const (Nat.toB256 0x121)), .unk] t_0121_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x409 [.unk, .unk, .unk, .unk, .ret] t_0409_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 1 0x51a [.unk, .unk, .unk, .ret] t_051a_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0xa81 [.unk, .unk, .unk, .unk, .ret] t_0a81_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0xc5e [.unk, .unk, .unk, .unk, .ret] t_0c5e_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 1 0xd9f [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_0d9f_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_7 :
    checkNode code (Cert.entries cert) 1 0xfec [.unk, .unk, .ret] t_0fec_c7 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_8 :
    checkNode code (Cert.entries cert) 1 0x1064 [.unk, .unk, .ret] t_1064_c8 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_9 :
    checkNode code (Cert.entries cert) 0 0x8bc [.unk, .ret] t_08bc_c9 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_10 :
    checkNode code (Cert.entries cert) 0 0x30c [.unk, .unk] t_030c_c10 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_11 :
    checkNode code (Cert.entries cert) 1 0x892 [.unk, .ret] t_0892_c11 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_12 :
    checkNode code (Cert.entries cert) 0 0x531 [.unk, .ret] t_0531_c12 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_13 :
    checkNode code (Cert.entries cert) 0 0x5ac [.unk, .ret] t_05ac_c13 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_14 :
    checkNode code (Cert.entries cert) 0 0x450 [.ret] t_0450_c14 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_15 :
    checkNode code (Cert.entries cert) 1 0x4f0 [.unk, .ret] t_04f0_c15 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_16 :
    checkNode code (Cert.entries cert) 0 0x12b [.unk, .unk] t_012b_c16 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_17 :
    checkNode code (Cert.entries cert) 1 0x520 [.ret] t_0520_c17 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_18 :
    checkNode code (Cert.entries cert) 1 0x100c [.unk, .unk, .ret] t_100c_c18 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_19 :
    checkNode code (Cert.entries cert) 0 0x182 [.unk, (.const (Nat.toB256 0x182)), .unk] t_0182_c19 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_20 :
    checkNode code (Cert.entries cert) 2 0xfbb [.unk, .unk, .ret] t_0fbb_c20 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_21 :
    checkNode code (Cert.entries cert) 0 0x31c [.unk, .unk, .ret] t_031c_c21 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_22 :
    checkNode code (Cert.entries cert) 0 0xcd5 [.unk, .unk, .ret] t_0cd5_c22 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_23 :
    checkNode code (Cert.entries cert) 1 0x10a8 [.unk, .unk, .ret] t_10a8_c23 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_24 :
    checkNode code (Cert.entries cert) 1 0x110e [.unk, .ret] t_110e_c24 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_25 :
    checkNode code (Cert.entries cert) 1 0x1145 [.unk, .unk, .ret] t_1145_c25 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_26 :
    checkNode code (Cert.entries cert) 0 0x1158 [(.const (Nat.toB256 0xb27)), .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_1158_c26 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_27 :
    checkNode code (Cert.entries cert) 0 0x1158 [(.const (Nat.toB256 0xb6a)), .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_1158_c27 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_28 :
    checkNode code (Cert.entries cert) 0 0x1185 [(.const (Nat.toB256 0xbdc)), .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_1185_c28 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_29 :
    checkNode code (Cert.entries cert) 1 0xf93 [.unk, .ret] t_0f93_c29 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_30 :
    checkNode code (Cert.entries cert) 0 0xea0 [.unk, .ret] t_0ea0_c30 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_31 :
    checkNode code (Cert.entries cert) 0 0xdab [.unk, .ret] t_0dab_c31 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_32 :
    checkNode code (Cert.entries cert) 0 0x934 [.unk, .unk, .unk, .ret] t_0934_c32 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_33 :
    checkNode code (Cert.entries cert) 1 0x10bb [.unk, .unk, .ret] t_10bb_c33 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_34 :
    checkNode code (Cert.entries cert) 1 0xd3a [.unk, .ret] t_0d3a_c34 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_35 :
    checkNode code (Cert.entries cert) 1 0x1025 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_1025_c35 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_36 :
    checkNode code (Cert.entries cert) 0 0x12b [.unk, (.const (Nat.toB256 0x182)), .unk] t_012b_c36 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_37 :
    checkNode code (Cert.entries cert) 0 0xd2e [.unk, .unk, .unk, .unk, .unk, .ret] t_0d2e_c37 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_38 :
    checkNode code (Cert.entries cert) 1 0x107b [(.const (Nat.toB256 0x51a)), .unk, .unk, .unk, .ret] t_107b_c38 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_39 :
    checkNode code (Cert.entries cert) 1 0x107b [(.const (Nat.toB256 0x113e)), .unk, .unk, .ret] t_107b_c39 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_40 :
    checkNode code (Cert.entries cert) 1 0x10da [.unk, .ret] t_10da_c40 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_41 :
    checkNode code (Cert.entries cert) 1 0xd74 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_0d74_c41 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_42 :
    checkNode code (Cert.entries cert) 1 0x107b [(.const (Nat.toB256 0x10e8)), .unk, .unk, .ret] t_107b_c42 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_43 :
    checkNode code (Cert.entries cert) 0 0x2a3 [.unk] t_02a3_c43 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_44 :
    checkNode code (Cert.entries cert) 0 0x2c2 [.unk] t_02c2_c44 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_45 :
    checkNode code (Cert.entries cert) 0 0x2d5 [.unk] t_02d5_c45 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_46 :
    checkNode code (Cert.entries cert) 0 0x269 [.unk] t_0269_c46 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_47 :
    checkNode code (Cert.entries cert) 0 0x27c [.unk] t_027c_c47 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_48 :
    checkNode code (Cert.entries cert) 0 0x1f5 [.unk] t_01f5_c48 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_49 :
    checkNode code (Cert.entries cert) 0 0x208 [.unk] t_0208_c49 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_50 :
    checkNode code (Cert.entries cert) 0 0x21b [.unk] t_021b_c50 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_51 :
    checkNode code (Cert.entries cert) 0 0x242 [.unk] t_0242_c51 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_52 :
    checkNode code (Cert.entries cert) 0 0x1bc [.unk] t_01bc_c52 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_53 :
    checkNode code (Cert.entries cert) 0 0x1c4 [.unk] t_01c4_c53 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_54 :
    checkNode code (Cert.entries cert) 0 0x1d7 [.unk] t_01d7_c54 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_55 :
    checkNode code (Cert.entries cert) 0 0x1ec [.unk] t_01ec_c55 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_56 :
    checkNode code (Cert.entries cert) 0 0x119 [.unk] t_0119_c56 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_57 :
    checkNode code (Cert.entries cert) 0 0x134 [.unk] t_0134_c57 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_58 :
    checkNode code (Cert.entries cert) 0 0x15b [.unk] t_015b_c58 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_59 :
    checkNode code (Cert.entries cert) 0 0x1a7 [.unk] t_01a7_c59 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem cert_check : Cert.check code cert = true := by
  unfold Cert.check
  rw [Bool.and_eq_true]
  refine ⟨by decide +kernel, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact entry_0
  · exact entry_1
  · exact entry_2
  · exact entry_3
  · exact entry_4
  · exact entry_5
  · exact entry_6
  · exact entry_7
  · exact entry_8
  · exact entry_9
  · exact entry_10
  · exact entry_11
  · exact entry_12
  · exact entry_13
  · exact entry_14
  · exact entry_15
  · exact entry_16
  · exact entry_17
  · exact entry_18
  · exact entry_19
  · exact entry_20
  · exact entry_21
  · exact entry_22
  · exact entry_23
  · exact entry_24
  · exact entry_25
  · exact entry_26
  · exact entry_27
  · exact entry_28
  · exact entry_29
  · exact entry_30
  · exact entry_31
  · exact entry_32
  · exact entry_33
  · exact entry_34
  · exact entry_35
  · exact entry_36
  · exact entry_37
  · exact entry_38
  · exact entry_39
  · exact entry_40
  · exact entry_41
  · exact entry_42
  · exact entry_43
  · exact entry_44
  · exact entry_45
  · exact entry_46
  · exact entry_47
  · exact entry_48
  · exact entry_49
  · exact entry_50
  · exact entry_51
  · exact entry_52
  · exact entry_53
  · exact entry_54
  · exact entry_55
  · exact entry_56
  · exact entry_57
  · exact entry_58
  · exact entry_59

end Blanc.Lift.LidoCircuitBreakerDeployed
