import Blanc.Lift.UniswapV2Pair.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 75..101, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.UniswapV2Pair

open Jaune

theorem entry_75 :
    checkNode code (Cert.entries cert) 0 0x5da [.unk] t_05da_c75 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_76 :
    checkNode code (Cert.entries cert) 0 0x5e2 [.unk] t_05e2_c76 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_77 :
    checkNode code (Cert.entries cert) 0 0x640 [.unk] t_0640_c77 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_78 :
    checkNode code (Cert.entries cert) 0 0x67b [.unk] t_067b_c78 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_79 :
    checkNode code (Cert.entries cert) 0 0x597 [.unk] t_0597_c79 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_80 :
    checkNode code (Cert.entries cert) 0 0x59f [.unk] t_059f_c80 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_81 :
    checkNode code (Cert.entries cert) 0 0x5d2 [.unk] t_05d2_c81 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_82 :
    checkNode code (Cert.entries cert) 0 0x4d7 [.unk] t_04d7_c82 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_83 :
    checkNode code (Cert.entries cert) 0 0x50a [.unk] t_050a_c83 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_84 :
    checkNode code (Cert.entries cert) 0 0x556 [.unk] t_0556_c84 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_85 :
    checkNode code (Cert.entries cert) 0 0x55e [.unk] t_055e_c85 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_86 :
    checkNode code (Cert.entries cert) 0 0x469 [.unk] t_0469_c86 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_87 :
    checkNode code (Cert.entries cert) 0 0x49c [.unk] t_049c_c87 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_88 :
    checkNode code (Cert.entries cert) 0 0x4cf [.unk] t_04cf_c88 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_89 :
    checkNode code (Cert.entries cert) 0 0x416 [.unk] t_0416_c89 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_90 :
    checkNode code (Cert.entries cert) 0 0x41e [.unk] t_041e_c90 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_91 :
    checkNode code (Cert.entries cert) 0 0x459 [.unk] t_0459_c91 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_92 :
    checkNode code (Cert.entries cert) 0 0x461 [.unk] t_0461_c92 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_93 :
    checkNode code (Cert.entries cert) 0 0x3ad [.unk] t_03ad_c93 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_94 :
    checkNode code (Cert.entries cert) 0 0x3f0 [.unk] t_03f0_c94 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_95 :
    checkNode code (Cert.entries cert) 0 0x3f8 [.unk] t_03f8_c95 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_96 :
    checkNode code (Cert.entries cert) 0 0x315 [.unk] t_0315_c96 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_97 :
    checkNode code (Cert.entries cert) 0 0x362 [.unk] t_0362_c97 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_98 :
    checkNode code (Cert.entries cert) 0 0x393 [.unk] t_0393_c98 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_99 :
    checkNode code (Cert.entries cert) 0 0x1be [.unk] t_01be_c99 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_100 :
    checkNode code (Cert.entries cert) 0 0x259 [.unk] t_0259_c100 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_101 :
    checkNode code (Cert.entries cert) 0 0x2d6 [.unk] t_02d6_c101 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.UniswapV2Pair
