import Blanc.Lift.UniswapV2Pair.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Entries 48..74, each decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.UniswapV2Pair

open Jaune

theorem entry_48 :
    checkNode code (Cert.entries cert) 1 0xe1e [.unk, .unk, .unk, .ret] t_0e1e_c48 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_49 :
    checkNode code (Cert.entries cert) 2 0xefd [.ret] t_0efd_c49 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_50 :
    checkNode code (Cert.entries cert) 2 0xf21 [.ret] t_0f21_c50 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_51 :
    checkNode code (Cert.entries cert) 1 0xde5 [.unk, .unk, .ret] t_0de5_c51 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_52 :
    checkNode code (Cert.entries cert) 2 0xdfc [.ret] t_0dfc_c52 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_53 :
    checkNode code (Cert.entries cert) 2 0xe18 [.ret] t_0e18_c53 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_54 :
    checkNode code (Cert.entries cert) 0 0x683 [.unk, .unk, .unk, .unk, .unk, .ret] t_0683_c54 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_55 :
    checkNode code (Cert.entries cert) 2 0xd57 [.ret] t_0d57_c55 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_56 :
    checkNode code (Cert.entries cert) 3 0xd90 [.ret] t_0d90_c56 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_57 :
    checkNode code (Cert.entries cert) 0 0x1fdb [.unk, .unk, .unk, .ret] t_1fdb_c57 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_58 :
    checkNode code (Cert.entries cert) 1 0x21e8 [.unk, .unk, .ret] t_21e8_c58 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_59 :
    checkNode code (Cert.entries cert) 1 0x226e [.unk, .unk, .ret] t_226e_c59 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_60 :
    checkNode code (Cert.entries cert) 0 0x22e0 [.unk, .unk, .unk, .unk, .ret] t_22e0_c60 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_61 :
    checkNode code (Cert.entries cert) 0 0x260b [.unk, .unk, .unk, .ret] t_260b_c61 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_62 :
    checkNode code (Cert.entries cert) 0 0x28ca [.unk, .unk, .ret] t_28ca_c62 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_63 :
    checkNode code (Cert.entries cert) 0 0x2992 [.unk, .unk, .ret] t_2992_c63 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_64 :
    checkNode code (Cert.entries cert) 0 0x259c [.unk, .unk, .unk, .ret] t_259c_c64 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_65 :
    checkNode code (Cert.entries cert) 1 0x2a57 [.unk, .ret] t_2a57_c65 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_66 :
    checkNode code (Cert.entries cert) 1 0x2a7b [.unk, .unk, .ret] t_2a7b_c66 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_67 :
    checkNode code (Cert.entries cert) 0 0x19ee [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, (.const (Nat.toB256 0x1a26)), .unk, .unk, (.const (Nat.toB256 0x1aca)), .unk, .unk, .unk, (.const (Nat.toB256 0x257)), .unk] t_19ee_c67 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_68 :
    checkNode code (Cert.entries cert) 1 0x26ec [.unk, .unk, .ret] t_26ec_c68 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_69 :
    checkNode code (Cert.entries cert) 1 0x2878 [.unk, .ret] t_2878_c69 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_70 :
    checkNode code (Cert.entries cert) 1 0x297a [.unk, .unk, .ret] t_297a_c70 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_71 :
    checkNode code (Cert.entries cert) 0 0x20a4 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] t_20a4_c71 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_72 :
    checkNode code (Cert.entries cert) 1 0x2abc [.unk, .unk, .ret] t_2abc_c72 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_73 :
    checkNode code (Cert.entries cert) 0 0x257 [.unk] t_0257_c73 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_74 :
    checkNode code (Cert.entries cert) 1 0x288d [.unk, .unk, .unk, .ret] t_288d_c74 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

end Blanc.Lift.UniswapV2Pair
