import Blanc.Lift.UniswapV2Pair.CheckPart0
import Blanc.Lift.UniswapV2Pair.CheckPart1
import Blanc.Lift.UniswapV2Pair.CheckPart2
import Blanc.Lift.UniswapV2Pair.CheckPart3

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Assembles the per-entry decisions of the CheckPart modules.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.UniswapV2Pair

open Jaune

theorem cert_check : Cert.check code cert = true := by
  unfold Cert.check
  rw [Bool.and_eq_true]
  refine ⟨by decide +kernel, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact entry_0
  · exact entry_1
  · exact entry_2
  · exact entry_3
  · exact entry_4
  · exact entry_5
  · exact entry_6
  · exact entry_7
  · exact entry_8
  · exact entry_9
  · exact entry_10
  · exact entry_11
  · exact entry_12
  · exact entry_13
  · exact entry_14
  · exact entry_15
  · exact entry_16
  · exact entry_17
  · exact entry_18
  · exact entry_19
  · exact entry_20
  · exact entry_21
  · exact entry_22
  · exact entry_23
  · exact entry_24
  · exact entry_25
  · exact entry_26
  · exact entry_27
  · exact entry_28
  · exact entry_29
  · exact entry_30
  · exact entry_31
  · exact entry_32
  · exact entry_33
  · exact entry_34
  · exact entry_35
  · exact entry_36
  · exact entry_37
  · exact entry_38
  · exact entry_39
  · exact entry_40
  · exact entry_41
  · exact entry_42
  · exact entry_43
  · exact entry_44
  · exact entry_45
  · exact entry_46
  · exact entry_47
  · exact entry_48
  · exact entry_49
  · exact entry_50
  · exact entry_51
  · exact entry_52
  · exact entry_53
  · exact entry_54
  · exact entry_55
  · exact entry_56
  · exact entry_57
  · exact entry_58
  · exact entry_59
  · exact entry_60
  · exact entry_61
  · exact entry_62
  · exact entry_63
  · exact entry_64
  · exact entry_65
  · exact entry_66
  · exact entry_67
  · exact entry_68
  · exact entry_69
  · exact entry_70
  · exact entry_71
  · exact entry_72
  · exact entry_73
  · exact entry_74
  · exact entry_75
  · exact entry_76
  · exact entry_77
  · exact entry_78
  · exact entry_79
  · exact entry_80
  · exact entry_81
  · exact entry_82
  · exact entry_83
  · exact entry_84
  · exact entry_85
  · exact entry_86
  · exact entry_87
  · exact entry_88
  · exact entry_89
  · exact entry_90
  · exact entry_91
  · exact entry_92
  · exact entry_93
  · exact entry_94
  · exact entry_95
  · exact entry_96
  · exact entry_97
  · exact entry_98
  · exact entry_99
  · exact entry_100
  · exact entry_101

end Blanc.Lift.UniswapV2Pair
