import Blanc.Lift.UniswapV2Pair.CheckTries

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Jump destinations are checked against the exact runtime, one kernel decision per entry. -/

namespace Blanc.Lift.UniswapV2Pair

open Jaune

theorem jumps_0 :
    jumpsOkNode code (Cert.entries cert) t_0000_c0 [] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_1 :
    jumpsOkNode code (Cert.entries cert) t_02c8_c1 [.unk, .unk, .unk, .unk, .unk, .unk, .unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_2 :
    jumpsOkNode code (Cert.entries cert) t_0707_c2 [.unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_3 :
    jumpsOkNode code (Cert.entries cert) t_079a_c3 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_4 :
    jumpsOkNode code (Cert.entries cert) t_0854_c4 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_5 :
    jumpsOkNode code (Cert.entries cert) t_09c3_c5 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_6 :
    jumpsOkNode code (Cert.entries cert) t_0b35_c6 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_7 :
    jumpsOkNode code (Cert.entries cert) t_0b6f_c7 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_8 :
    jumpsOkNode code (Cert.entries cert) t_0b80_c8 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_9 :
    jumpsOkNode code (Cert.entries cert) t_0df6_c9 [.unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_10 :
    jumpsOkNode code (Cert.entries cert) t_0ee8_c10 [.unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_11 :
    jumpsOkNode code (Cert.entries cert) t_12cd_c11 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_12 :
    jumpsOkNode code (Cert.entries cert) t_137e_c12 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_13 :
    jumpsOkNode code (Cert.entries cert) t_162e_c13 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_14 :
    jumpsOkNode code (Cert.entries cert) t_1827_c14 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_15 :
    jumpsOkNode code (Cert.entries cert) t_1d57_c15 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_16 :
    jumpsOkNode code (Cert.entries cert) t_2148_c16 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_17 :
    jumpsOkNode code (Cert.entries cert) t_2176_c17 [.unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_18 :
    jumpsOkNode code (Cert.entries cert) t_2203_c18 [.unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_19 :
    jumpsOkNode code (Cert.entries cert) t_230c_c19 [.unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_20 :
    jumpsOkNode code (Cert.entries cert) t_23c7_c20 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_21 :
    jumpsOkNode code (Cert.entries cert) t_23e2_c21 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_22 :
    jumpsOkNode code (Cert.entries cert) t_2492_c22 [.unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_23 :
    jumpsOkNode code (Cert.entries cert) t_285c_c23 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_24 :
    jumpsOkNode code (Cert.entries cert) t_285f_c24 [.unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_25 :
    jumpsOkNode code (Cert.entries cert) t_2870_c25 [.unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_26 :
    jumpsOkNode code (Cert.entries cert) t_28c5_c26 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_27 :
    jumpsOkNode code (Cert.entries cert) t_298b_c27 [.unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_28 :
    jumpsOkNode code (Cert.entries cert) t_1af0_c28 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_29 :
    jumpsOkNode code (Cert.entries cert) t_1b0c_c29 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_30 :
    jumpsOkNode code (Cert.entries cert) t_1dd8_c30 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_31 :
    jumpsOkNode code (Cert.entries cert) t_1df5_c31 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_32 :
    jumpsOkNode code (Cert.entries cert) t_01b9_c32 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_33 :
    jumpsOkNode code (Cert.entries cert) t_18d8_c33 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_34 :
    jumpsOkNode code (Cert.entries cert) t_18de_c34 [.unk, (.const (Nat.toB256 0x257)), .unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_35 :
    jumpsOkNode code (Cert.entries cert) t_1ad4_c35 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_36 :
    jumpsOkNode code (Cert.entries cert) t_13e3_c36 [.unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_37 :
    jumpsOkNode code (Cert.entries cert) t_13f5_c37 [.unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_38 :
    jumpsOkNode code (Cert.entries cert) t_1892_c38 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_39 :
    jumpsOkNode code (Cert.entries cert) t_0283_c39 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_40 :
    jumpsOkNode code (Cert.entries cert) t_18cb_c40 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_41 :
    jumpsOkNode code (Cert.entries cert) t_1011_c41 [.unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_42 :
    jumpsOkNode code (Cert.entries cert) t_13cb_c42 [.unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_43 :
    jumpsOkNode code (Cert.entries cert) t_13dd_c43 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_44 :
    jumpsOkNode code (Cert.entries cert) t_0f26_c44 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_45 :
    jumpsOkNode code (Cert.entries cert) t_0f2c_c45 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_46 :
    jumpsOkNode code (Cert.entries cert) t_1005_c46 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_47 :
    jumpsOkNode code (Cert.entries cert) t_100b_c47 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_48 :
    jumpsOkNode code (Cert.entries cert) t_0e1e_c48 [.unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_49 :
    jumpsOkNode code (Cert.entries cert) t_0efd_c49 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_50 :
    jumpsOkNode code (Cert.entries cert) t_0f21_c50 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_51 :
    jumpsOkNode code (Cert.entries cert) t_0de5_c51 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_52 :
    jumpsOkNode code (Cert.entries cert) t_0dfc_c52 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_53 :
    jumpsOkNode code (Cert.entries cert) t_0e18_c53 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_54 :
    jumpsOkNode code (Cert.entries cert) t_0683_c54 [.unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_55 :
    jumpsOkNode code (Cert.entries cert) t_0d57_c55 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_56 :
    jumpsOkNode code (Cert.entries cert) t_0d90_c56 [.ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_57 :
    jumpsOkNode code (Cert.entries cert) t_1fdb_c57 [.unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_58 :
    jumpsOkNode code (Cert.entries cert) t_21e8_c58 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_59 :
    jumpsOkNode code (Cert.entries cert) t_226e_c59 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_60 :
    jumpsOkNode code (Cert.entries cert) t_22e0_c60 [.unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_61 :
    jumpsOkNode code (Cert.entries cert) t_260b_c61 [.unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_62 :
    jumpsOkNode code (Cert.entries cert) t_28ca_c62 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_63 :
    jumpsOkNode code (Cert.entries cert) t_2992_c63 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_64 :
    jumpsOkNode code (Cert.entries cert) t_259c_c64 [.unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_65 :
    jumpsOkNode code (Cert.entries cert) t_2a57_c65 [.unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_66 :
    jumpsOkNode code (Cert.entries cert) t_2a7b_c66 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_67 :
    jumpsOkNode code (Cert.entries cert) t_19ee_c67 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, (.const (Nat.toB256 0x1a26)), .unk, .unk, (.const (Nat.toB256 0x1aca)), .unk, .unk, .unk, (.const (Nat.toB256 0x257)), .unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_68 :
    jumpsOkNode code (Cert.entries cert) t_26ec_c68 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_69 :
    jumpsOkNode code (Cert.entries cert) t_2878_c69 [.unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_70 :
    jumpsOkNode code (Cert.entries cert) t_297a_c70 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_71 :
    jumpsOkNode code (Cert.entries cert) t_20a4_c71 [.unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_72 :
    jumpsOkNode code (Cert.entries cert) t_2abc_c72 [.unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_73 :
    jumpsOkNode code (Cert.entries cert) t_0257_c73 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_74 :
    jumpsOkNode code (Cert.entries cert) t_288d_c74 [.unk, .unk, .unk, .ret] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_75 :
    jumpsOkNode code (Cert.entries cert) t_05da_c75 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_76 :
    jumpsOkNode code (Cert.entries cert) t_05e2_c76 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_77 :
    jumpsOkNode code (Cert.entries cert) t_0640_c77 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_78 :
    jumpsOkNode code (Cert.entries cert) t_067b_c78 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_79 :
    jumpsOkNode code (Cert.entries cert) t_0597_c79 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_80 :
    jumpsOkNode code (Cert.entries cert) t_059f_c80 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_81 :
    jumpsOkNode code (Cert.entries cert) t_05d2_c81 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_82 :
    jumpsOkNode code (Cert.entries cert) t_04d7_c82 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_83 :
    jumpsOkNode code (Cert.entries cert) t_050a_c83 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_84 :
    jumpsOkNode code (Cert.entries cert) t_0556_c84 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_85 :
    jumpsOkNode code (Cert.entries cert) t_055e_c85 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_86 :
    jumpsOkNode code (Cert.entries cert) t_0469_c86 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_87 :
    jumpsOkNode code (Cert.entries cert) t_049c_c87 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_88 :
    jumpsOkNode code (Cert.entries cert) t_04cf_c88 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_89 :
    jumpsOkNode code (Cert.entries cert) t_0416_c89 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_90 :
    jumpsOkNode code (Cert.entries cert) t_041e_c90 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_91 :
    jumpsOkNode code (Cert.entries cert) t_0459_c91 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_92 :
    jumpsOkNode code (Cert.entries cert) t_0461_c92 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_93 :
    jumpsOkNode code (Cert.entries cert) t_03ad_c93 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_94 :
    jumpsOkNode code (Cert.entries cert) t_03f0_c94 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_95 :
    jumpsOkNode code (Cert.entries cert) t_03f8_c95 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_96 :
    jumpsOkNode code (Cert.entries cert) t_0315_c96 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_97 :
    jumpsOkNode code (Cert.entries cert) t_0362_c97 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_98 :
    jumpsOkNode code (Cert.entries cert) t_0393_c98 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_99 :
    jumpsOkNode code (Cert.entries cert) t_01be_c99 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_100 :
    jumpsOkNode code (Cert.entries cert) t_0259_c100 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_101 :
    jumpsOkNode code (Cert.entries cert) t_02d6_c101 [.unk] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_ok : Cert.jumpsOk code cert = true := by
  unfold Cert.jumpsOk
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact jumps_0
  · exact jumps_1
  · exact jumps_2
  · exact jumps_3
  · exact jumps_4
  · exact jumps_5
  · exact jumps_6
  · exact jumps_7
  · exact jumps_8
  · exact jumps_9
  · exact jumps_10
  · exact jumps_11
  · exact jumps_12
  · exact jumps_13
  · exact jumps_14
  · exact jumps_15
  · exact jumps_16
  · exact jumps_17
  · exact jumps_18
  · exact jumps_19
  · exact jumps_20
  · exact jumps_21
  · exact jumps_22
  · exact jumps_23
  · exact jumps_24
  · exact jumps_25
  · exact jumps_26
  · exact jumps_27
  · exact jumps_28
  · exact jumps_29
  · exact jumps_30
  · exact jumps_31
  · exact jumps_32
  · exact jumps_33
  · exact jumps_34
  · exact jumps_35
  · exact jumps_36
  · exact jumps_37
  · exact jumps_38
  · exact jumps_39
  · exact jumps_40
  · exact jumps_41
  · exact jumps_42
  · exact jumps_43
  · exact jumps_44
  · exact jumps_45
  · exact jumps_46
  · exact jumps_47
  · exact jumps_48
  · exact jumps_49
  · exact jumps_50
  · exact jumps_51
  · exact jumps_52
  · exact jumps_53
  · exact jumps_54
  · exact jumps_55
  · exact jumps_56
  · exact jumps_57
  · exact jumps_58
  · exact jumps_59
  · exact jumps_60
  · exact jumps_61
  · exact jumps_62
  · exact jumps_63
  · exact jumps_64
  · exact jumps_65
  · exact jumps_66
  · exact jumps_67
  · exact jumps_68
  · exact jumps_69
  · exact jumps_70
  · exact jumps_71
  · exact jumps_72
  · exact jumps_73
  · exact jumps_74
  · exact jumps_75
  · exact jumps_76
  · exact jumps_77
  · exact jumps_78
  · exact jumps_79
  · exact jumps_80
  · exact jumps_81
  · exact jumps_82
  · exact jumps_83
  · exact jumps_84
  · exact jumps_85
  · exact jumps_86
  · exact jumps_87
  · exact jumps_88
  · exact jumps_89
  · exact jumps_90
  · exact jumps_91
  · exact jumps_92
  · exact jumps_93
  · exact jumps_94
  · exact jumps_95
  · exact jumps_96
  · exact jumps_97
  · exact jumps_98
  · exact jumps_99
  · exact jumps_100
  · exact jumps_101

end Blanc.Lift.UniswapV2Pair
