import Blanc.Lift.Check
import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Creation.Input

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Creation.Check.cert_check checks the preserved creation input. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Creation

open Jaune

-- Code: 17569 bytes, SHA-256: 890d2e9b028d3cdb1ca10cfe6e24f0c07c466f7b241eea9dfc825ae1313d945f
def code : ByteArray := Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Creation.creationCode

def t_0000_c0 : SFunc := (.next (.push [0x7a, 0x69] (by decide)) (.next (.push [0x0a] (by decide)) (.next (.reg .sstore) (.next (.push [0x44, 0x89] (by decide)) (.jump 1)))))
def t_4489_c1 : SFunc := (.dest (.next (.push [0x00, 0x0a] (by decide)) (.next (.push [0x44, 0x89] (by decide)) (.next (.reg .sub) (.next (.push [0x00, 0x0a] (by decide)) (.next (.push [0x00] (by decide)) (.next (.reg .codecopy) (.next (.push [0x00, 0x0a] (by decide)) (.next (.push [0x44, 0x89] (by decide)) (.next (.reg .sub) (.next (.push [0x00] (by decide)) (.last .return_))))))))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0),
  (⟨0x4489, [], 0⟩, t_4489_c1)
]

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Creation
