import Blanc.Lift.Check
import Blanc.Lift.VyperNonreentrantDeployed.Fixed.ReceiverR.Creation.Input

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; ReceiverR.Creation.Check.cert_check checks the synthetic receiver creation input. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed.ReceiverR.Creation

open Jaune

-- Code: 98 bytes, SHA-256: 9734878008a55b6d1cc416af0c7303e17814d61edaf9186db2c7be4ead332210
def code : ByteArray := Blanc.Lift.VyperNonreentrantDeployed.Fixed.ReceiverR.Creation.creationCode

def t_0000_c0 : SFunc := (.next (.push [0x59] (by decide)) (.next (.reg .returndatasize) (.next (.reg (.dup 1)) (.next (.push [0x09] (by decide)) (.next (.reg .returndatasize) (.next (.reg .codecopy) (.last .return_)))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.VyperNonreentrantDeployed.Fixed.ReceiverR.Creation
