import Blanc.Lift.WithdrawalRequest.Cert
import Blanc.Lift.CheckFast

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Each entry is decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.WithdrawalRequest

open Jaune

/-- Depth 9 covers all 504 runtime byte positions. -/
def codeTries : CodeTries code 9 :=
  CodeTries.ofCode code 9 (by decide +kernel) (by decide +kernel)

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_1 :
    checkNode code (Cert.entries cert) 0 0xdf [.unk, .unk, .unk] t_00df_c1 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_2 :
    checkNode code (Cert.entries cert) 0 0x1a0 [.unk] t_01a0_c2 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_3 :
    checkNode code (Cert.entries cert) 0 0x1cd [.unk, .unk] t_01cd_c3 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_4 :
    checkNode code (Cert.entries cert) 0 0x1e8 [.unk, .unk] t_01e8_c4 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_5 :
    checkNode code (Cert.entries cert) 0 0x4d [.unk, .unk, .unk, .unk, .unk] t_004d_c5 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem entry_6 :
    checkNode code (Cert.entries cert) 0 0xe1 [.unk, .unk, .unk, .unk] t_00e1_c6 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem cert_check : Cert.check code cert = true := by
  unfold Cert.check
  rw [Bool.and_eq_true]
  refine ⟨by decide +kernel, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl | rfl | rfl | rfl | rfl | rfl | rfl
  · exact entry_0
  · exact entry_1
  · exact entry_2
  · exact entry_3
  · exact entry_4
  · exact entry_5
  · exact entry_6

end Blanc.Lift.WithdrawalRequest
