#!/usr/bin/env python3
"""Canonical lift-certificate producer for deployed EVM bytecode (untrusted).

This is Blanc's one registered generator of `Blanc/Lift/**/Cert.lean` (and, where
registered, the matching per-entry `Check.lean`).  It recovers a certificate of
frame-relative control structure from raw runtime bytes; it proves nothing.  The
only trust boundary is Lean: `Cert.check code cert = true`, decided by the kernel
in the generated or hand-written `Check.lean`, is what a lift theorem consumes.

Provenance.  This file is the union of the historical producer forks kept as
Plans evidence (`solc-bytecode-v1/w3/lift.py`, `beacon-deposit-bytecode-v1/w0/lift.py`,
`vyper-3crv-bytecode-v1/v1/lift.py`) and the deployed Lido adaptation
(`deployed-lido-vyper-v1/certificate/generate.py`: PUSH0, TLOAD/TSTORE, SLT,
EXTCODESIZE, compatible-join repair, join-aware call continuations).  The two
exploration differences of the solc-w3 fork are options (`--no-join-entries`,
`--wrapper-order fall-first`), not code paths per contract.  `--fold` (registry
option `"fold": true`) folds ADD, MUL, SUB, LT, GT, EQ and ISZERO over constant
operands exactly as `foldConst` in `Blanc/Lift/Check.lean`; off by default, so
every certificate registered without it regenerates byte-identically.

Supported opcodes.  `LEAN_REG` maps each regular opcode the producer may emit to
its Lean `Ninst`; every row is checked, on each run, against the arms of
`ninstTransfer`/`liftRegularTransfer` (`Blanc/Lift/Transfer.lean`) and
`regularTransfer` (`Blanc/AbstractStackTransfer.lean`), including the arm's stack
shape.  An opcode without a lifted transfer is reported and the run fails; there
is no way to assume one.

Modes.
  lift:      --hex FILE --sha256 DIGEST --namespace NS --cert-out FILE [--check-out FILE] ...
  registry:  --registry scripts/lift/certificates.json (--verify | --write) [--only ID]
The registry mode regenerates every registered certificate from its committed
input and byte-compares (`--verify`, used by `scripts/check-lift-certificates.sh`)
or rewrites (`--write`) the committed Lean files.
"""

from pathlib import Path
import argparse
import hashlib
import json
import re
import subprocess
import sys
import tempfile
from typing import Dict, List, Optional, Set, Tuple, Any

sys.setrecursionlimit(50000)
MAX_NODES = 80000
MAX_ENTRIES = 8000

SCRIPT = Path(__file__).resolve()
DEFAULT_ROOT = SCRIPT.parents[2]
DEFAULT_HEADER = "GENERATED by scripts/lift/lift.py -- do not edit."
# The largest committed single-literal runtime is 6358 bytes; an 18320-byte literal
# exceeds the elaborator's recursion depth.
CODE_LITERAL_MAX = 8192
CODE_CHUNK = 4096

# EVM opcode table: (name, pops, pushes)
OPCODE_EFFECTS: Dict[int, Tuple[str, int, int]] = {
    0x00: ("STOP", 0, 0),
    0x01: ("ADD", 2, 1),
    0x02: ("MUL", 2, 1),
    0x03: ("SUB", 2, 1),
    0x04: ("DIV", 2, 1),
    0x05: ("SDIV", 2, 1),
    0x06: ("MOD", 2, 1),
    0x07: ("SMOD", 2, 1),
    0x08: ("ADDMOD", 3, 1),
    0x09: ("MULMOD", 3, 1),
    0x0a: ("EXP", 2, 1),
    0x0b: ("SIGNEXTEND", 2, 1),
    0x10: ("LT", 2, 1),
    0x11: ("GT", 2, 1),
    0x12: ("SLT", 2, 1),
    0x13: ("SGT", 2, 1),
    0x14: ("EQ", 2, 1),
    0x15: ("ISZERO", 1, 1),
    0x16: ("AND", 2, 1),
    0x17: ("OR", 2, 1),
    0x18: ("XOR", 2, 1),
    0x19: ("NOT", 1, 1),
    0x1a: ("BYTE", 2, 1),
    0x1b: ("SHL", 2, 1),
    0x1c: ("SHR", 2, 1),
    0x1d: ("SAR", 2, 1),
    0x20: ("KECCAK256", 2, 1),
    0x30: ("ADDRESS", 0, 1),
    0x31: ("BALANCE", 1, 1),
    0x32: ("ORIGIN", 0, 1),
    0x33: ("CALLER", 0, 1),
    0x34: ("CALLVALUE", 0, 1),
    0x35: ("CALLDATALOAD", 1, 1),
    0x36: ("CALLDATASIZE", 0, 1),
    0x37: ("CALLDATACOPY", 3, 0),
    0x38: ("CODESIZE", 0, 1),
    0x39: ("CODECOPY", 3, 0),
    0x3a: ("GASPRICE", 0, 1),
    0x3b: ("EXTCODESIZE", 1, 1),
    0x3c: ("EXTCODECOPY", 4, 0),
    0x3d: ("RETURNDATASIZE", 0, 1),
    0x3e: ("RETURNDATACOPY", 3, 0),
    0x3f: ("EXTCODEHASH", 1, 1),
    0x40: ("BLOCKHASH", 1, 1),
    0x41: ("COINBASE", 0, 1),
    0x42: ("TIMESTAMP", 0, 1),
    0x43: ("NUMBER", 0, 1),
    0x44: ("DIFFICULTY", 0, 1),
    0x45: ("GASLIMIT", 0, 1),
    0x46: ("CHAINID", 0, 1),
    0x47: ("SELFBALANCE", 0, 1),
    0x48: ("BASEFEE", 0, 1),
    0x50: ("POP", 1, 0),
    0x51: ("MLOAD", 1, 1),
    0x52: ("MSTORE", 2, 0),
    0x53: ("MSTORE8", 2, 0),
    0x54: ("SLOAD", 1, 1),
    0x55: ("SSTORE", 2, 0),
    0x56: ("JUMP", 1, 0),
    0x57: ("JUMPI", 2, 0),
    0x58: ("PC", 0, 1),
    0x59: ("MSIZE", 0, 1),
    0x5a: ("GAS", 0, 1),
    0x5b: ("JUMPDEST", 0, 0),
    0x5c: ("TLOAD", 1, 1),
    0x5d: ("TSTORE", 2, 0),
    0x5f: ("PUSH0", 0, 1),
    0xf0: ("CREATE", 3, 1),
    0xf1: ("CALL", 7, 1),
    0xf2: ("CALLCODE", 7, 1),
    0xf3: ("RETURN", 2, 0),
    0xf4: ("DELEGATECALL", 6, 1),
    0xf5: ("CREATE2", 4, 1),
    0xfa: ("STATICCALL", 6, 1),
    0xfd: ("REVERT", 2, 0),
    0xfe: ("INVALID", 0, 0),
    0xff: ("SELFDESTRUCT", 1, 0),
}
for _i in range(1, 33):
    OPCODE_EFFECTS[0x5f + _i] = (f"PUSH{_i}", 0, 1)
for _i in range(1, 17):
    OPCODE_EFFECTS[0x7f + _i] = (f"DUP{_i}", _i, _i + 1)
for _i in range(1, 17):
    OPCODE_EFFECTS[0x8f + _i] = (f"SWAP{_i}", _i + 1, _i + 1)
for _i in range(0, 5):
    OPCODE_EFFECTS[0xa0 + _i] = (f"LOG{_i}", _i + 2, 0)

# Regular (non-control, non-push/dup/swap) opcodes the producer may emit, with
# their Lean `Ninst`.  Each row must have a lifted transfer of the same stack
# shape (checked by `check_lean_transfers`).
LEAN_REG: Dict[int, str] = {
    0x01: ".reg .add", 0x02: ".reg .mul", 0x03: ".reg .sub", 0x04: ".reg .div",
    0x05: ".reg .sdiv", 0x06: ".reg .mod", 0x0a: ".reg .exp", 0x0b: ".reg .signextend",
    0x10: ".reg .lt", 0x11: ".reg .gt", 0x12: ".reg .slt", 0x13: ".reg .sgt",
    0x14: ".reg .eq", 0x15: ".reg .iszero", 0x16: ".reg .and", 0x17: ".reg .or",
    0x18: ".reg .xor", 0x19: ".reg .not", 0x1a: ".reg .byte", 0x1b: ".reg .shl",
    0x1c: ".reg .shr", 0x20: ".reg .keccak256", 0x30: ".reg .address",
    0x31: ".reg .balance", 0x32: ".reg .origin", 0x33: ".reg .caller",
    0x34: ".reg .callvalue", 0x35: ".reg .calldataload", 0x36: ".reg .calldatasize",
    0x37: ".reg .calldatacopy", 0x39: ".reg .codecopy", 0x3b: ".reg .extcodesize",
    0x3d: ".reg .returndatasize", 0x3e: ".reg .returndatacopy", 0x42: ".reg .timestamp",
    0x46: ".reg .chainid", 0x47: ".reg .selfbalance", 0x50: ".reg .pop",
    0x51: ".reg .mload", 0x52: ".reg .mstore", 0x53: ".reg .mstore8",
    0x54: ".reg .sload", 0x55: ".reg .sstore", 0x5a: ".reg .gas",
    0x5c: ".reg .tload", 0x5d: ".reg .tstore",
    0xa0: ".reg (.log 0)", 0xa1: ".reg (.log 1)", 0xa2: ".reg (.log 2)",
    0xa3: ".reg (.log 3)", 0xa4: ".reg (.log 4)",
    0xf1: ".exec .call", 0xfa: ".exec .staticcall",
}

# Opcodes the certificate grammar expresses directly: halts (`.last`), jumps
# (`.jump`/`.branch*`/`.callNext`/`.ret`), `.dest`, `.undefined`, pushes and the
# stack permutations (`regularTransfer`'s `.dup`/`.swap` arms).
STRUCTURAL_OPS: Set[int] = {
    0x00, 0xf3, 0xfd, 0xff, 0x56, 0x57, 0x5b, 0xfe,
    *range(0x5f, 0x80), *range(0x80, 0x90), *range(0x90, 0xa0),
}
BASE_SUPPORTED_OPS: Set[int] = STRUCTURAL_OPS | set(LEAN_REG)


def _def_arms(source: str, header: str, path: Path) -> List[Tuple[str, str]]:
    """The one-line `| .ctor[ arg], words => rhs` arms of the Lean def starting at `header`."""
    start = source.find(header)
    if start < 0 or source.count(header) != 1:
        raise SystemExit(f"lift: cannot locate `{header}` exactly once in {path}")
    body = source[start + len(header):].split("\n\n", 1)[0]
    arms = []
    for line in body.splitlines():
        m = re.match(r"^\s*\| (\.[\w .]+?), words =>\s*(.*)$", line)
        if m:
            arms.append((m.group(1).strip(), m.group(2).strip()))
    return arms


def _arm_shape(rhs: str, source: str) -> Optional[Tuple[int, int]]:
    """Stack shape (pops, pushes) of a transfer right-hand side, None if unrecognized."""
    fixed = {
        "binaryTransfer words": (2, 1),
        "unaryTransfer words": (1, 1),
        "some (none :: words)": (0, 1),
        "dropTwoTransfer words": (2, 0),
        "dropOneTransfer words": (1, 0),
    }
    if rhs in fixed:
        return fixed[rhs]
    m = re.fullmatch(r"dropTransfer (\d+) words", rhs)
    if m:
        return (int(m.group(1)), 0)
    m = re.fullmatch(r"(callTransfer|staticcallTransfer) words", rhs)
    if m:
        dm = re.search(rf"def {m.group(1)} : Pattern → Option Pattern\n\s*\| ((?:_ :: )+)words => some \(none :: words\)", source)
        if dm:
            return (dm.group(1).count("_ ::"), 1)
    return None


def check_lean_transfers(root: Path) -> None:
    """Fail unless every `LEAN_REG` row has a lifted Lean transfer of the producer's stack shape."""
    transfer_path = root / "Blanc/Lift/Transfer.lean"
    regular_path = root / "Blanc/AbstractStackTransfer.lean"
    transfer = transfer_path.read_text()
    regular = regular_path.read_text()
    ninst = dict(_def_arms(transfer, "def ninstTransfer : Ninst → Pattern → Option Pattern", transfer_path))
    lift = dict(_def_arms(transfer, "def liftRegularTransfer : Rinst → Pattern → Option Pattern", transfer_path))
    reg = dict(_def_arms(regular, "def regularTransfer : Rinst → Pattern → Option Pattern", regular_path))
    if ninst.get(".reg r") != "liftRegularTransfer r words":
        raise SystemExit("lift: ninstTransfer no longer routes `.reg r` through liftRegularTransfer")
    errors = []
    for op, lean in sorted(LEAN_REG.items()):
        name, pops, pushes = OPCODE_EFFECTS[op]
        if lean.startswith(".exec "):
            rhs = ninst.get(lean)
        else:
            ctor = lean[len(".reg "):]
            m = re.fullmatch(r"\(\.log (\d)\)", ctor)
            if m:
                arm = lift.get(".log n")
                rhs = None if arm != "dropTransfer (n.val + 2) words" else f"dropTransfer {int(m.group(1)) + 2} words"
            else:
                rhs = lift.get(ctor, reg.get(ctor))
        shape = _arm_shape(rhs, transfer + "\n" + regular) if rhs is not None else None
        if shape is None:
            errors.append(f"{name} (0x{op:02x}) `{lean}`: no lifted transfer arm")
        elif shape != (pops, pushes):
            errors.append(f"{name} (0x{op:02x}) `{lean}`: Lean shape {shape} != producer ({pops}, {pushes})")
    if errors:
        raise SystemExit("lift: producer opcode table disagrees with the Lean transfer set:\n  " + "\n  ".join(errors))


def run_registry(args: argparse.Namespace) -> int:
    """Regenerate every registered certificate and compare with (or write) the committed files."""
    root = args.blanc_root
    registry_path = args.registry
    registry = json.loads(registry_path.read_text())
    rows = registry["certificates"]
    if args.only:
        rows = [r for r in rows if r["id"] in args.only]
        if len(rows) != len(set(args.only)):
            print(f"lift: unknown --only id among {args.only}", file=sys.stderr)
            return 2
    failures = 0
    with tempfile.TemporaryDirectory(prefix="lift-registry-") as tmp:
        for row in rows:
            ident = row["id"]
            hex_file = root / row["input"]["hex"]
            file_sha = hashlib.sha256(hex_file.read_bytes()).hexdigest()
            if file_sha != row["input"]["file_sha256"]:
                print(f"FAIL {ident}: input {row['input']['hex']} file sha256 {file_sha} != registered {row['input']['file_sha256']}")
                failures += 1
                continue
            out = Path(tmp) / ident
            out.mkdir()
            argv = [sys.executable, str(SCRIPT), "--blanc-root", str(root),
                    "--hex", str(hex_file), "--sha256", row["input"]["runtime_sha256"],
                    "--namespace", row["namespace"], "--cert-out", str(out / "Cert.lean")]
            opts = row.get("options", {})
            if opts.get("join_entries") is False:
                argv.append("--no-join-entries")
            if "wrapper_order" in opts:
                argv += ["--wrapper-order", opts["wrapper_order"]]
            if opts.get("fold") is True:
                argv.append("--fold")
            if "header" in row:
                argv += ["--header", row["header"]]
            check = row.get("check")
            if check:
                argv += ["--check-out", str(out / "Check.lean"), "--check-header", check["header"],
                         "--check-split-nodes", str(check.get("split_nodes", 0))]
            proc = subprocess.run(argv, capture_output=True, text=True, timeout=args.timeout)
            if proc.returncode != 0:
                print(f"FAIL {ident}: producer exit {proc.returncode}\n{proc.stdout}{proc.stderr}")
                failures += 1
                continue
            summary = next((l for l in proc.stdout.splitlines() if l.startswith("Counts:")), "")
            pairs = [(out / "Cert.lean", root / row["cert"])]
            if check:
                pairs.append((out / "Check.lean", root / check["path"]))
            for produced, committed in pairs:
                rel = committed.relative_to(root)
                if args.write:
                    committed.parent.mkdir(parents=True, exist_ok=True)
                    committed.write_bytes(produced.read_bytes())
                    print(f"WROTE {ident}: {rel}")
                elif not committed.exists():
                    print(f"FAIL {ident}: {rel} is missing")
                    failures += 1
                elif produced.read_bytes() != committed.read_bytes():
                    a, b = produced.read_bytes(), committed.read_bytes()
                    first = next((i for i in range(min(len(a), len(b))) if a[i] != b[i]), min(len(a), len(b)))
                    line = a[:first].count(b"\n") + 1
                    print(f"FAIL {ident}: {rel} differs from its regeneration (first difference at byte {first}, line {line}; sizes {len(b)} committed vs {len(a)} regenerated)")
                    failures += 1
                else:
                    print(f"ok   {ident}: {rel} byte-identical ({committed.stat().st_size} bytes) {summary}")
    total = len(rows)
    if failures:
        print(f"check-lift-certificates: FAIL ({failures} failure(s) over {total} registered certificate(s))")
        return 1
    verb = "written" if args.write else "regenerated byte-identically"
    print(f"check-lift-certificates: PASS ({total} registered certificate(s) {verb})")
    return 0


parser = argparse.ArgumentParser(description="Canonical lift-certificate producer (untrusted)")
parser.add_argument("--blanc-root", type=Path, default=DEFAULT_ROOT, help="Blanc checkout whose Lean transfer set is read")
parser.add_argument("--registry", type=Path, default=None, help="certificate registry (registry mode)")
mode = parser.add_mutually_exclusive_group()
mode.add_argument("--verify", action="store_true", help="registry mode: byte-compare regenerations with committed files")
mode.add_argument("--write", action="store_true", help="registry mode: rewrite committed files from their regeneration")
parser.add_argument("--only", action="append", default=None, help="registry mode: restrict to this id (repeatable)")
parser.add_argument("--timeout", type=int, default=600, help="registry mode: per-certificate producer timeout (s)")
parser.add_argument("--hex", type=Path, default=None, help="runtime bytecode as hex text")
parser.add_argument("--sha256", type=str, default=None, help="expected SHA-256 of the runtime bytes")
parser.add_argument("--namespace", type=str, default=None, help="Lean namespace of the certificate")
parser.add_argument("--cert-out", type=Path, default=None, help="Cert.lean to write")
parser.add_argument("--check-out", type=Path, default=None, help="per-entry Check.lean to write (optional)")
parser.add_argument("--header", type=str, default=DEFAULT_HEADER, help="Cert.lean generator comment")
parser.add_argument("--check-header", type=str, default=DEFAULT_HEADER, help="Check.lean generator comment")
parser.add_argument("--check-split-nodes", type=int, default=0,
                    help="Check.lean: decide an entry above this many nodes block by block (0: never)")
parser.add_argument("--no-join-entries", action="store_true",
                    help="do not promote multi-predecessor JUMPDESTs to join entries (solc-w3 exploration)")
parser.add_argument("--wrapper-order", choices=("taken-first", "fall-first"), default="taken-first",
                    help="build order of a dispatcher selector branch (fall-first: solc-w3 exploration)")
parser.add_argument("--fold", action="store_true",
                    help="fold ADD/MUL/SUB/LT/GT/EQ/ISZERO over constant operands (mirror of foldConst)")
parser.add_argument("--report-dir", type=Path, default=None, help="also write cert.json/cfg.json diagnostics here")

args = parser.parse_args()

check_lean_transfers(args.blanc_root)

if args.registry is not None:
    if not (args.verify or args.write):
        parser.error("registry mode needs --verify or --write")
    sys.exit(run_registry(args))

if args.hex is None or args.sha256 is None or args.namespace is None or args.cert_out is None:
    parser.error("lift mode needs --hex, --sha256, --namespace and --cert-out")

# 1. Load bytecode
code_hex = args.hex.read_text().strip()
if code_hex.startswith("0x"):
    code_hex = code_hex[2:]
code = bytes.fromhex(code_hex)
actual_sha256 = hashlib.sha256(code).hexdigest()
if actual_sha256 != args.sha256.lower():
    print(f"Error: runtime SHA-256 mismatch: {actual_sha256} != {args.sha256}", file=sys.stderr)
    sys.exit(1)

out_dir = args.report_dir
if out_dir is not None:
    out_dir.mkdir(parents=True, exist_ok=True)

# 2. Instruction decoding
inst_map: Dict[int, Tuple[int, int, bytes]] = {}
pc = 0
while pc < len(code):
    cur_pc = pc
    op = code[pc]
    if 0x5f <= op <= 0x7f:
        size = op - 0x5f
        data = code[pc + 1 : pc + 1 + size]
        pc += 1 + size
        inst_map[cur_pc] = (op, 1 + size, data)
    else:
        pc += 1
        inst_map[cur_pc] = (op, 1, b"")

jumpdests = {p for p in inst_map if inst_map[p][0] == 0x5b}

trailer_len = 0
trailer_start = len(code)
if len(code) >= 2:
    potential_cbor_len = int.from_bytes(code[-2:], "big")
    if potential_cbor_len < len(code) - 2:
        trailer_len = potential_cbor_len + 2
        trailer_start = len(code) - trailer_len

# Track encountered unsupported opcodes
encountered_unsupported: Dict[int, List[int]] = {} # op -> list of pcs

# Track loops (back-edges) and external calls
back_edges: List[Dict[str, Any]] = []
external_calls: List[Dict[str, Any]] = []

# 3. Abstract state transfer (mirror of absNinst)
W256 = 1 << 256
# foldConst's binary ops; x = top of stack, y = second (Jaune's applyBinary order)
FOLD2 = {
    0x01: lambda x, y: x + y,               # ADD
    0x02: lambda x, y: x * y,               # MUL
    0x03: lambda x, y: x - y,               # SUB
    0x10: lambda x, y: 1 if x < y else 0,   # LT
    0x11: lambda x, y: 1 if x > y else 0,   # GT
    0x14: lambda x, y: 1 if x == y else 0,  # EQ
}
def step_inst(op: int, data: bytes, stack: List[Tuple[Any, ...]], cur_pc: Optional[int] = None) -> Optional[List[Tuple[Any, ...]]]:
    # Check if opcode is supported in the checker model
    if op not in BASE_SUPPORTED_OPS:
        if cur_pc is not None:
            encountered_unsupported.setdefault(op, []).append(cur_pc)
        return None

    st = list(stack)
    if 0x5f <= op <= 0x7f:
        val = int.from_bytes(data, 'big')
        st.insert(0, ('const', val))
        return st
    elif 0x80 <= op <= 0x8f: # DUPn
        idx = op - 0x80
        if idx >= len(st): return None
        st.insert(0, st[idx])
        return st
    elif 0x90 <= op <= 0x9f: # SWAPn
        idx = op - 0x8f
        if idx >= len(st): return None
        st[0], st[idx] = st[idx], st[0]
        return st
    elif op == 0x50: # POP
        if not st: return None
        st.pop(0)
        return st
    elif op in (0x01, 0x02, 0x03, 0x04, 0x0a, 0x10, 0x11, 0x14, 0x16, 0x1c, 0x20): # 2 -> 1
        if len(st) < 2: return None
        x, y = st.pop(0), st.pop(0)
        if args.fold and op in FOLD2 and x[0] == 'const' and y[0] == 'const':
            st.insert(0, ('const', FOLD2[op](x[1], y[1]) % W256))
        else:
            st.insert(0, ('unk',))
        return st
    elif op in (0x15, 0x19, 0x31, 0x35, 0x51, 0x54): # 1 -> 1
        if len(st) < 1: return None
        x = st.pop(0)
        if args.fold and op == 0x15 and x[0] == 'const':
            st.insert(0, ('const', 1 if x[1] == 0 else 0))
        else:
            st.insert(0, ('unk',))
        return st
    elif op in (0x30, 0x32, 0x33, 0x34, 0x36, 0x42, 0x5a): # 0 -> 1
        st.insert(0, ('unk',))
        return st
    elif op in (0x52, 0x55): # 2 -> 0
        if len(st) < 2: return None
        st.pop(0); st.pop(0)
        return st
    elif op in (0xa0, 0xa1, 0xa2, 0xa3, 0xa4): # LOGn: n + 2 -> 0
        n = op - 0xa0
        if len(st) < n + 2: return None
        for _ in range(n + 2): st.pop(0)
        return st
    elif op == 0xf1: # CALL: 7 -> 1
        if len(st) < 7: return None
        for _ in range(7): st.pop(0)
        st.insert(0, ('unk',))
        return st
    elif op in BASE_SUPPORTED_OPS:  # natural effect for every other supported op
        name, pops, pushes = OPCODE_EFFECTS[op]
        if len(st) < pops: return None
        for _ in range(pops): st.pop(0)
        for _ in range(pushes): st.insert(0, ('unk',))
        return st
    else:
        return None

def goto_compat(caller_frame: List[Tuple[Any, ...]], entry_frame: Tuple[Tuple[Any, ...], ...]) -> bool:
    if len(caller_frame) != len(entry_frame):
        return False
    for a, e in zip(caller_frame, entry_frame):
        if e[0] == 'unk':
            continue
        elif e[0] == 'const':
            if a[0] != 'const' or a[1] != e[1]:
                return False
        elif e[0] == 'ret':
            if a[0] != 'ret':
                return False
        else:
            return False
    return True

def call_compat(t: int, caller_frame: List[Tuple[Any, ...]], callee_frame: Tuple[Tuple[Any, ...], ...]) -> bool:
    if len(caller_frame) < len(callee_frame):
        return False
    for a, e in zip(caller_frame, callee_frame):
        if e[0] == 'unk':
            continue
        elif e[0] == 'const':
            if a[0] != 'const' or a[1] != e[1]:
                return False
        elif e[0] == 'ret':
            if a[0] != 'const' or a[1] != t:
                return False
        else:
            return False
    return True

# 4. Callee analysis (solc convention)
callee_memo: Dict[Tuple[int, Tuple[Tuple[Any, ...], ...]], Tuple[bool, Optional[int]]] = {}

explore_budget = [400000]

def check_callee(t: int, callee_frame: Tuple[Tuple[Any, ...], ...]) -> Tuple[bool, Optional[int]]:
    key = (t, callee_frame)
    if key in callee_memo:
        return callee_memo[key]
    
    returns = set()
    failed = False
    
    def explore(cur_pc: int, cur_st: List[Tuple[Any, ...]], path: Set[Tuple[int, Tuple[Tuple[Any, ...], ...]]]):
        nonlocal failed
        if failed: return
        state_key = (cur_pc, tuple(cur_st))
        if state_key in seen:
            return
        seen.add(state_key)
        explore_budget[0] -= 1
        if explore_budget[0] < 0:
            raise RuntimeError("callee exploration budget exhausted")
        new_path = path | {state_key}
        
        while True:
            if cur_pc not in inst_map:
                failed = True
                return
            op, sz, d = inst_map[cur_pc]
            if op == 0x5b: # JUMPDEST
                cur_pc += 1
            elif op == 0x57: # JUMPI
                if len(cur_st) < 2:
                    failed = True
                    return
                tgt = cur_st[0]
                rem = cur_st[2:]
                explore(cur_pc + 1, rem, new_path)
                if tgt[0] == 'const':
                    if not any(p == tgt[1] for (p, _) in new_path):
                        explore(tgt[1], rem, new_path)
                else:
                    failed = True
                return
            elif op == 0x56: # JUMP
                if len(cur_st) < 1:
                    failed = True
                    return
                tgt = cur_st[0]
                rem = cur_st[1:]
                if tgt[0] == 'ret':
                    returns.add(len(rem))
                    return
                elif tgt[0] == 'const':
                    if any(p == tgt[1] for (p, _) in new_path):
                        return # Loop back-edge encountered in callee, cycle terminates
                    sub_call = None
                    for i, v in enumerate(rem):
                        if v[0] == 'const' and v[1] in jumpdests:
                            sub_cf = (('unk',),) * i + (('ret',),)
                            is_c, sub_rets = check_callee(tgt[1], sub_cf)
                            if is_c:
                                sub_call = (i, sub_rets)
                            break
                    if sub_call is not None:
                        i, sub_rets = sub_call
                        ret_pc = rem[i][1]
                        cont_st = [('unk',)] * sub_rets + list(rem[i+1:])
                        explore(ret_pc, cont_st, new_path)
                        return
                    else:
                        explore(tgt[1], rem, new_path)
                        return
                else:
                    failed = True
                    return
            elif op in (0x00, 0xf3, 0xfd, 0xfe, 0xff):
                return
            else:
                nxt = step_inst(op, d, cur_st, cur_pc)
                if nxt is None:
                    failed = True
                    return
                cur_st = nxt
                cur_pc += sz

    seen: Set[Tuple[int, Tuple[Tuple[Any, ...], ...]]] = set()
    try:
        explore(t, list(callee_frame), set())
    except (RecursionError, RuntimeError):
        failed = True
    if not failed and len(returns) == 1:
        res = (True, list(returns)[0])
    else:
        res = (False, None)
    callee_memo[key] = res
    return res

# 4. Selector wrappers detection: `DUP1; PUSH4 sel; EQ; PUSH2 tgt; JUMPI` in the dispatcher.
WRAPPERS: Set[int] = set()
SELECTOR_MAP: Dict[int, int] = {} # selector_int -> wrapper_pc
_pcs = sorted(inst_map)
for _i in range(len(_pcs) - 4):
    _a, _b, _c, _d, _e = (_pcs[_i + j] for j in range(5))
    if (inst_map[_a][0] == 0x80 and inst_map[_b][0] == 0x63 and inst_map[_c][0] == 0x14
            and (0x60 <= inst_map[_d][0] <= 0x62) and inst_map[_e][0] == 0x57):
        sel = int.from_bytes(inst_map[_b][2], "big")
        tgt_pc = int.from_bytes(inst_map[_d][2], "big")
        WRAPPERS.add(tgt_pc)
        SELECTOR_MAP[sel] = tgt_pc

deferred_wrappers: List[Tuple[int, Tuple[Tuple[Any, ...], ...], int, Any]] = []

def generalize_frame(frame: List[Tuple[Any, ...]]) -> Tuple[Tuple[Any, ...], ...]:
    gen = []
    for v in frame:
        if v[0] == 'const' and v[1] in jumpdests:
            gen.append(v)
        elif v[0] == 'ret':
            gen.append(v)
        else:
            gen.append(('unk',))
    return tuple(gen)

# Pointwise generalization for join entries
def pointwise_generalization(frames: List[List[Tuple[Any, ...]]]) -> Tuple[Optional[Tuple[Tuple[Any, ...], ...]], Optional[str]]:
    if not frames:
        return None, "No incoming frames"
    lengths = [len(f) for f in frames]
    if len(set(lengths)) > 1:
        return None, f"Frame lengths disagree: {lengths}"
    flen = lengths[0]
    gen = []
    for i in range(flen):
        vals = [f[i] for f in frames]
        ret_count = sum(1 for v in vals if v[0] == 'ret')
        if ret_count > 0:
            if ret_count != len(vals):
                return None, f"Return positions disagree at index {i}"
            gen.append(('ret',))
        elif all(v == vals[0] for v in vals):
            if vals[0][0] == 'const' and vals[0][1] not in jumpdests:
                gen.append(('unk',))
            else:
                gen.append(vals[0])
        else:
            gen.append(('unk',))
    return tuple(gen), None

# 5. Tree construction state & entries
entries: List[Tuple[int, Tuple[Tuple[Any, ...], ...], int]] = []
entry_map: Dict[Tuple[int, Tuple[Tuple[Any, ...], ...], int], int] = {}
entry_roles: Dict[int, str] = {}
call_sites: List[Tuple[int, int, int]] = []
return_sites: List[Tuple[int, int, int]] = []
rejections: List[str] = []

def get_or_create_entry(epc: int, eframe: Tuple[Tuple[Any, ...], ...], erets: int, role: str = "goto") -> int:
    key = (epc, tuple(eframe), erets)
    if key in entry_map:
        return entry_map[key]
    idx = len(entries)
    if idx >= MAX_ENTRIES:
        raise RuntimeError(f"Entry cap {MAX_ENTRIES} exceeded")
    entries.append(key)
    entry_map[key] = idx
    entry_roles[idx] = role
    return idx

get_or_create_entry(0, (), 0, role="top")

# CFG Pre-Pass to detect loops and join points across functions
pre_incoming_edges: Dict[int, List[Tuple[int, str, List[Tuple[Any, ...]]]]] = {} # jd -> list of (src_pc, kind, stack)
pre_back_edges: Set[Tuple[int, int]] = set() # (src_pc, target_jd)
pre_func_rets: Dict[int, int] = {} # jd -> rets of enclosing function

func_queue: List[Tuple[int, int, Tuple[Tuple[Any, ...], ...]]] = [
    (0, 0, ())
]
for wpc in sorted(WRAPPERS):
    func_queue.append((wpc, 0, (('unk',),)))

discovered_funcs: Set[int] = {0} | WRAPPERS
explored_func_entries: Set[Tuple[int, Tuple[Tuple[Any, ...], ...]]] = set()

while func_queue:
    f_pc, f_rets, f_frame = func_queue.pop(0)
    f_key = (f_pc, tuple(f_frame))
    if f_key in explored_func_entries:
        continue
    explored_func_entries.add(f_key)
    
    visited_states: Set[Tuple[int, Tuple[Tuple[Any, ...], ...]]] = set()
    
    def explore_func(pc: int, st: List[Tuple[Any, ...]], path: Set[int]):
        state_key = (pc, tuple(st))
        if state_key in visited_states:
            return
        visited_states.add(state_key)
        
        while True:
            if pc not in inst_map:
                return
            path = path | {pc}
            op, sz, d = inst_map[pc]
            if op in (0x00, 0xf3, 0xfd, 0xff):
                return
            elif op == 0xfe:
                return
            elif op == 0x5b: # JUMPDEST
                pre_func_rets[pc] = f_rets
                pc += 1
            elif op == 0x56: # JUMP
                if not st: return
                tgt = st[0]
                rem = st[1:]
                if tgt[0] == 'ret':
                    return
                elif tgt[0] == 'const':
                    # Check callee
                    call_info = None
                    for i, v in enumerate(rem):
                        if v[0] == 'const' and v[1] in jumpdests:
                            sub_cf = (('unk',),) * i + (('ret',),)
                            is_c, sub_rets = check_callee(tgt[1], sub_cf)
                            if is_c:
                                call_info = (i, sub_cf, sub_rets)
                                break
                    if call_info is not None:
                        i, sub_cf, sub_rets = call_info
                        if tgt[1] not in discovered_funcs:
                            discovered_funcs.add(tgt[1])
                            func_queue.append((tgt[1], sub_rets, sub_cf))
                        cont_pc = rem[i][1]
                        cont_st = [('unk',)] * sub_rets + list(rem[i+1:])
                        explore_func(cont_pc, cont_st, path)
                        return
                    else:
                        target_pc = tgt[1]
                        if target_pc in jumpdests:
                            pre_incoming_edges.setdefault(target_pc, []).append((pc, 'jump', list(rem)))
                            if target_pc in path:
                                pre_back_edges.add((pc, target_pc))
                            else:
                                explore_func(target_pc, rem, path)
                        return
                else:
                    return
            elif op == 0x57: # JUMPI
                if len(st) < 2: return
                tgt = st[0]
                rem = st[2:]
                fall_pc = pc + 1
                if fall_pc in jumpdests:
                    pre_incoming_edges.setdefault(fall_pc, []).append((pc, 'fallthrough', list(rem)))
                explore_func(fall_pc, rem, path)
                if tgt[0] == 'const':
                    target_pc = tgt[1]
                    if target_pc in jumpdests:
                        pre_incoming_edges.setdefault(target_pc, []).append((pc, 'jumpi_taken', list(rem)))
                        if target_pc in path:
                            pre_back_edges.add((pc, target_pc))
                        else:
                            explore_func(target_pc, rem, path)
                return
            else:
                nxt = step_inst(op, d, st, pc)
                if nxt is None: return
                st = nxt
                nxt_pc = pc + sz
                if nxt_pc in jumpdests:
                    pre_incoming_edges.setdefault(nxt_pc, []).append((pc, 'fallthrough', list(st)))
                pc = nxt_pc

    explore_func(f_pc, list(f_frame), set())

loop_head_pcs = {tgt for src, tgt in pre_back_edges}
join_entries: Dict[int, int] = {} # jd_pc -> entry_idx
unmerged_joins: List[Dict[str, Any]] = []

for jd in sorted(pre_incoming_edges.keys()):
    if jd in loop_head_pcs:
        continue
    edges_list = pre_incoming_edges[jd]
    distinct_edges = {}
    for src_pc, kind, stk in edges_list:
        if (src_pc, jd) in pre_back_edges:
            continue
        edge_key = (src_pc, kind)
        if edge_key not in distinct_edges:
            distinct_edges[edge_key] = stk
    
    if len(distinct_edges) >= 2:
        frames = list(distinct_edges.values())
        gen_frame, err = pointwise_generalization(frames)
        if gen_frame is None:
            unmerged_joins.append({
                "pc": jd,
                "reason": err,
                "edges": sorted(list(distinct_edges.keys())),
                "frame_lengths": [len(f) for f in frames]
            })
        elif not args.no_join_entries:
            f_rets = pre_func_rets.get(jd, 0)
            k = get_or_create_entry(jd, gen_frame, f_rets, role="join")
            join_entries[jd] = k

node_count = 0

def build_tree(cur_pc: int, cur_st: List[Tuple[Any, ...]], cur_rets: int, path: Set[Tuple[int, Tuple[Tuple[Any, ...], ...]]], entry_idx: int) -> Any:
    global node_count
    node_count += 1
    if node_count > MAX_NODES:
        raise RuntimeError(f"Node count cap {MAX_NODES} exceeded")
    
    # If this PC is a registered join entry and we are entering from another entry (fallthrough), transition to it
    if (cur_pc in join_entries and entry_idx != join_entries[cur_pc]
        and cur_rets == entries[join_entries[cur_pc]][2]
        and goto_compat(cur_st, entries[join_entries[cur_pc]][1])):
        k = join_entries[cur_pc]
        return ('join_ref', k, cur_pc)

    state_key = (cur_pc, tuple(cur_st))
    if state_key in path:
        msg = f"LOOP REVISIT at 0x{cur_pc:04x} with stack {cur_st}"
        raise RuntimeError(msg)
    new_path = path | {state_key}
    
    if cur_pc not in inst_map:
        return ('undefined', cur_pc)
    
    op, sz, d = inst_map[cur_pc]
    if op in (0x00, 0xf3, 0xfd, 0xff):
        return ('last', op, cur_pc)
    elif op == 0xfe:
        return ('undefined', cur_pc)
    elif op == 0x5b: # JUMPDEST
        sub = build_tree(cur_pc + 1, cur_st, cur_rets, new_path, entry_idx)
        return ('dest', sub, cur_pc)
    elif op == 0x57: # JUMPI
        tgt = cur_st[0]
        rem = cur_st[2:]
        if tgt[0] == 'const':
            if any(p == tgt[1] for (p, _) in new_path) or ((cur_pc, tgt[1]) in pre_back_edges):
                k = get_or_create_entry(tgt[1], generalize_frame(rem), cur_rets, role="loop")
                back_edges.append({
                    "kind": "branchTo",
                    "pc": cur_pc,
                    "target_entry": k,
                    "target_pc": tgt[1],
                    "target_frame": generalize_frame(rem),
                    "caller_entry": entry_idx
                })
                fall = build_tree(cur_pc + 1, rem, cur_rets, new_path, entry_idx)
                return ('branchTo', fall, k, cur_pc)
            elif tgt[1] in join_entries:
                k = join_entries[tgt[1]]
                fall = build_tree(cur_pc + 1, rem, cur_rets, new_path, entry_idx)
                return ('branchTo', fall, k, cur_pc)
            elif entry_idx == 0 and tgt[1] in WRAPPERS:
                # Build order only decides entry numbering (solc-w3 built the fallthrough first).
                if args.wrapper_order == "fall-first":
                    fall = build_tree(cur_pc + 1, rem, cur_rets, new_path, entry_idx)
                taken = build_tree(tgt[1], rem, cur_rets, new_path, entry_idx)
                wrap_idx = len(deferred_wrappers)
                deferred_wrappers.append((tgt[1], generalize_frame(rem), cur_rets, taken))
                if args.wrapper_order == "taken-first":
                    fall = build_tree(cur_pc + 1, rem, cur_rets, new_path, entry_idx)
                return ('branchTo', fall, ('wrapper', wrap_idx), cur_pc)
        fall = build_tree(cur_pc + 1, rem, cur_rets, new_path, entry_idx)
        taken = build_tree(tgt[1], rem, cur_rets, new_path, entry_idx)
        return ('branch', fall, taken, cur_pc)
    elif op == 0x56: # JUMP
        tgt = cur_st[0]
        rem = cur_st[1:]
        if tgt[0] == 'ret':
            if len(rem) != cur_rets:
                raise RuntimeError(f"Return frame len {len(rem)} != rets {cur_rets} at 0x{cur_pc:04x}")
            return_sites.append((cur_pc, entry_idx, len(rem)))
            return ('ret', cur_pc)
        elif tgt[0] == 'const':
            is_back = any(p == tgt[1] for (p, _) in new_path) or ((cur_pc, tgt[1]) in pre_back_edges)
            call_info = None
            if not is_back:
                for i, v in enumerate(rem):
                    if v[0] == 'const' and v[1] in jumpdests:
                        sub_cf = (('unk',),) * i + (('ret',),)
                        is_c, sub_rets = check_callee(tgt[1], sub_cf)
                        if is_c:
                            call_info = (i, sub_cf, sub_rets)
                            break
            if call_info is not None:
                i, sub_cf, sub_rets = call_info
                k = get_or_create_entry(tgt[1], sub_cf, sub_rets, role="callee")
                ret_pc = rem[i][1]
                call_sites.append((cur_pc, k, ret_pc))
                cont_st = [('unk',)] * sub_rets + list(rem[i+1:])
                cont_tree = build_tree(ret_pc, cont_st, cur_rets, new_path, entry_idx)
                return ('callNext', k, cont_tree, cur_pc)
            elif is_back:
                g_frame = generalize_frame(rem)
                k = get_or_create_entry(tgt[1], g_frame, cur_rets, role="loop")
                back_edges.append({
                    "kind": "jump",
                    "pc": cur_pc,
                    "target_entry": k,
                    "target_pc": tgt[1],
                    "target_frame": g_frame,
                    "caller_entry": entry_idx
                })
                return ('jump', k, cur_pc)
            elif tgt[1] in join_entries:
                k = join_entries[tgt[1]]
                return ('jump', k, cur_pc)
            else:
                g_frame = generalize_frame(rem)
                k = get_or_create_entry(tgt[1], g_frame, cur_rets, role="goto")
                return ('jump', k, cur_pc)
        else:
            raise RuntimeError(f"Non-const/ret JUMP target {tgt} at 0x{cur_pc:04x}")
    else:
        # Record external calls (CALL, STATICCALL, DELEGATECALL, CALLCODE)
        if op in (0xf1, 0xf2, 0xf4, 0xfa):
            call_name = OPCODE_EFFECTS[op][0]
            target_desc = "unknown"
            if len(cur_st) >= 2 and cur_st[1][0] == 'const':
                addr = cur_st[1][1]
                if addr == 2:
                    target_desc = "0x02 (SHA-256 precompile)"
                else:
                    target_desc = f"0x{addr:x}"
            external_calls.append({
                "pc": cur_pc,
                "type": call_name,
                "target": target_desc,
                "entry_idx": entry_idx
            })

        nxt_st = step_inst(op, d, cur_st, cur_pc)
        if nxt_st is None:
            op_name = OPCODE_EFFECTS.get(op, ("UNKNOWN", 0, 0))[0]
            if op not in BASE_SUPPORTED_OPS:
                raise RuntimeError(f"Unsupported opcode {op_name} (0x{op:02x}) at 0x{cur_pc:04x}")
            else:
                raise RuntimeError(f"Stack underflow at 0x{cur_pc:04x} on {op_name} (stack depth {len(cur_st)})")
        sub = build_tree(cur_pc + sz, nxt_st, cur_rets, new_path, entry_idx)
        return ('next', (op, d), sub, cur_pc)

# Pre-scan reachable instructions to report all unsupported opcodes if any exist
def scan_unsupported() -> Dict[int, List[int]]:
    unsupported_found: Dict[int, List[int]] = {}
    visited = set()
    queue = [0]
    for wpc in WRAPPERS:
        queue.append(wpc)
    for jd in jumpdests:
        queue.append(jd)

    while queue:
        p = queue.pop(0)
        if p in visited or p not in inst_map:
            continue
        visited.add(p)
        op, sz, d = inst_map[p]
        if op not in BASE_SUPPORTED_OPS:
            unsupported_found.setdefault(op, []).append(p)
        if op in (0x00, 0xf3, 0xfd, 0xfe, 0xff):
            continue
        elif op == 0x56:
            continue
        elif op == 0x57:
            queue.append(p + 1)
        else:
            queue.append(p + sz)
    return unsupported_found

unsupported_in_scan = scan_unsupported()

# Unsupported opcodes anywhere in the linear code reachable from an entry or JUMPDEST
# are reported and fail the run: an opcode is supported only through a Lean transfer.
if unsupported_in_scan:
    print("=== Unsupported opcodes: no lifted Lean transfer (Blanc/Lift/Transfer.lean) ===", file=sys.stderr)
    for op in sorted(unsupported_in_scan.keys()):
        name, pops, pushes = OPCODE_EFFECTS.get(op, ("UNKNOWN", 0, 0))
        occurrences = len(unsupported_in_scan[op])
        pcs_str = ", ".join(f"0x{pc:04x}" for pc in unsupported_in_scan[op][:5])
        if occurrences > 5:
            pcs_str += f", ... ({occurrences} total)"
        print(f"  - {name} (0x{op:02x}): pops {pops}, pushes {pushes} [occurrences: {occurrences} at {pcs_str}]", file=sys.stderr)
    sys.exit(1)

# 6. Build entry trees
trees: Dict[int, Any] = {}
rejected_entries: List[Tuple[int, int, str]] = []

# Build Entry 0
try:
    trees[0] = build_tree(0, [], 0, set(), 0)
except Exception as e:
    msg = str(e)
    rejected_entries.append((0, 0, msg))
    rejections.append(f"Entry 0 (pc 0x0000): {msg}")

# Build all callee/goto entries discovered
idx = 1
while idx < len(entries):
    epc, ef, er = entries[idx]
    try:
        t = build_tree(epc, list(ef), er, set(), idx)
        trees[idx] = t
    except Exception as e:
        msg = str(e)
        rejected_entries.append((idx, epc, msg))
        rejections.append(f"Entry {idx} (pc 0x{epc:04x}): {msg}")
    idx += 1

# Append the wrapper entries and patch their branchTo placeholders.
wrapper_index: Dict[int, int] = {}
for wi, (wpc, wframe, wrets, wtree) in enumerate(deferred_wrappers):
    k = get_or_create_entry(wpc, wframe, wrets, role="wrapper")
    trees[k] = wtree
    wrapper_index[wi] = k

def _patch(t: Any) -> Any:
    kind = t[0]
    if kind == 'join_ref':
        return t
    if kind == 'branchTo' and isinstance(t[2], tuple):
        return ('branchTo', _patch(t[1]), wrapper_index[t[2][1]], t[3])
    if kind in ('next',):
        return (kind, t[1], _patch(t[2]), t[3])
    if kind == 'dest':
        return ('dest', _patch(t[1]), t[2])
    if kind == 'branch':
        return ('branch', _patch(t[1]), _patch(t[2]), t[3])
    if kind == 'branchTo':
        return ('branchTo', _patch(t[1]), t[2], t[3])
    if kind == 'callNext':
        return ('callNext', t[1], _patch(t[2]), t[3])
    return t

if 0 in trees:
    trees[0] = _patch(trees[0])

# A rejected entry has no tree; the certificate would not check, so the run fails.
if rejected_entries:
    for msg in rejections:
        print(f"Rejected: {msg}", file=sys.stderr)
    sys.exit(1)

# 7. Independent Python Mirror Checker
debug_entry = False

def check_node(code_bytes: bytes, es: List[Tuple[int, Tuple[Tuple[Any, ...], ...], int]], m: int, pc: int, a: List[Tuple[Any, ...]], tree: Any) -> bool:
    kind = tree[0]
    def fail(reason: str) -> bool:
        if debug_entry:
            print(f"CHECK FAIL at pc 0x{pc:04x}, kind {kind}: {reason}", file=sys.stderr)
        return False

    if kind == 'join_ref':
        k = tree[1]
        if k >= len(es): return fail(f"join_ref k >= len(es): {k} >= {len(es)}")
        e_pc, e_frame, e_rets = es[k]
        if pc >= len(code_bytes) or pc != e_pc: return fail(f"join_ref pc mismatch: pc 0x{pc:04x} != e_pc 0x{e_pc:04x}")
        if e_rets != m: return fail(f"join_ref rets mismatch: {e_rets} != {m} at 0x{pc:04x}")
        if not goto_compat(a, e_frame): return fail(f"join_ref goto_compat: a={a} != e_frame={e_frame} at 0x{pc:04x}")
        res = check_node(code_bytes, es, m, pc, a, trees[k])
        if not res:
            return fail(f"join_ref check_node(trees[{k}]) failed at 0x{pc:04x}")
        return True
    elif kind == 'next':
        op, d = tree[1]
        sz = 1 + len(d)
        if pc >= len(code_bytes) or code_bytes[pc] != op: return fail(f"next opcode mismatch: code[{pc}] != {hex(op)}")
        if d and code_bytes[pc+1 : pc+sz] != d: return fail("next data mismatch")
        nxt_a = step_inst(op, d, a, pc)
        if nxt_a is None: return fail(f"next step_inst returned None for {hex(op)}")
        return check_node(code_bytes, es, m, pc + sz, nxt_a, tree[2])
    elif kind == 'last':
        if not (pc < len(code_bytes) and code_bytes[pc] == tree[1]):
            return fail(f"last opcode mismatch at {pc}: code={code_bytes[pc] if pc < len(code_bytes) else None} != {hex(tree[1])}")
        return True
    elif kind == 'dest':
        if pc >= len(code_bytes) or code_bytes[pc] != 0x5b: return fail("dest not 0x5b")
        return check_node(code_bytes, es, m, pc + 1, a, tree[1])
    elif kind == 'branch':
        fall, taken = tree[1], tree[2]
        if len(a) < 2: return fail("branch stack < 2")
        tgt, rem = a[0], a[2:]
        if tgt[0] != 'const': return fail("branch target not const")
        if pc >= len(code_bytes) or code_bytes[pc] != 0x57: return fail("branch not 0x57")
        return check_node(code_bytes, es, m, pc + 1, rem, fall) and check_node(code_bytes, es, m, tgt[1], rem, taken)
    elif kind == 'branchTo':
        fall, k = tree[1], tree[2]
        if len(a) < 2: return fail(f"branchTo stack < 2: {a}")
        tgt, rem = a[0], a[2:]
        if tgt[0] != 'const': return fail("branchTo target not const")
        if k >= len(es): return fail("branchTo k >= len(es)")
        e_pc, e_frame, e_rets = es[k]
        if pc >= len(code_bytes) or code_bytes[pc] != 0x57: return fail("branchTo not 0x57")
        if e_pc != tgt[1] or e_rets != m: return fail(f"branchTo epc {hex(e_pc)} != tgt {hex(tgt[1])} or erets {e_rets} != m {m}")
        if not goto_compat(rem, e_frame): return fail(f"branchTo goto_compat failed: rem={rem} != e_frame={e_frame}")
        return check_node(code_bytes, es, m, pc + 1, rem, fall)
    elif kind == 'jump':
        k = tree[1]
        if len(a) < 1: return fail("jump stack < 1")
        tgt, rem = a[0], a[1:]
        if tgt[0] != 'const': return fail("jump target not const")
        if k >= len(es): return fail("jump k >= len(es)")
        e_pc, e_frame, e_rets = es[k]
        if pc >= len(code_bytes) or code_bytes[pc] != 0x56: return fail("jump not 0x56")
        if e_pc != tgt[1]: return fail(f"jump epc {hex(e_pc)} != tgt {hex(tgt[1])}")
        if e_rets != m: return fail(f"jump erets {e_rets} != m {m}")
        if not goto_compat(rem, e_frame): return fail(f"jump goto_compat failed: rem={rem} != e_frame={e_frame}")
        return True
    elif kind == 'callNext':
        k, f = tree[1], tree[2]
        if len(a) < 1: return fail("callNext stack < 1")
        tgt, rem = a[0], a[1:]
        if tgt[0] != 'const': return fail("callNext target not const")
        shape, seen_shape = f, set()
        while shape[0] == "join_ref":
            if shape[1] in seen_shape: return fail("cyclic continuation shape")
            seen_shape.add(shape[1])
            shape = trees[shape[1]]
        if shape[0] != "dest": return fail("callNext cont not dest")
        if k >= len(es): return fail("callNext k >= len(es)")
        e_pc, e_frame, e_rets = es[k]
        if pc >= len(code_bytes) or code_bytes[pc] != 0x56: return fail("callNext not 0x56")
        if e_pc != tgt[1]: return fail("callNext epc != tgt")
        if len(rem) < len(e_frame): return fail("callNext len(rem) < len(e_frame)")
        ret_idx = None
        for i, v in enumerate(e_frame):
            if v[0] == 'ret':
                ret_idx = i
                break
        if ret_idx is not None:
            if ret_idx >= len(rem) or rem[ret_idx][0] != 'const':
                return fail("callNext ret_idx not const in rem")
            r = rem[ret_idx][1]
            if not call_compat(r, rem, e_frame):
                return fail("callNext call_compat failed")
            nxt_a = [('unk',)] * e_rets + rem[len(e_frame):]
            return check_node(code_bytes, es, m, r, nxt_a, f)
        else:
            return call_compat(0, rem, e_frame)
    elif kind == 'ret':
        if len(a) < 1: return fail("ret stack < 1")
        if a[0][0] != 'ret': return fail("ret top not ret")
        rem = a[1:]
        if pc >= len(code_bytes) or code_bytes[pc] != 0x56: return fail("ret not 0x56")
        return len(rem) == m
    elif kind == 'undefined':
        return pc not in inst_map or inst_map[pc][0] == 0xfe
    else:
        return False

# Run self-check on all successfully built entries
self_check_passed = True
checked_entries_count = 0
for e_idx in sorted(trees.keys()):
    epc, ef, er = entries[e_idx]
    debug_entry = False
    v = check_node(code, entries, er, epc, list(ef), trees[e_idx])
    if not v:
        self_check_passed = False
        print(f"Self-check FAILED on entry {e_idx} (pc 0x{epc:04x})", file=sys.stderr)
    else:
        checked_entries_count += 1

if not self_check_passed:
    print("Self-check mirror rejected! Exiting non-zero.", file=sys.stderr)
    sys.exit(1)

# 8. Lean Code Generation (Basic Block Decomposition)
def op_to_lean_reg(op: int) -> str:
    if op in LEAN_REG:
        return LEAN_REG[op]
    elif 0x80 <= op <= 0x8f:
        return f".reg (.dup {op - 0x80})"
    elif 0x90 <= op <= 0x9f:
        return f".reg (.swap {op - 0x90})"
    else:
        raise ValueError(f"Unknown regular opcode 0x{op:02x}")

# Decompose trees into definitions per basic block (ends at dest, branch, jump, callNext, ret, last)
lean_defs: List[Tuple[str, str]] = [] # (name, body)
def_memo: Dict[Tuple[int, int], str] = {} # (pc, entry_idx) -> def_name

def emit_block(tree: Any, entry_idx: int) -> str:
    kind = tree[0]
    if kind == 'join_ref':
        target_k = tree[1]
        return f"t_{entries[target_k][0]:04x}_c{target_k}"
    
    cur_pc = tree[-1]
    key = (cur_pc, entry_idx)
    if key in def_memo:
        return def_memo[key]
    
    def_name = f"t_{cur_pc:04x}_c{entry_idx}"
    def_memo[key] = def_name
    
    # Render tree into string
    def render(t: Any) -> str:
        k = t[0]
        if k == 'join_ref':
            target_k = t[1]
            return f"t_{entries[target_k][0]:04x}_c{target_k}"
        elif k == 'next':
            op, d = t[1]
            sub = t[2]
            if 0x5f <= op <= 0x7f:
                hex_list = ", ".join(f"0x{b:02x}" for b in d)
                op_str = f".push [{hex_list}] (by decide)"
            else:
                op_str = op_to_lean_reg(op)
            
            # If next instruction is JUMPDEST or join_ref, branch to new block def
            if sub[0] in ('dest', 'join_ref'):
                child_name = emit_block(sub, entry_idx)
                return f"(.next ({op_str}) {child_name})"
            else:
                return f"(.next ({op_str}) {render(sub)})"
        elif k == 'dest':
            sub = t[1]
            if sub[0] in ('dest', 'join_ref'):
                child_name = emit_block(sub, entry_idx)
                return f"(.dest {child_name})"
            else:
                return f"(.dest {render(sub)})"
        elif k == 'branch':
            fall, taken = t[1], t[2]
            fall_name = emit_block(fall, entry_idx)
            taken_name = emit_block(taken, entry_idx)
            return f"(.branch {fall_name} {taken_name})"
        elif k == 'branchTo':
            fall_name = emit_block(t[1], entry_idx)
            return f"(.branchTo {fall_name} {t[2]})"
        elif k == 'last':
            op = t[1]
            last_map = {0x00: ".last .stop", 0xf3: ".last .return_", 0xfd: ".last .revert", 0xff: ".last .selfdestruct"}
            return f"({last_map[op]})"
        elif k == 'jump':
            target_k = t[1]
            return f"(.jump {target_k})"
        elif k == 'callNext':
            target_k = t[1]
            cont = t[2]
            cont_name = emit_block(cont, entry_idx)
            return f"(.callNext {target_k} {cont_name})"
        elif k == 'ret':
            return ".ret"
        elif k == 'undefined':
            return ".undefined"
        else:
            raise ValueError(f"Unknown kind {k}")

    body = render(tree)
    lean_defs.append((def_name, body))
    return def_name

# Emit definitions for all built entries
entry_def_names: Dict[int, str] = {}
for e_idx in sorted(trees.keys()):
    entry_def_names[e_idx] = emit_block(trees[e_idx], e_idx)

# Generate Cert.lean
lean_lines = []
lean_lines.append("import Blanc.Lift.Check")
lean_lines.append("")
lean_lines.append(f"/-! {args.header} -/")
lean_lines.append("")
lean_lines.append(f"namespace {args.namespace}")
lean_lines.append("")
lean_lines.append("open Jaune")
lean_lines.append("")
lean_lines.append(f"-- Code: {len(code)} bytes, SHA-256: {actual_sha256}")


def byte_lines(data: bytes) -> List[str]:
    """Code bytes, 16 per line."""
    out = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        hex_chunk = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(data) else ""
        out.append(f"  {hex_chunk}{comma}")
    return out


if len(code) <= CODE_LITERAL_MAX:
    lean_lines.append("def code : ByteArray := ⟨#[")
    lean_lines.extend(byte_lines(code))
    lean_lines.append("]⟩")
else:
    # One literal of this length exceeds Lean's elaboration recursion depth, so the
    # bytes are list chunks joined by `++` (definitionally `code.data.toList`).
    names = []
    for c, i in enumerate(range(0, len(code), CODE_CHUNK)):
        name = f"codeChunk{c}"
        names.append(name)
        lean_lines.append(f"def {name} : List UInt8 := [")
        lean_lines.extend(byte_lines(code[i : i + CODE_CHUNK]))
        lean_lines.append("]")
        lean_lines.append("")
    lean_lines.append(f"def code : ByteArray := ⟨({' ++ '.join(names)}).toArray⟩")
lean_lines.append("")

# Emit definitions in topological dependency order (defs appear before use)
def_dict = {name: body for name, body in lean_defs}
dep_graph: Dict[str, Set[str]] = {name: set() for name in def_dict}
for name, body in lean_defs:
    refs = re.findall(r"t_[0-9a-f]{4}_c\d+", body)
    for ref in refs:
        if ref in def_dict and ref != name:
            dep_graph[name].add(ref)

sorted_defs: List[Tuple[str, str]] = []
visited_defs: Set[str] = set()
visiting_defs: Set[str] = set()

def visit_def(dname: str):
    if dname in visited_defs:
        return
    if dname in visiting_defs:
        raise RuntimeError(f"Cyclic dependency in Lean definitions: {dname}")
    visiting_defs.add(dname)
    for dep in sorted(dep_graph[dname]):
        visit_def(dep)
    visiting_defs.remove(dname)
    visited_defs.add(dname)
    sorted_defs.append((dname, def_dict[dname]))

for name, _ in lean_defs:
    visit_def(name)

for name, body in sorted_defs:
    lean_lines.append(f"def {name} : SFunc := {body}")
lean_lines.append("")

# Generate def cert : Cert
lean_lines.append("def cert : Cert := [")
cert_entries_lines = []
for i, (epc, eframe, erets) in enumerate(entries):
    frame_vals = []
    for v in eframe:
        if v[0] == 'unk':
            frame_vals.append(".unk")
        elif v[0] == 'ret':
            frame_vals.append(".ret")
        elif v[0] == 'const':
            frame_vals.append(f"(.const (Nat.toB256 0x{v[1]:x}))")
    frame_str = "[" + ", ".join(frame_vals) + "]"
    t_name = entry_def_names[i]
    cert_entries_lines.append(f"  (⟨0x{epc:x}, {frame_str}, {erets}⟩, {t_name})")

lean_lines.append(",\n".join(cert_entries_lines))
lean_lines.append("]")
lean_lines.append("")
lean_lines.append(f"end {args.namespace}")
lean_lines.append("")

lean_file = args.cert_out
lean_file.parent.mkdir(parents=True, exist_ok=True)
lean_file.write_text("\n".join(lean_lines))

# 9. Generate cert.json and cfg.json
def tree_to_json(t: Any) -> Dict[str, Any]:
    kind = t[0]
    if kind == 'join_ref':
        return {"kind": "join", "pc": t[2], "target_entry": t[1]}
    elif kind == 'next':
        op, d = t[1]
        return {"kind": "next", "pc": t[3], "op": hex(op), "data": d.hex(), "sub": tree_to_json(t[2])}
    elif kind == 'last':
        return {"kind": "last", "pc": t[2], "op": hex(t[1])}
    elif kind == 'dest':
        return {"kind": "dest", "pc": t[2], "sub": tree_to_json(t[1])}
    elif kind == 'branch':
        return {"kind": "branch", "pc": t[3], "fall": tree_to_json(t[1]), "taken": tree_to_json(t[2])}
    elif kind == 'branchTo':
        return {"kind": "branchTo", "pc": t[3], "fall": tree_to_json(t[1]), "target_entry": t[2]}
    elif kind == 'jump':
        return {"kind": "jump", "pc": t[2], "target_entry": t[1]}
    elif kind == 'callNext':
        return {"kind": "callNext", "pc": t[3], "target_entry": t[1], "continuation": tree_to_json(t[2])}
    elif kind == 'ret':
        return {"kind": "ret", "pc": t[1]}
    elif kind == 'undefined':
        return {"kind": "undefined", "pc": t[1]}
    else:
        return {"kind": "unknown"}

def count_tree_nodes(t: Any) -> int:
    kind = t[0]
    if kind == 'join_ref':
        return 1
    elif kind == 'next':
        return 1 + count_tree_nodes(t[2])
    elif kind == 'dest':
        return 1 + count_tree_nodes(t[1])
    elif kind == 'branch':
        return 1 + count_tree_nodes(t[1]) + count_tree_nodes(t[2])
    elif kind == 'branchTo':
        return 1 + count_tree_nodes(t[1])
    elif kind == 'jump':
        return 1
    elif kind == 'callNext':
        return 1 + count_tree_nodes(t[2])
    elif kind in ('last', 'ret', 'undefined'):
        return 1
    return 1

entry_node_counts = {i: count_tree_nodes(trees[i]) for i in sorted(trees.keys())}
total_nodes = sum(entry_node_counts.values())

json_entries = []
for i, (epc, eframe, erets) in enumerate(entries):
    json_entries.append({
        "index": i,
        "pc": hex(epc),
        "frame": [v[0] if v[0] != 'const' else f"const(0x{v[1]:x})" for v in eframe],
        "rets": erets,
        "role": entry_roles.get(i, "goto"),
        "node_count": entry_node_counts.get(i, 0),
        "status": "verified" if i in trees else "rejected"
    })

json_trees = {str(i): tree_to_json(trees[i]) for i in sorted(trees.keys())}

# Deduplicate loops and external calls for clean static counts
distinct_back_edges: Dict[int, Dict[str, Any]] = {}
for b in back_edges:
    if b["pc"] not in distinct_back_edges:
        distinct_back_edges[b["pc"]] = b

distinct_calls: Dict[int, Dict[str, Any]] = {}
for c in external_calls:
    if c["pc"] not in distinct_calls:
        distinct_calls[c["pc"]] = c

json_data = {
    "code_length": len(code),
    "code_sha256": actual_sha256,
    "total_entries": len(entries),
    "total_nodes": total_nodes,
    "entries": json_entries,
    "trees": json_trees,
    "call_sites": [{"pc": hex(c[0]), "callee_entry": c[1], "continuation_pc": hex(c[2])} for c in call_sites],
    "return_sites": [{"pc": hex(r[0]), "entry": r[1], "rets": r[2]} for r in return_sites],
    "back_edges": [{"pc": hex(b["pc"]), "kind": b["kind"], "target_entry": b["target_entry"], "target_pc": hex(b["target_pc"])} for b in distinct_back_edges.values()],
    "external_calls": [{"pc": hex(c["pc"]), "type": c["type"], "target": c["target"], "entry": c["entry_idx"]} for c in distinct_calls.values()],
    "rejections": rejections
}

if out_dir is not None:
    # Compact JSON keeps the diagnostic within git/tool limits.
    (out_dir / "cert.json").write_text(json.dumps(json_data))

# Emit out/cfg.json: reachability per entry and containing entry per instruction PC
cfg_reaches: Dict[int, Set[int]] = {i: set() for i in range(len(entries))}
cfg_staticcall: Dict[str, int] = {}
cfg_jump: Dict[str, int] = {}
cfg_jumpi: Dict[str, int] = {}
cfg_pc_to_entry: Dict[str, int] = {}

for e_idx in sorted(trees.keys()):
    def walk_cfg(t: Any):
        kind = t[0]
        if kind == 'join_ref':
            target_k = t[1]
            cfg_reaches[e_idx].add(target_k)
            return
        elif kind == 'next':
            op, d = t[1]
            pc = t[3]
            if op == 0xfa: # STATICCALL
                hex_str = f"0x{pc:04x}"
                cfg_staticcall[hex_str] = e_idx
                cfg_pc_to_entry[hex_str] = e_idx
                if hex(pc) != hex_str:
                    cfg_staticcall[hex(pc)] = e_idx
                    cfg_pc_to_entry[hex(pc)] = e_idx
            walk_cfg(t[2])
        elif kind == 'dest':
            walk_cfg(t[1])
        elif kind == 'branch':
            pc = t[3] # JUMPI
            hex_str = f"0x{pc:04x}"
            cfg_jumpi[hex_str] = e_idx
            cfg_pc_to_entry[hex_str] = e_idx
            if hex(pc) != hex_str:
                cfg_jumpi[hex(pc)] = e_idx
                cfg_pc_to_entry[hex(pc)] = e_idx
            walk_cfg(t[1])
            walk_cfg(t[2])
        elif kind == 'branchTo':
            pc = t[3] # JUMPI
            hex_str = f"0x{pc:04x}"
            cfg_jumpi[hex_str] = e_idx
            cfg_pc_to_entry[hex_str] = e_idx
            if hex(pc) != hex_str:
                cfg_jumpi[hex(pc)] = e_idx
                cfg_pc_to_entry[hex(pc)] = e_idx
            target_k = t[2]
            cfg_reaches[e_idx].add(target_k)
            walk_cfg(t[1])
        elif kind == 'jump':
            pc = t[2] # JUMP
            hex_str = f"0x{pc:04x}"
            cfg_jump[hex_str] = e_idx
            cfg_pc_to_entry[hex_str] = e_idx
            if hex(pc) != hex_str:
                cfg_jump[hex(pc)] = e_idx
                cfg_pc_to_entry[hex(pc)] = e_idx
            target_k = t[1]
            cfg_reaches[e_idx].add(target_k)
        elif kind == 'callNext':
            pc = t[3] # JUMP
            hex_str = f"0x{pc:04x}"
            cfg_jump[hex_str] = e_idx
            cfg_pc_to_entry[hex_str] = e_idx
            if hex(pc) != hex_str:
                cfg_jump[hex(pc)] = e_idx
                cfg_pc_to_entry[hex(pc)] = e_idx
            target_k = t[1]
            cfg_reaches[e_idx].add(target_k)
            walk_cfg(t[2])
        elif kind == 'ret':
            pc = t[1] # JUMP
            hex_str = f"0x{pc:04x}"
            cfg_jump[hex_str] = e_idx
            cfg_pc_to_entry[hex_str] = e_idx
            if hex(pc) != hex_str:
                cfg_jump[hex(pc)] = e_idx
                cfg_pc_to_entry[hex(pc)] = e_idx
        elif kind in ('last', 'undefined'):
            pass

    walk_cfg(trees[e_idx])

cfg_data = {
    "entry_reaches": {str(i): sorted(list(cfg_reaches[i])) for i in sorted(trees.keys())},
    "entries": {
        str(i): {
            "index": i,
            "pc": f"0x{entries[i][0]:04x}",
            "role": entry_roles.get(i, "goto"),
            "reaches": sorted(list(cfg_reaches[i]))
        }
        for i in sorted(trees.keys())
    },
    "staticcall_pcs": cfg_staticcall,
    "jump_pcs": cfg_jump,
    "jumpi_pcs": cfg_jumpi,
    "pc_to_entry": cfg_pc_to_entry
}
if out_dir is not None:
    (out_dir / "cfg.json").write_text(json.dumps(cfg_data, indent=2))


# 10. Per-entry Check.lean: each entry is one kernel decision over trie-backed code
# reads (`Blanc/Lift/CheckFast.lean`), assembled into `cert_check`.
def check_source() -> str:
    depth = max(1, (len(code) - 1).bit_length())
    ns = args.namespace
    lines = [
        f"import {ns}.Cert",
        "import Blanc.Lift.CheckFast",
        "",
        f"/-! {args.check_header}",
        "Each entry is decided against trie-backed reads of the exact runtime.",
        "The generic equality rewrites each result to the unchanged Cert.check. -/",
        "",
        f"namespace {ns}",
        "",
        "open Jaune",
        "",
        f"/-- Depth {depth} covers all {len(code)} runtime byte positions. -/",
        f"def codeTries : CodeTries code {depth} :=",
        f"  CodeTries.ofCode code {depth} (by decide +kernel) (by decide +kernel)",
        "",
    ]
    for i, line in enumerate(cert_entries_lines):
        m = re.match(r"^  \(⟨(0x[0-9a-f]+), (\[[^\]]*\]), (\d+)⟩, (t_\w+)\)$", line)
        if m is None:
            raise RuntimeError(f"cannot read certificate entry {i}: {line}")
        pc, frame, rets, tree = m.groups()
        if args.check_split_nodes and entry_node_counts.get(i, 0) > args.check_split_nodes:
            raise RuntimeError(f"entry {i} has {entry_node_counts[i]} nodes > --check-split-nodes; splitting is not implemented")
        lines.extend([
            f"theorem entry_{i} :",
            f"    checkNode code (Cert.entries cert) {rets} {pc} {frame} {tree} = true := by",
            "  rw [← checkNodeT_eq codeTries]",
            "  decide +kernel",
            "",
        ])
    n = len(cert_entries_lines)
    lines.extend([
        "theorem cert_check : Cert.check code cert = true := by",
        "  unfold Cert.check",
        "  rw [Bool.and_eq_true]",
        "  refine ⟨by decide +kernel, ?_⟩",
        "  rw [List.all_eq_true]",
        "  intro p hp",
        "  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp",
        "  rcases hp with " + " | ".join(["rfl"] * n),
    ])
    lines.extend(f"  · exact entry_{i}" for i in range(n))
    lines.extend(["", f"end {ns}", ""])
    return "\n".join(lines)


if args.check_out is not None:
    args.check_out.parent.mkdir(parents=True, exist_ok=True)
    args.check_out.write_text(check_source())

# 11. Final summary print
largest = max(entry_node_counts.items(), key=lambda kv: kv[1]) if entry_node_counts else (0, 0)
print(f"Counts: entries={len(entries)}, calls={len(call_sites)}, rets={len(return_sites)}, nodes={total_nodes}, loops={len(distinct_back_edges)}, ext_calls={len(distinct_calls)}, largest_entry={largest[0]}:{largest[1]}")
print(f"Self-check verdict: {'PASS' if self_check_passed else 'FAIL'}")
print(f"Generated: {lean_file}" + (f", {args.check_out}" if args.check_out is not None else ""))
