import Blanc.Lift.Check
import Blanc.Lift.VyperNonreentrantDeployed.Fixed.Clone.Input

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Clone.Check.cert_check checks the synthetic clone creation input. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Fixed.Clone

open Jaune

-- Code: 54 bytes, SHA-256: 6784f452339424d595d31fcb73cfa776cd092515fa823fb14017d9b947511df1
def code : ByteArray := Blanc.Lift.VyperNonreentrantDeployed.Fixed.Clone.cloneCreationCode

def t_0000_c0 : SFunc := (.next (.push [0x2d] (by decide)) (.next (.reg .returndatasize) (.next (.reg (.dup 1)) (.next (.push [0x09] (by decide)) (.next (.reg .returndatasize) (.next (.reg .codecopy) (.last .return_)))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.VyperNonreentrantDeployed.Fixed.Clone
