import Blanc.Lift.VyperNonreentrantDeployed.Code

/-! GENERATED by Plans evidence/deployed-lido-vyper-v1/vyper-code/generate.py.
Small kernel facts for defensive local verification; do not edit.
The source/deployment binding remains external provenance evidence. -/

namespace Blanc.Lift.VyperNonreentrantDeployed

private theorem implementationChunk00_size : implementationChunk00.size = 128 := by rfl
private theorem implementationChunk01_size : implementationChunk01.size = 128 := by rfl
private theorem implementationChunk02_size : implementationChunk02.size = 128 := by rfl
private theorem implementationChunk03_size : implementationChunk03.size = 128 := by rfl
private theorem implementationChunk04_size : implementationChunk04.size = 128 := by rfl
private theorem implementationChunk05_size : implementationChunk05.size = 128 := by rfl
private theorem implementationChunk06_size : implementationChunk06.size = 128 := by rfl
private theorem implementationChunk07_size : implementationChunk07.size = 128 := by rfl
private theorem implementationChunk08_size : implementationChunk08.size = 128 := by rfl
private theorem implementationChunk09_size : implementationChunk09.size = 128 := by rfl
private theorem implementationChunk10_size : implementationChunk10.size = 128 := by rfl
private theorem implementationChunk11_size : implementationChunk11.size = 128 := by rfl
private theorem implementationChunk12_size : implementationChunk12.size = 128 := by rfl
private theorem implementationChunk13_size : implementationChunk13.size = 128 := by rfl
private theorem implementationChunk14_size : implementationChunk14.size = 128 := by rfl
private theorem implementationChunk15_size : implementationChunk15.size = 128 := by rfl
private theorem implementationChunk16_size : implementationChunk16.size = 128 := by rfl
private theorem implementationChunk17_size : implementationChunk17.size = 128 := by rfl
private theorem implementationChunk18_size : implementationChunk18.size = 128 := by rfl
private theorem implementationChunk19_size : implementationChunk19.size = 128 := by rfl
private theorem implementationChunk20_size : implementationChunk20.size = 128 := by rfl
private theorem implementationChunk21_size : implementationChunk21.size = 128 := by rfl
private theorem implementationChunk22_size : implementationChunk22.size = 128 := by rfl
private theorem implementationChunk23_size : implementationChunk23.size = 128 := by rfl
private theorem implementationChunk24_size : implementationChunk24.size = 128 := by rfl
private theorem implementationChunk25_size : implementationChunk25.size = 128 := by rfl
private theorem implementationChunk26_size : implementationChunk26.size = 128 := by rfl
private theorem implementationChunk27_size : implementationChunk27.size = 128 := by rfl
private theorem implementationChunk28_size : implementationChunk28.size = 128 := by rfl
private theorem implementationChunk29_size : implementationChunk29.size = 128 := by rfl
private theorem implementationChunk30_size : implementationChunk30.size = 128 := by rfl
private theorem implementationChunk31_size : implementationChunk31.size = 128 := by rfl
private theorem implementationChunk32_size : implementationChunk32.size = 128 := by rfl
private theorem implementationChunk33_size : implementationChunk33.size = 128 := by rfl
private theorem implementationChunk34_size : implementationChunk34.size = 128 := by rfl
private theorem implementationChunk35_size : implementationChunk35.size = 128 := by rfl
private theorem implementationChunk36_size : implementationChunk36.size = 128 := by rfl
private theorem implementationChunk37_size : implementationChunk37.size = 128 := by rfl
private theorem implementationChunk38_size : implementationChunk38.size = 128 := by rfl
private theorem implementationChunk39_size : implementationChunk39.size = 128 := by rfl
private theorem implementationChunk40_size : implementationChunk40.size = 128 := by rfl
private theorem implementationChunk41_size : implementationChunk41.size = 128 := by rfl
private theorem implementationChunk42_size : implementationChunk42.size = 128 := by rfl
private theorem implementationChunk43_size : implementationChunk43.size = 128 := by rfl
private theorem implementationChunk44_size : implementationChunk44.size = 128 := by rfl
private theorem implementationChunk45_size : implementationChunk45.size = 128 := by rfl
private theorem implementationChunk46_size : implementationChunk46.size = 128 := by rfl
private theorem implementationChunk47_size : implementationChunk47.size = 128 := by rfl
private theorem implementationChunk48_size : implementationChunk48.size = 128 := by rfl
private theorem implementationChunk49_size : implementationChunk49.size = 128 := by rfl
private theorem implementationChunk50_size : implementationChunk50.size = 128 := by rfl
private theorem implementationChunk51_size : implementationChunk51.size = 128 := by rfl
private theorem implementationChunk52_size : implementationChunk52.size = 128 := by rfl
private theorem implementationChunk53_size : implementationChunk53.size = 128 := by rfl
private theorem implementationChunk54_size : implementationChunk54.size = 128 := by rfl
private theorem implementationChunk55_size : implementationChunk55.size = 128 := by rfl
private theorem implementationChunk56_size : implementationChunk56.size = 128 := by rfl
private theorem implementationChunk57_size : implementationChunk57.size = 128 := by rfl
private theorem implementationChunk58_size : implementationChunk58.size = 128 := by rfl
private theorem implementationChunk59_size : implementationChunk59.size = 128 := by rfl
private theorem implementationChunk60_size : implementationChunk60.size = 128 := by rfl
private theorem implementationChunk61_size : implementationChunk61.size = 128 := by rfl
private theorem implementationChunk62_size : implementationChunk62.size = 128 := by rfl
private theorem implementationChunk63_size : implementationChunk63.size = 128 := by rfl
private theorem implementationChunk64_size : implementationChunk64.size = 128 := by rfl
private theorem implementationChunk65_size : implementationChunk65.size = 128 := by rfl
private theorem implementationChunk66_size : implementationChunk66.size = 128 := by rfl
private theorem implementationChunk67_size : implementationChunk67.size = 128 := by rfl
private theorem implementationChunk68_size : implementationChunk68.size = 128 := by rfl
private theorem implementationChunk69_size : implementationChunk69.size = 128 := by rfl
private theorem implementationChunk70_size : implementationChunk70.size = 128 := by rfl
private theorem implementationChunk71_size : implementationChunk71.size = 128 := by rfl
private theorem implementationChunk72_size : implementationChunk72.size = 128 := by rfl
private theorem implementationChunk73_size : implementationChunk73.size = 128 := by rfl
private theorem implementationChunk74_size : implementationChunk74.size = 128 := by rfl
private theorem implementationChunk75_size : implementationChunk75.size = 128 := by rfl
private theorem implementationChunk76_size : implementationChunk76.size = 128 := by rfl
private theorem implementationChunk77_size : implementationChunk77.size = 128 := by rfl
private theorem implementationChunk78_size : implementationChunk78.size = 128 := by rfl
private theorem implementationChunk79_size : implementationChunk79.size = 128 := by rfl
private theorem implementationChunk80_size : implementationChunk80.size = 128 := by rfl
private theorem implementationChunk81_size : implementationChunk81.size = 128 := by rfl
private theorem implementationChunk82_size : implementationChunk82.size = 128 := by rfl
private theorem implementationChunk83_size : implementationChunk83.size = 128 := by rfl
private theorem implementationChunk84_size : implementationChunk84.size = 128 := by rfl
private theorem implementationChunk85_size : implementationChunk85.size = 128 := by rfl
private theorem implementationChunk86_size : implementationChunk86.size = 128 := by rfl
private theorem implementationChunk87_size : implementationChunk87.size = 128 := by rfl
private theorem implementationChunk88_size : implementationChunk88.size = 128 := by rfl
private theorem implementationChunk89_size : implementationChunk89.size = 128 := by rfl
private theorem implementationChunk90_size : implementationChunk90.size = 128 := by rfl
private theorem implementationChunk91_size : implementationChunk91.size = 128 := by rfl
private theorem implementationChunk92_size : implementationChunk92.size = 128 := by rfl
private theorem implementationChunk93_size : implementationChunk93.size = 128 := by rfl
private theorem implementationChunk94_size : implementationChunk94.size = 128 := by rfl
private theorem implementationChunk95_size : implementationChunk95.size = 128 := by rfl
private theorem implementationChunk96_size : implementationChunk96.size = 128 := by rfl
private theorem implementationChunk97_size : implementationChunk97.size = 128 := by rfl
private theorem implementationChunk98_size : implementationChunk98.size = 128 := by rfl
private theorem implementationChunk99_size : implementationChunk99.size = 128 := by rfl
private theorem implementationChunk100_size : implementationChunk100.size = 128 := by rfl
private theorem implementationChunk101_size : implementationChunk101.size = 128 := by rfl
private theorem implementationChunk102_size : implementationChunk102.size = 128 := by rfl
private theorem implementationChunk103_size : implementationChunk103.size = 128 := by rfl
private theorem implementationChunk104_size : implementationChunk104.size = 128 := by rfl
private theorem implementationChunk105_size : implementationChunk105.size = 128 := by rfl
private theorem implementationChunk106_size : implementationChunk106.size = 128 := by rfl
private theorem implementationChunk107_size : implementationChunk107.size = 128 := by rfl
private theorem implementationChunk108_size : implementationChunk108.size = 128 := by rfl
private theorem implementationChunk109_size : implementationChunk109.size = 128 := by rfl
private theorem implementationChunk110_size : implementationChunk110.size = 128 := by rfl
private theorem implementationChunk111_size : implementationChunk111.size = 128 := by rfl
private theorem implementationChunk112_size : implementationChunk112.size = 128 := by rfl
private theorem implementationChunk113_size : implementationChunk113.size = 128 := by rfl
private theorem implementationChunk114_size : implementationChunk114.size = 128 := by rfl
private theorem implementationChunk115_size : implementationChunk115.size = 128 := by rfl
private theorem implementationChunk116_size : implementationChunk116.size = 128 := by rfl
private theorem implementationChunk117_size : implementationChunk117.size = 128 := by rfl
private theorem implementationChunk118_size : implementationChunk118.size = 128 := by rfl
private theorem implementationChunk119_size : implementationChunk119.size = 128 := by rfl
private theorem implementationChunk120_size : implementationChunk120.size = 128 := by rfl
private theorem implementationChunk121_size : implementationChunk121.size = 128 := by rfl
private theorem implementationChunk122_size : implementationChunk122.size = 128 := by rfl
private theorem implementationChunk123_size : implementationChunk123.size = 128 := by rfl
private theorem implementationChunk124_size : implementationChunk124.size = 128 := by rfl
private theorem implementationChunk125_size : implementationChunk125.size = 128 := by rfl
private theorem implementationChunk126_size : implementationChunk126.size = 128 := by rfl
private theorem implementationChunk127_size : implementationChunk127.size = 128 := by rfl
private theorem implementationChunk128_size : implementationChunk128.size = 128 := by rfl
private theorem implementationChunk129_size : implementationChunk129.size = 128 := by rfl
private theorem implementationChunk130_size : implementationChunk130.size = 128 := by rfl
private theorem implementationChunk131_size : implementationChunk131.size = 128 := by rfl
private theorem implementationChunk132_size : implementationChunk132.size = 128 := by rfl
private theorem implementationChunk133_size : implementationChunk133.size = 128 := by rfl
private theorem implementationChunk134_size : implementationChunk134.size = 128 := by rfl
private theorem implementationChunk135_size : implementationChunk135.size = 128 := by rfl
private theorem implementationChunk136_size : implementationChunk136.size = 127 := by rfl

theorem implementationCode_size : implementationCode.size = 17535 := by
  simp only [implementationCode, ByteArray.size_append,
    implementationChunk00_size,
    implementationChunk01_size,
    implementationChunk02_size,
    implementationChunk03_size,
    implementationChunk04_size,
    implementationChunk05_size,
    implementationChunk06_size,
    implementationChunk07_size,
    implementationChunk08_size,
    implementationChunk09_size,
    implementationChunk10_size,
    implementationChunk11_size,
    implementationChunk12_size,
    implementationChunk13_size,
    implementationChunk14_size,
    implementationChunk15_size,
    implementationChunk16_size,
    implementationChunk17_size,
    implementationChunk18_size,
    implementationChunk19_size,
    implementationChunk20_size,
    implementationChunk21_size,
    implementationChunk22_size,
    implementationChunk23_size,
    implementationChunk24_size,
    implementationChunk25_size,
    implementationChunk26_size,
    implementationChunk27_size,
    implementationChunk28_size,
    implementationChunk29_size,
    implementationChunk30_size,
    implementationChunk31_size,
    implementationChunk32_size,
    implementationChunk33_size,
    implementationChunk34_size,
    implementationChunk35_size,
    implementationChunk36_size,
    implementationChunk37_size,
    implementationChunk38_size,
    implementationChunk39_size,
    implementationChunk40_size,
    implementationChunk41_size,
    implementationChunk42_size,
    implementationChunk43_size,
    implementationChunk44_size,
    implementationChunk45_size,
    implementationChunk46_size,
    implementationChunk47_size,
    implementationChunk48_size,
    implementationChunk49_size,
    implementationChunk50_size,
    implementationChunk51_size,
    implementationChunk52_size,
    implementationChunk53_size,
    implementationChunk54_size,
    implementationChunk55_size,
    implementationChunk56_size,
    implementationChunk57_size,
    implementationChunk58_size,
    implementationChunk59_size,
    implementationChunk60_size,
    implementationChunk61_size,
    implementationChunk62_size,
    implementationChunk63_size,
    implementationChunk64_size,
    implementationChunk65_size,
    implementationChunk66_size,
    implementationChunk67_size,
    implementationChunk68_size,
    implementationChunk69_size,
    implementationChunk70_size,
    implementationChunk71_size,
    implementationChunk72_size,
    implementationChunk73_size,
    implementationChunk74_size,
    implementationChunk75_size,
    implementationChunk76_size,
    implementationChunk77_size,
    implementationChunk78_size,
    implementationChunk79_size,
    implementationChunk80_size,
    implementationChunk81_size,
    implementationChunk82_size,
    implementationChunk83_size,
    implementationChunk84_size,
    implementationChunk85_size,
    implementationChunk86_size,
    implementationChunk87_size,
    implementationChunk88_size,
    implementationChunk89_size,
    implementationChunk90_size,
    implementationChunk91_size,
    implementationChunk92_size,
    implementationChunk93_size,
    implementationChunk94_size,
    implementationChunk95_size,
    implementationChunk96_size,
    implementationChunk97_size,
    implementationChunk98_size,
    implementationChunk99_size,
    implementationChunk100_size,
    implementationChunk101_size,
    implementationChunk102_size,
    implementationChunk103_size,
    implementationChunk104_size,
    implementationChunk105_size,
    implementationChunk106_size,
    implementationChunk107_size,
    implementationChunk108_size,
    implementationChunk109_size,
    implementationChunk110_size,
    implementationChunk111_size,
    implementationChunk112_size,
    implementationChunk113_size,
    implementationChunk114_size,
    implementationChunk115_size,
    implementationChunk116_size,
    implementationChunk117_size,
    implementationChunk118_size,
    implementationChunk119_size,
    implementationChunk120_size,
    implementationChunk121_size,
    implementationChunk122_size,
    implementationChunk123_size,
    implementationChunk124_size,
    implementationChunk125_size,
    implementationChunk126_size,
    implementationChunk127_size,
    implementationChunk128_size,
    implementationChunk129_size,
    implementationChunk130_size,
    implementationChunk131_size,
    implementationChunk132_size,
    implementationChunk133_size,
    implementationChunk134_size,
    implementationChunk135_size,
    implementationChunk136_size]

theorem proxyCode_size : proxyCode.size = 45 := by rfl

/-- The 20-byte immediate in the proxy's `PUSH20` is the pinned implementation. -/
theorem proxyCode_implementation_bytes :
    (proxyCode.data.toList.drop 10).take 20 =
      [0x63, 0x26, 0xde, 0xbb, 0xaa, 0x15, 0xbc, 0xfe, 0x60, 0x3d,
       0x83, 0x1e, 0x7d, 0x75, 0xf4, 0xfc, 0x10, 0xd9, 0xb4, 0x3e] := by
  decide

end Blanc.Lift.VyperNonreentrantDeployed
