#!/usr/bin/env bash
# PRORATA fixture conformance.  The suite is generated by
# scripts/gen-prorata-fixtures.py; its arithmetic vectors are independently
# regenerated by scripts/gen-prorata-oracle-vectors.py --check.
#
# Usage: scripts/check-prorata.sh [--no-build|--self-test]
#
# --no-build requires the Jaune fixture runner already built at this exact
# source state.  Exit zero only when the manifest, vector, runtime-byte, and
# every Prague fixture leg pass.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
FIXTURES_DIR="$ROOT/scripts/fixtures/prorata"
MANIFEST="$FIXTURES_DIR/manifest.json"
BIN="$ROOT/.lake/packages/jaune/.lake/build/bin/jaune"
NETWORK="Prague"
BUILD=1
SELF_TEST=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --no-build) BUILD=0 ;;
    --self-test) BUILD=0; SELF_TEST=1 ;;
    *) echo "usage: scripts/check-prorata.sh [--no-build|--self-test]" >&2; exit 2 ;;
  esac
  shift
done

if [ "$BUILD" -eq 1 ]; then
  if ! (cd "$ROOT" && lake build jaune/jaune); then
    echo "REGRESSION — prorata fixtures: lake build jaune/jaune failed"
    exit 1
  fi
fi
if [ ! -x "$BIN" ]; then
  echo "REGRESSION — prorata fixtures: runner binary not found at $BIN" >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "REGRESSION — prorata fixtures: python3 not found on PATH" >&2
  exit 1
fi

BLANC_COMMIT="$(cd "$ROOT" && git rev-parse HEAD 2>/dev/null || echo unknown)"
JAUNE_PIN="$(cd "$ROOT" && git -C .lake/packages/jaune rev-parse HEAD 2>/dev/null || echo unknown)"
echo "prorata fixtures — blanc $BLANC_COMMIT, jaune pin $JAUNE_PIN, network $NETWORK"

check_manifest() {
python3 - "$1" "$2" <<'PYEOF'
import json, os, sys

fixtures_dir, manifest_path = sys.argv[1:]
try:
    with open(manifest_path, encoding="utf-8") as f:
        rows = json.load(f)
except (OSError, json.JSONDecodeError) as exc:
    print(f"MANIFEST-ERROR {exc}")
    raise SystemExit(1)
if not isinstance(rows, list) or not rows:
    print("MANIFEST-ERROR empty or malformed manifest")
    raise SystemExit(1)
names = []
for row in rows:
    if not isinstance(row, dict) or set(("name", "outcome", "assertions")) - set(row):
        print(f"MANIFEST-ERROR malformed row: {row!r}")
        raise SystemExit(1)
    if not isinstance(row["assertions"], int) or row["assertions"] < 1:
        print(f"MANIFEST-ERROR non-positive assertion count for {row['name']!r}")
        raise SystemExit(1)
    names.append(row["name"])
if len(names) != len(set(names)):
    print("MANIFEST-ERROR duplicate scenario name")
    raise SystemExit(1)
disk = {p[:-5] for p in os.listdir(fixtures_dir)
        if p.endswith(".json") and p != "manifest.json"}
missing, orphaned = sorted(set(names) - disk), sorted(disk - set(names))
for name in missing:
    print(f"MANIFEST-MISSING {name}")
for name in orphaned:
    print(f"MANIFEST-ORPHAN {name}")
if missing or orphaned:
    raise SystemExit(1)
print(f"MANIFEST-OK {len(names)} scenario(s) cross-checked, "
      f"{sum(row['assertions'] for row in rows)} total assertions")
PYEOF
}

if [ "$SELF_TEST" -eq 1 ]; then
  set -e
  SELF_TEST_DIR="$(mktemp -d /private/tmp/prorata-self-test.XXXXXX)"
  trap 'rm -rf "$SELF_TEST_DIR"' EXIT

  cp -R "$FIXTURES_DIR" "$SELF_TEST_DIR/fixtures"
  python3 - "$SELF_TEST_DIR/fixtures/manifest.json" <<'PYEOF'
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
rows = json.loads(p.read_text())
rows.pop(0)
p.write_text(json.dumps(rows, indent=2) + "\n")
PYEOF
  if check_manifest "$SELF_TEST_DIR/fixtures" "$SELF_TEST_DIR/fixtures/manifest.json" >/dev/null 2>&1; then
    echo "REGRESSION — prorata fixture self-test: deleted manifest expectation escaped" >&2
    exit 1
  fi

  mkdir -p "$SELF_TEST_DIR/root/scripts"
  cp "$ROOT/scripts/gen-prorata-oracle-vectors.py" "$SELF_TEST_DIR/root/scripts/"
  cp "$ROOT/scripts/prorata_oracle.py" "$SELF_TEST_DIR/root/scripts/"
  cp "$ROOT/scripts/prorata-oracle-vectors.json" "$SELF_TEST_DIR/root/scripts/"
  python3 - "$SELF_TEST_DIR/root/scripts/prorata-oracle-vectors.json" <<'PYEOF'
import json, sys
from pathlib import Path
p = Path(sys.argv[1])
obj = json.loads(p.read_text())
obj["meta"]["offset"] += 1
p.write_text(json.dumps(obj, sort_keys=True, separators=(",", ":")) + "\n")
PYEOF
  if (cd "$SELF_TEST_DIR/root" && python3 scripts/gen-prorata-oracle-vectors.py --check >/dev/null 2>&1); then
    echo "REGRESSION — prorata fixture self-test: mutated oracle vector escaped" >&2
    exit 1
  fi
  echo "OK — prorata fixture self-test: deleted manifest expectation and mutated oracle vector both rejected"
  exit 0
fi

if [ ! -f "$MANIFEST" ]; then
  echo "REGRESSION — prorata fixtures: manifest not found at $MANIFEST" >&2
  exit 1
fi

MANIFEST_OUT="$(check_manifest "$FIXTURES_DIR" "$MANIFEST")"
MANIFEST_STATUS=$?
printf '%s\n' "$MANIFEST_OUT"
if [ "$MANIFEST_STATUS" -ne 0 ]; then
  echo "REGRESSION — prorata fixtures: manifest cross-check failed"
  exit 1
fi

VECTOR_OUT="$(cd "$ROOT" && python3 scripts/gen-prorata-oracle-vectors.py --check 2>&1)"
VECTOR_STATUS=$?
printf '%s\n' "$VECTOR_OUT"
if [ "$VECTOR_STATUS" -ne 0 ]; then
  echo "REGRESSION — prorata fixtures: oracle vector check failed"
  exit 1
fi

RUNTIME_OUT="$(python3 "$SCRIPT_DIR/check-runtime-bytes.py" \
  --lean "$ROOT/Blanc/ProrataCode.lean" --def prorataCode \
  --fixtures-dir "$FIXTURES_DIR" --label prorata 2>&1)"
RUNTIME_STATUS=$?
printf '%s\n' "$RUNTIME_OUT"
if [ "$RUNTIME_STATUS" -ne 0 ]; then
  echo "REGRESSION — prorata fixtures: runtime byte-equality gate failed"
  exit 1
fi

FAIL=0
TOTAL=0
OUT="$(mktemp)"
trap 'rm -f "$OUT"' EXIT
for fixture in "$FIXTURES_DIR"/*.json; do
  [ "$(basename "$fixture")" = "manifest.json" ] && continue
  TOTAL=$((TOTAL + 1))
  if "$BIN" "$fixture" --network "$NETWORK" >"$OUT" 2>&1; then
    echo "PASS  $(basename "$fixture")"
  else
    echo "FAIL  $(basename "$fixture")"
    sed 's/^/      /' "$OUT"
    FAIL=$((FAIL + 1))
  fi
done
if [ "$TOTAL" -eq 0 ]; then
  echo "REGRESSION — prorata fixtures: no fixture files found"
  exit 1
fi
if [ "$FAIL" -eq 0 ]; then
  echo "OK — prorata fixtures: $TOTAL/$TOTAL PASS, manifest/vector/runtime checks clean"
  exit 0
fi
echo "REGRESSION — prorata fixtures: $((TOTAL - FAIL))/$TOTAL PASS, $FAIL FAIL"
exit 1
