#!/usr/bin/env bash
# Closed transaction-level WETH10 redemption evidence.  The committed Prague
# blockchain fixtures are generated by pinned EELS t8n, checked against
# scenario-specific semantic assertions before being written, and replayed
# here through Jaune's full block/transaction/receipt path.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
FIXTURES_DIR="$ROOT/scripts/fixtures/weth10-redemption"
MANIFEST="$FIXTURES_DIR/manifest.json"
BIN="$ROOT/.lake/packages/jaune/.lake/build/bin/jaune"
NETWORK="Prague"
EELS_ROOT="${EELS_ROOT:-$HOME/execution-specs}"
EELS_PY="$EELS_ROOT/venv/bin/python"

BUILD=1
while [ $# -gt 0 ]; do
  case "$1" in
    --no-build) BUILD=0 ;;
    *) echo "usage: scripts/check-weth10-redemption.sh [--no-build]" >&2; exit 2 ;;
  esac
  shift
done

if [ "$BUILD" -eq 1 ]; then
  if ! (cd "$ROOT" && lake build jaune/jaune); then
    echo "REGRESSION — WETH10 redemption fixtures: lake build jaune/jaune failed"
    exit 1
  fi
fi
if [ ! -x "$BIN" ]; then
  echo "REGRESSION — WETH10 redemption fixtures: Jaune runner not found at $BIN" >&2
  exit 1
fi
if [ ! -f "$MANIFEST" ]; then
  echo "REGRESSION — WETH10 redemption fixtures: missing manifest $MANIFEST" >&2
  exit 1
fi
if [ ! -x "$EELS_PY" ]; then
  echo "REGRESSION — WETH10 redemption fixtures: pinned EELS python not found at $EELS_PY" >&2
  exit 1
fi

# Regenerate in memory, rerun all scenario-specific semantic assertions, and
# byte-compare every prospective artifact with the committed fixture/manifest.
# A coherent golden rewrite therefore cannot preserve a green Jaune replay by
# merely updating consensus roots and manifest metadata.
SEMANTIC_OUT="$(PYTHONPATH="$EELS_ROOT/src" "$EELS_PY" \
  "$SCRIPT_DIR/gen-weth10-redemption-fixtures.py" --check 2>&1)"
SEMANTIC_STATUS=$?
printf '%s\n' "$SEMANTIC_OUT"
if [ "$SEMANTIC_STATUS" -ne 0 ]; then
  echo "REGRESSION — WETH10 redemption fixtures: semantic regeneration check failed"
  exit 1
fi

PY=python3
MANIFEST_OUT="$($PY - "$FIXTURES_DIR" "$MANIFEST" <<'PYEOF'
import json, os, sys

fixtures_dir, manifest_path = sys.argv[1], sys.argv[2]
manifest = json.load(open(manifest_path))
if not isinstance(manifest, list) or len(manifest) != 2:
    print("MANIFEST-ERROR expected exactly two WETH10 redemption scenarios")
    sys.exit(1)

expected = {
    "01-type2-redemption": {
        "types": [2, 2, 2],
        "receipts": [True, True, False],
        "mutation": "none",
        "assertions": 16,
        "outcome": "receipts=true,true,false",
    },
    "02-authorization-mutation": {
        "types": [4],
        "receipts": [True],
        "mutation": "recipient code+nonce",
        "assertions": 13,
        "outcome": "receipts=true",
    },
}
names = []
for row in manifest:
    required = {
        "name", "outcome", "assertions", "transactionTypes",
        "receiptSucceeded", "authorizationMutation",
    }
    if not isinstance(row, dict) or set(row) != required:
        print(f"MANIFEST-ERROR malformed/flexible row: {row!r}")
        sys.exit(1)
    name = row["name"]
    if name not in expected:
        print(f"MANIFEST-ERROR unexpected scenario {name!r}")
        sys.exit(1)
    pin = expected[name]
    if row["assertions"] != pin["assertions"]:
        print(f"MANIFEST-ERROR semantic assertion count drift for {name!r}")
        sys.exit(1)
    if row["outcome"] != pin["outcome"]:
        print(f"MANIFEST-ERROR named receipt outcome drift for {name!r}")
        sys.exit(1)
    if row["transactionTypes"] != pin["types"]:
        print(f"MANIFEST-ERROR transaction profile drift for {name!r}")
        sys.exit(1)
    if row["receiptSucceeded"] != pin["receipts"]:
        print(f"MANIFEST-ERROR receipt profile drift for {name!r}")
        sys.exit(1)
    if row["authorizationMutation"] != pin["mutation"]:
        print(f"MANIFEST-ERROR authorization evidence drift for {name!r}")
        sys.exit(1)
    names.append(name)

if len(set(names)) != len(names):
    print("MANIFEST-ERROR duplicate scenario")
    sys.exit(1)
disk = sorted(
    name[:-5] for name in os.listdir(fixtures_dir)
    if name.endswith(".json") and name != "manifest.json"
)
if sorted(names) != disk:
    print(f"MANIFEST-ERROR rows/files differ: rows={sorted(names)}, files={disk}")
    sys.exit(1)
print(
    f"MANIFEST-OK 2 scenarios, {sum(row['assertions'] for row in manifest)} "
    "generator assertions, exact type/receipt/authorization profiles"
)
PYEOF
)"
MANIFEST_STATUS=$?
printf '%s\n' "$MANIFEST_OUT"
if [ "$MANIFEST_STATUS" -ne 0 ]; then
  echo "REGRESSION — WETH10 redemption fixtures: manifest cross-check failed"
  exit 1
fi

RUNTIME_OUT="$($PY "$SCRIPT_DIR/check-runtime-bytes.py" \
  --lean "$ROOT/Blanc/Weth10Code.lean" --def weth10MainnetCode \
  --fixtures-dir "$FIXTURES_DIR" --label weth10-redemption 2>&1)"
RUNTIME_STATUS=$?
printf '%s\n' "$RUNTIME_OUT"
if [ "$RUNTIME_STATUS" -ne 0 ]; then
  echo "REGRESSION — WETH10 redemption fixtures: runtime byte check failed"
  exit 1
fi

FILES=("$FIXTURES_DIR"/*.json)
FAIL=0
TOTAL=0
OUT="$(mktemp)"
trap 'rm -f "$OUT"' EXIT
for file in "${FILES[@]}"; do
  [ "$(basename "$file")" = "manifest.json" ] && continue
  TOTAL=$((TOTAL + 1))
  if "$BIN" "$file" --network "$NETWORK" >"$OUT" 2>&1; then
    echo "PASS  $(basename "$file")"
  else
    echo "FAIL  $(basename "$file")"
    sed 's/^/      /' "$OUT"
    FAIL=$((FAIL + 1))
  fi
done

if [ "$TOTAL" -ne 2 ]; then
  echo "REGRESSION — WETH10 redemption fixtures: expected 2 runnable files, got $TOTAL"
  exit 1
fi
if [ "$FAIL" -eq 0 ]; then
  echo "OK — WETH10 redemption fixtures: 2/2 PASS; type-2 receipts 2 success + 1 failed; type-4 recipient code/nonce mutation pinned"
  exit 0
fi
echo "REGRESSION — WETH10 redemption fixtures: $((TOTAL - FAIL))/$TOTAL PASS, $FAIL FAIL"
exit 1
