#!/usr/bin/env bash
# DRIP family evidence gate. The first landing owns the target-independent
# integer oracle; compiled-byte and fixture replay joins this same gate once
# the G2 artifact exists.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT"
python3 -B scripts/gen-drip-oracle-vectors.py
python3 -B scripts/check-drip-oracle.py
python3 -B scripts/check-drip-oracle.py --self-test
echo "OK — DRIP evidence: generated bytes, exact semantics, and corruptions are live"
