#!/usr/bin/env python3
"""Fail-closed static pins for the PRORATA WETH vault G2 artifact."""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "Blanc/ProrataWethVault.lean"
CODE = ROOT / "Blanc/ProrataWethVaultCode.lean"
ARTIFACT = ROOT / "Blanc/ProrataWethVaultArtifact.lean"
GENERATOR = ROOT / "scripts/gen-prorata-weth-vault-code.lean"

RUNTIME_BYTES = 17_481
RUNTIME_SHA256 = "e57aebd462ffb71c703194f18b1577f3a58b8287a440b89619e9e62a5ded6770"

ABI = [
    ("totalAssets", "", 0, "totalAssets", "01e1d114"),
    ("name", "", 0, "name", "06fdde03"),
    ("convertToAssets", ".uint256", 1, "convertToAssets", "07a2d13a"),
    ("approve", ".address,.uint256", 2, "approve", "095ea7b3"),
    ("previewWithdraw", ".uint256", 1, "previewWithdraw", "0a28a477"),
    ("totalSupply", "", 0, "totalSupply", "18160ddd"),
    ("transferFrom", ".address,.address,.uint256", 3, "transferFrom", "23b872dd"),
    ("decimals", "", 0, "decimals", "313ce567"),
    ("asset", "", 0, "asset", "38d52e0f"),
    ("maxDeposit", ".address", 1, "maxDeposit", "402d267d"),
    ("previewRedeem", ".uint256", 1, "previewRedeem", "4cdad506"),
    ("deposit", ".uint256,.address", 2, "deposit", "6e553f65"),
    ("balanceOf", ".address", 1, "balanceOf", "70a08231"),
    ("mint", ".uint256,.address", 2, "mint", "94bf804d"),
    ("symbol", "", 0, "symbol", "95d89b41"),
    ("transfer", ".address,.uint256", 2, "transfer", "a9059cbb"),
    ("previewMint", ".uint256", 1, "previewMint", "b3d7f6b9"),
    ("withdraw", ".uint256,.address,.address", 3, "withdraw", "b460af94"),
    ("redeem", ".uint256,.address,.address", 3, "redeem", "ba087652"),
    ("maxMint", ".address", 1, "maxMint", "c63d75b6"),
    ("convertToShares", ".uint256", 1, "convertToShares", "c6e6f592"),
    ("maxWithdraw", ".address", 1, "maxWithdraw", "ce96cb77"),
    ("maxRedeem", ".address", 1, "maxRedeem", "d905777e"),
    ("allowance", ".address,.address", 2, "allowance", "dd62ed3e"),
    ("previewDeposit", ".uint256", 1, "previewDeposit", "ef8b30f7"),
]

AUX = [
    "Func.revert",
    "returnWord",
    "depositAfterQuote",
    "mintAfterQuote",
    "withdrawAfterQuote",
    "redeemAfterQuote",
    "transferStaged",
    "withdrawBurn",
    "redeemBurn",
    "maxMintAfterAssetCap",
]


def compact(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def read(path: Path, errors: list[str]) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        errors.append(f"cannot read {path.relative_to(ROOT)}: {exc}")
        return ""


def require(text: str, snippet: str, owner: str, errors: list[str]) -> None:
    if compact(snippet) not in compact(text):
        errors.append(f"{owner}: missing exact pin: {compact(snippet)}")


def check_runtime(text: str, errors: list[str]) -> None:
    literal_rows: dict[int, bytes] = {}
    chunk_re = re.compile(
        r"private def prorataWethVaultCodeChunk(\d+)\s*:\s*Bytes\s*:=\s*\[(.*?)\]",
        re.S,
    )
    for raw_index, body in chunk_re.findall(text):
        index = int(raw_index)
        if index in literal_rows:
            errors.append(f"runtime chunk {index}: duplicate literal definition")
            continue
        residue = re.sub(r"0x[0-9a-fA-F]{2}|[\s,]", "", body)
        if residue:
            errors.append(f"runtime chunk {raw_index}: unparsed content {residue!r}")
            continue
        tokens = re.findall(r"0x[0-9a-fA-F]{2}", body)
        literal_rows[index] = bytes(int(token, 16) for token in tokens)

    alias_rows: dict[int, int] = {}
    alias_re = re.compile(
        r"private def prorataWethVaultCodeChunk(\d+)\s*:\s*Bytes\s*:=\s*"
        r"prorataWethVaultCodeChunk(\d+)\b"
    )
    for raw_index, raw_target in alias_re.findall(text):
        index = int(raw_index)
        if index in alias_rows:
            errors.append(f"runtime chunk {index}: duplicate alias definition")
            continue
        alias_rows[index] = int(raw_target)

    if not literal_rows:
        errors.append("runtime: no generated byte chunks found")
        return
    overlapping = sorted(set(literal_rows) & set(alias_rows))
    if overlapping:
        errors.append(f"runtime: chunks defined as both literal and alias: {overlapping}")
    indices = sorted(set(literal_rows) | set(alias_rows))
    if indices != list(range(69)):
        errors.append(f"runtime: non-contiguous chunk indices {indices}")
    parsed_defs = len(literal_rows) + len(alias_rows)
    declared_defs = text.count("private def prorataWethVaultCodeChunk")
    if parsed_defs != declared_defs:
        errors.append(
            f"runtime: parsed {parsed_defs} chunk definitions but found {declared_defs} declarations"
        )
    if len(literal_rows) != 68 or alias_rows != {48: 34}:
        errors.append(
            "runtime: expected 68 literal chunks and canonical alias chunk48 -> chunk34; "
            f"found {len(literal_rows)} literals and aliases {alias_rows}"
        )

    resolved: dict[int, bytes] = {}

    def resolve(index: int, active: set[int]) -> bytes:
        if index in resolved:
            return resolved[index]
        if index in active:
            errors.append(f"runtime chunk {index}: alias cycle")
            return b""
        if index in literal_rows:
            resolved[index] = literal_rows[index]
            return resolved[index]
        target = alias_rows.get(index)
        if target is None:
            errors.append(f"runtime chunk {index}: missing definition")
            return b""
        if target >= index:
            errors.append(f"runtime chunk {index}: alias target {target} is not earlier")
        resolved[index] = resolve(target, active | {index})
        return resolved[index]

    rows = [(index, resolve(index, set())) for index in range(69)]
    for index, chunk in rows[:-1]:
        if len(chunk) != 256:
            errors.append(f"runtime chunk {index}: expected 256 bytes, found {len(chunk)}")
    if len(rows[-1][1]) != 73:
        errors.append(f"runtime final chunk: expected 73 bytes, found {len(rows[-1][1])}")

    runtime = b"".join(chunk for _, chunk in rows)
    if len(runtime) != RUNTIME_BYTES:
        errors.append(f"runtime: expected {RUNTIME_BYTES} bytes, found {len(runtime)}")
    digest = hashlib.sha256(runtime).hexdigest()
    if digest != RUNTIME_SHA256:
        errors.append(f"runtime: SHA-256 {digest}, expected {RUNTIME_SHA256}")
    if len(runtime) > 24_576:
        errors.append(f"runtime: {len(runtime)} bytes exceeds EIP-170")

    join_match = re.search(
        r"def prorataWethVaultCode\s*:\s*Bytes\s*:=\s*(.*?)\n\n/-- Kernel-checked",
        text,
        re.S,
    )
    if join_match is None:
        errors.append("runtime: committed literal join is missing")
    else:
        joined = [int(value) for value in re.findall(
            r"prorataWethVaultCodeChunk(\d+)", join_match.group(1)
        )]
        if joined != list(range(69)):
            errors.append(f"runtime: literal joins chunks in the wrong order: {joined}")

    require(text, f"The {RUNTIME_BYTES}-byte compiled EVM runtime.", "runtime", errors)
    require(
        text,
        "Prog.compile ProrataWethVault.vault = some prorataWethVaultCode := by decide +kernel",
        "runtime",
        errors,
    )


def check_abi(source: str, artifact: str, errors: list[str]) -> None:
    block_match = re.search(
        r"def vaultFuncs\s*:\s*List \(B256 × Func\)\s*:=\s*(.*?)\n\ntheorem vaultFuncs_sorted",
        source,
        re.S,
    )
    if block_match is None:
        errors.append("source: vaultFuncs block is missing")
        return
    block = block_match.group(1)
    entry_re = re.compile(
        r"\(selector\s+\"([^\"]+)\"\s+\[(.*?)\],\s*routed\s+(\d+)\s+([A-Za-z0-9_]+)\)",
        re.S,
    )
    observed = []
    for name, args, words, body in entry_re.findall(block):
        observed.append((name, re.sub(r"\s+", "", args), int(words), body))
    expected = [(name, args, words, body) for name, args, words, body, _ in ABI]
    if observed != expected:
        errors.append(f"source: ABI routes differ\n  observed={observed}\n  expected={expected}")
    if block.count("selector \"") != len(ABI):
        errors.append("source: ABI block contains an unparsed or extra selector entry")

    selector_match = re.search(
        r"theorem vaultSelectors_exact\s*:(.*?)\:= by",
        artifact,
        re.S,
    )
    if selector_match is None:
        errors.append("artifact: vaultSelectors_exact is missing")
    else:
        observed_selectors = re.findall(r"0x([0-9a-fA-F]{8})", selector_match.group(1))
        expected_selectors = [selector for *_, selector in ABI]
        if observed_selectors != expected_selectors:
            errors.append(
                f"artifact: selector list differs: {observed_selectors} != {expected_selectors}"
            )


def check_pins(source: str, artifact: str, generator: str, errors: list[str]) -> None:
    source_pins = [
        "def assetAddress : B256 := 0x1000",
        "def virtualShares : B256 := 1000",
        "def supplySlot : B256 := B256.max",
        "def maxSupply : B256 := B256.max - virtualShares",
        "def pushSupplySlot : Line := [pushB256 0, not]",
        "def checkAllowanceSlotCollision : Line := (dup 0 :: checkAddress) ++ (dup 1 :: isMax) ++ [Ninst.or]",
        "def name : Func := pushB256 (Blanc.String.toBytes \"PRORATA WETH Vault\").toB256",
        "def symbol : Func := pushB256 (Blanc.String.toBytes \"prWETH\").toB256",
        "def decimals : Func := returnConstant 21",
        "def endpoint (words : Nat) (body : Func) : Func := nonpayable (requireStaticArgs words body)",
        "def routed (words : Nat) (body : Func) : Func := endpoint words body",
        "def balanceOf : Func := canonicalAddressArg 0 <| arg 0 +++ sload ::: returnWord",
        "pushList [64, 0] +++ keccak256 ::: checkAllowanceSlotCollision +++ (Func.revert <?> (sload ::: returnWord))",
        "def maxMintAfterAssetCapSlot : Nat := 10",
        "loadWord quoteWord +++ shareRoom +++ lt ::: ((shareRoom +++ .call returnWordSlot) <?> (loadWord quoteWord +++ .call returnWordSlot))",
        "productOverTwoPow256 [pushB256 B256.max] stagedDenominator .down maxMintAfterAssetCapSlot",
        "mulDiv [pushB256 B256.max] stagedDenominator stagedAssetFactor .capDown maxMintAfterAssetCapSlot",
        "def vault : Prog := ⟨Func.mainWith revertSlot vaultTree, vaultAux⟩",
    ]
    for pin in source_pins:
        require(source, pin, "source", errors)

    artifact_pins = [
        "theorem vaultSelectorCount_exact : vaultSelectors.length = 25",
        "theorem noPermitSelector",
        "theorem assetAddress_exact : assetAddress = 0x1000 := rfl",
        "theorem virtualShares_exact : virtualShares = 1000 := rfl",
        "theorem supplySlot_exact : supplySlot = B256.max := rfl",
        "theorem maxSupply_exact : maxSupply = B256.max - 1000 := rfl",
        "approvalEvent = 0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925",
        "transferEvent = 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
        "depositEvent = 0xdcbc1c05240f31ff3ad067ef1ee35ce4997762752e3a095284754544f4c709d7",
        "withdrawEvent = 0xfbde797d201c681b91056529119e0b02407c7bb96a4a2c75c01fc9667232c8db",
        "theorem routed_exact",
        "routed words body = nonpayable (requireStaticArgs words body) := rfl",
        "theorem fallback_exact : revertSlot = 1 := rfl",
        f"theorem runtimeCodeSize_exact : prorataWethVaultCode.length = {RUNTIME_BYTES}",
        "theorem runtimeCodeWithinEip170 : prorataWethVaultCode.length ≤ 24576",
        "theorem runtimeCode_compile : Prog.compile vault = some prorataWethVaultCode := prorataWethVaultCode_compile",
    ]
    for pin in artifact_pins:
        require(artifact, pin, "artifact", errors)

    aux_match = re.search(r"theorem auxLayout_exact\s*:(.*?)\:= rfl", artifact, re.S)
    if aux_match is None:
        errors.append("artifact: auxLayout_exact is missing")
    else:
        observed_aux = re.findall(
            r"Func\.revert|returnWord|depositAfterQuote|mintAfterQuote|withdrawAfterQuote|"
            r"redeemAfterQuote|transferStaged|withdrawBurn|redeemBurn|maxMintAfterAssetCap",
            aux_match.group(1),
        )
        if observed_aux != AUX:
            errors.append(f"artifact: auxiliary layout differs: {observed_aux} != {AUX}")

    require(generator, "private partial def chunks", "generator", errors)
    require(generator, "private def renderByteChunkAlias", "generator", errors)
    require(generator, "indexedChunks.map (renderByteChunkDef indexedChunks)", "generator", errors)
    require(generator, "let byteChunks := chunks 256", "generator", errors)
    require(generator, '"Blanc" / "ProrataWethVaultCode.lean"', "generator", errors)


def main() -> int:
    if len(sys.argv) != 1:
        print("usage: scripts/check-prorata-weth-vault-artifact.py", file=sys.stderr)
        return 2
    errors: list[str] = []
    source = read(SOURCE, errors)
    code = read(CODE, errors)
    artifact = read(ARTIFACT, errors)
    generator = read(GENERATOR, errors)
    if not errors:
        check_runtime(code, errors)
        check_abi(source, artifact, errors)
        check_pins(source, artifact, generator, errors)
    if errors:
        for error in errors:
            print(f"REGRESSION — PRORATA WETH vault artifact: {error}", file=sys.stderr)
        return 1
    print(
        "OK — PRORATA WETH vault artifact: 25 selectors; 10 auxiliaries; "
        f"{RUNTIME_BYTES} runtime bytes; sha256 {RUNTIME_SHA256}; "
        "kernel compile witness green"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
