#!/usr/bin/env python3
"""Generate/check the PRORATA WETH wrap proof (review F14).

The load-bearing "exact Blanc WETH wraps" claim was evidenced only by the
stdout of an uncommitted /tmp script.  This registered generator replaces
it: it executes a direct WETH `transfer` of 10 to a receiver row sitting
at `U - 5` through Jaune t8n and records the raw pre-state allocation,
the transaction, and the raw t8n result.  The build asserts the executed
facts (status 1, receiver row lands on 4) and fails closed otherwise.

``--check`` regenerates the same canonical bytes and fails on drift.  The
differential gate re-executes this generator on every run and byte-compares
the committed JSON, so the proof cannot rot.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "prorata-weth-wrap-proof.json"

RECEIVER_KEY = 3
AMOUNT = 10


def _checker():
    """The differential checker beside this generator, lazily loaded."""
    sys.path.insert(0, str(HERE))
    spec = importlib.util.spec_from_file_location(
        "weth_wrap_proof_target", HERE / "check-prorata-weth-vault-differential.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def build(run=None) -> bytes:
    """Execute the wrap probe and return the canonical proof bytes."""
    c = _checker()
    if run is None:
        if not c.JAUNE.exists():
            raise RuntimeError(f"the Jaune runner is not built at {c.JAUNE}")
        run = c.Runner(c.blanc_side(), c._literal("Blanc/WethCode.lean", "wethCode"))
    receiver = c.signer_address(RECEIVER_KEY)
    world = run.alloc(100, 0, None, 0, {c.word(receiver): c.word(c.V.U - 5)})
    data = c.abi("transfer(address,uint256)", receiver, AMOUNT)
    result = run.call(world, data, target=c.WETH_ADDR)
    body = result.get("result", {})
    receipts = body.get("receipts", [])
    if len(receipts) != 1 or int(receipts[0].get("status", "0x0"), 16) != 1:
        raise AssertionError("wrap probe did not return exactly one status-1 receipt")
    landed = c.storage_get(result["alloc"][c.address(c.WETH_ADDR)]["storage"],
                           receiver)
    if landed != (c.V.U - 5 + AMOUNT) & c.V.U:
        raise AssertionError(f"wrap probe receiver row landed on {landed}, expected 4")
    obj = {
        "meta": {
            "generator": "scripts/gen-prorata-weth-wrap-proof.py",
            "claim": "exact Blanc WETH credit wraps modulo 2^256 (bare add, no ceiling check)",
            "review": "F14",
            "decision": "vault-oracle-weth-wrap-20260916 option A",
        },
        "world": world,
        "tx": {"target": "WETH_ADDR", "calldata": data, "value": 0,
               "gas": 3_000_000, "signing_key": 1},
        "result": result,
        "claims": {"status": 1, "receiver_row": landed},
    }
    return (json.dumps(obj, sort_keys=True, separators=(",", ":")) + "\n").encode()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="regenerate and fail on drift instead of writing")
    args = parser.parse_args(argv)
    try:
        payload = build()
    except RuntimeError as exc:
        print(f"REGRESSION — vault wrap-proof: {exc}")
        return 2
    except AssertionError as exc:
        print(f"REGRESSION — vault wrap-proof: {exc}")
        return 1
    if args.check:
        if not OUT.exists():
            print(f"REGRESSION — vault wrap-proof: {OUT.name} is missing")
            return 1
        if OUT.read_bytes() != payload:
            print("REGRESSION — vault wrap-proof: committed bytes differ from "
                  "the regenerated ones")
            return 1
        print(f"OK — vault wrap-proof: {OUT.name} matches the regenerated bytes")
        return 0
    OUT.write_bytes(payload)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
