#!/usr/bin/env python3
"""Pin the Prague differential lane's reference Python environment.

Blanc's historical differentials execute Solidity and Blanc side by side inside
a checkout of ethereum/execution-specs.  Until now that reference was pinned by
Git commit and a clean tree, and nothing else.  That is not enough to determine
a result.  The checkout declares its dependencies as ranges —

    pycryptodome>=3,<4   coincurve>=20,<21          typing_extensions>=4.4
    py-ecc>=8.0.0b2,<9   ethereum-types>=0.2.4,<0.3 ethereum-rlp>=0.1.4,<0.2

— and those six libraries are keccak-256, secp256k1 recovery, the BN254/BLS/KZG
precompiles, RLP encoding (hence every transaction, receipt and trie root) and
U256 arithmetic.  Two clean checkouts at the same commit can disagree on the
answer, and the drift is not hypothetical: this repository's own reference
environment holds `ethereum_rlp 0.1.5` while `0.1.6` sits inside the declared
range and is what a fresh resolve installs.

So this generator records the lane's *semantic closure* — the distributions the
specification package actually imports, with exact versions — and renders it as
a pip constraints file that provisioning consumes.  See eels_semantic_closure
for how the closure is derived and why it is narrow.

Distribution, complete executable-standard-library, and loaded native-interpreter content
digests are recorded per platform, and enforced on a platform once its row has
been generated there.  Every accepted process also uses an unreachable
bytecode-cache prefix, so excluded ``pyc`` files cannot become executable input.
Unlike the current-mainnet lock, an ungenerated platform is not fatal here:
the longstanding ``whereGenerated`` policy permits that lane to run but says
plainly that byte evidence is unavailable there.  Only a generated row is
content-verified evidence for its platform.
"""

from __future__ import annotations

import argparse
import copy
import json
import os
import platform as platform_module
import subprocess
import sys
from pathlib import Path
from typing import Any, NoReturn

sys.path.insert(0, str(Path(__file__).resolve().parent))

import eels_semantic_closure as closure  # noqa: E402

SCRIPTS = Path(__file__).resolve().parent
PIN_PATH = SCRIPTS / "eels-prague-closure.json"
CONSTRAINTS_PATH = SCRIPTS / "eels-prague-constraints.txt"

LANE = "blanc-eels-prague-differential"
REPOSITORY = "https://github.com/ethereum/execution-specs.git"
EELS_PIN = "4198b9c5996713b268aed602739d5aa40e277694"
SOURCE_ROOT = "src"
PYTHON_SERIES = "3.11"
PYTHON_IMPLEMENTATION = "CPython"

# The specification package, walked whole.  This lane drives EELS as a library —
# it imports `ethereum.prague.*` directly rather than running the t8n tool — so
# there is no tool entry module and nothing to attribute afterwards.
CLOSURE_POLICY = {
    "transitionModules": [],
    "transitionPackages": ["ethereum"],
    "runtimePackages": [],
}

PROVISIONING = {
    "tool": "pip",
    "command": "pip install -e . -c scripts/eels-prague-constraints.txt",
    "constraints": "eels-prague-constraints.txt",
}

CONSTRAINTS_HEADER = (
    "Generated by scripts/gen-eels-prague-closure.py --write.  Do not hand-edit.",
    "",
    "The semantic closure of ethereum/execution-specs at",
    f"{EELS_PIN},",
    "pinned exactly so that provisioning is reproducible.  The checkout declares",
    "these as ranges; a differential result depends on which end of the range you",
    "land on, so the range is not the pin.",
)


def fail(message: str) -> NoReturn:
    raise closure.ClosureError(message)


def resolve_root(explicit: str | None) -> Path:
    raw = explicit or os.environ.get("EELS_ROOT") or "~/execution-specs"
    root = Path(raw).expanduser()
    if not root.is_absolute():
        root = (Path.cwd() / root).resolve()
    if not root.is_dir():
        fail(f"pinned EELS checkout is absent: {root}")
    return root


def verify_checkout(root: Path) -> None:
    try:
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=root, text=True,
            capture_output=True, check=True).stdout.strip()
        dirty = subprocess.run(
            ["git", "status", "--porcelain"], cwd=root, text=True,
            capture_output=True, check=True).stdout.strip()
    except (OSError, subprocess.CalledProcessError) as exc:
        fail(f"cannot read the pinned EELS checkout at {root}: {exc}")
    if head != EELS_PIN or dirty:
        fail(
            f"pinned EELS checkout must be clean at {EELS_PIN}; "
            f"found {head}, dirty={bool(dirty)}"
        )


def target_python(root: Path) -> Path:
    python = root / "venv" / "bin" / "python"
    if not python.is_file() and not python.is_symlink():
        fail(f"pinned EELS environment has no interpreter at {python}")
    return python


def site_packages_of(root: Path) -> Path:
    candidates = sorted((root / "venv" / "lib").glob("python*/site-packages"))
    if len(candidates) != 1:
        fail(
            "pinned EELS environment must contain exactly one site-packages tree, "
            f"found {[str(path) for path in candidates]}"
        )
    return candidates[0]


def interpreter_series(observed: dict[str, Any]) -> str:
    return ".".join(observed["interpreter"]["version"].split(".")[:2])


def derive(root: Path) -> dict[str, Any]:
    python = target_python(root)
    env = {
        "HOME": os.environ.get("HOME", str(Path.home())),
        "PATH": os.pathsep.join([str(root / "venv" / "bin"), "/usr/bin", "/bin"]),
        "PYTHONNOUSERSITE": "1",
        "VIRTUAL_ENV": str(root / "venv"),
    }
    if os.environ.get("TMPDIR"):
        env["TMPDIR"] = os.environ["TMPDIR"]
    return closure.derive(
        python,
        site_packages_of(root),
        CLOSURE_POLICY,
        cwd=root,
        env=env,
        source_paths=[root / SOURCE_ROOT],
    )


def closure_section(observed: dict[str, Any]) -> dict[str, Any]:
    return {
        "policy": observed["policy"],
        "contentExcludes": list(closure.CONTENT_EXCLUDES),
        "bytecodePolicy": dict(closure.BYTECODE_POLICY),
        "executedLoaderPolicy": dict(closure.EXECUTED_LOADER_POLICY),
        "installerMetadataExcludes": list(closure.INSTALLER_METADATA),
        "standardLibraryPolicy": dict(closure.STANDARD_LIBRARY_POLICY),
        "interpreterRuntimePolicy": dict(closure.INTERPRETER_RUNTIME_POLICY),
        "distributions": [
            {
                "name": entry["name"],
                "version": entry["version"],
                "modules": entry["modules"],
            }
            for entry in observed["distributions"]
        ],
        "count": observed["count"],
        "versionsSha256": observed["versionsSha256"],
    }


def platform_row(observed: dict[str, Any]) -> dict[str, Any]:
    return {
        "generated": True,
        "pythonExecutableSha256": observed["pythonExecutableSha256"],
        "fileRecords": observed["fileRecords"],
        "contentSha256": observed["contentSha256"],
        "standardLibrary": observed["standardLibrary"],
        "interpreterRuntime": observed["interpreterRuntime"],
        "unownedSitePackages": observed["unownedSitePackages"],
        "distributions": [
            {
                "name": entry["name"],
                "files": entry["files"],
                "contentSha256": entry["contentSha256"],
            }
            for entry in observed["distributions"]
        ],
    }


def native_key() -> str:
    return closure.platform_key(
        platform_module.system(), platform_module.machine()
    )


def read_pin() -> dict[str, Any] | None:
    if not PIN_PATH.exists():
        return None
    try:
        return validate(json.loads(PIN_PATH.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, closure.ClosureError):
        return None


def build(root: Path, observed: dict[str, Any]) -> dict[str, Any]:
    section = closure_section(observed)
    previous = read_pin()
    platforms: dict[str, Any] = {}
    if previous is not None and previous["semanticClosure"]["versionsSha256"] == \
            section["versionsSha256"]:
        # Bytes measured elsewhere still describe this closure; carry them.
        platforms = copy.deepcopy(previous["platforms"])
    platforms[native_key()] = platform_row(observed)
    document = {
        "schema": 4,
        "lane": LANE,
        "checkout": {
            "repository": REPOSITORY,
            "commit": EELS_PIN,
            "sourceRoot": SOURCE_ROOT,
        },
        "interpreter": {
            "implementation": PYTHON_IMPLEMENTATION,
            "series": PYTHON_SERIES,
        },
        "provisioning": dict(PROVISIONING),
        "contentPolicy": "whereGenerated",
        "semanticClosure": section,
        "platforms": platforms,
    }
    return validate(document)


def validate(document: Any) -> dict[str, Any]:
    """Reject any pin that could be read as stronger than it is."""

    def keys(value: Any, expected: set[str], where: str) -> dict[str, Any]:
        if not isinstance(value, dict):
            fail(f"{where} is not an object")
        if set(value) != expected:
            fail(
                f"{where} keys differ: missing={sorted(expected - set(value))}, "
                f"extra={sorted(set(value) - expected)}"
            )
        return value

    top = keys(
        document,
        {
            "schema", "lane", "checkout", "interpreter", "provisioning",
            "contentPolicy", "semanticClosure", "platforms",
        },
        "prague closure pin",
    )
    if top["schema"] != 4 or top["lane"] != LANE:
        fail("prague closure pin identity differs")
    checkout = keys(
        top["checkout"], {"repository", "commit", "sourceRoot"}, "pin.checkout"
    )
    if checkout["repository"] != REPOSITORY or checkout["commit"] != EELS_PIN \
            or checkout["sourceRoot"] != SOURCE_ROOT:
        fail("prague closure pin does not name the pinned checkout")
    interpreter = keys(
        top["interpreter"], {"implementation", "series"}, "pin.interpreter"
    )
    if interpreter["implementation"] != PYTHON_IMPLEMENTATION \
            or interpreter["series"] != PYTHON_SERIES:
        fail("prague closure pin does not name the pinned interpreter")
    if top["provisioning"] != dict(PROVISIONING):
        fail("prague closure pin does not name the declared provisioning recipe")
    if top["contentPolicy"] != "whereGenerated":
        fail("prague closure pin content policy differs")

    section = keys(
        top["semanticClosure"],
        {
            "policy", "contentExcludes", "bytecodePolicy", "executedLoaderPolicy",
            "installerMetadataExcludes", "standardLibraryPolicy",
            "interpreterRuntimePolicy",
            "distributions", "count", "versionsSha256",
        },
        "pin.semanticClosure",
    )
    if section["policy"] != CLOSURE_POLICY:
        fail("prague closure policy differs from the declared derivation")
    if section["contentExcludes"] != list(closure.CONTENT_EXCLUDES) \
            or section["installerMetadataExcludes"] != list(closure.INSTALLER_METADATA):
        fail("prague closure exclusion policy differs")
    if section["bytecodePolicy"] != dict(closure.BYTECODE_POLICY):
        fail("prague closure bytecode policy differs")
    if section["executedLoaderPolicy"] != dict(closure.EXECUTED_LOADER_POLICY):
        fail("prague closure executed-loader policy differs")
    if section["standardLibraryPolicy"] != dict(closure.STANDARD_LIBRARY_POLICY):
        fail("prague closure standard-library policy differs")
    if section["interpreterRuntimePolicy"] != \
            dict(closure.INTERPRETER_RUNTIME_POLICY):
        fail("prague closure interpreter-runtime policy differs")
    entries = section["distributions"]
    if not isinstance(entries, list) or not entries:
        fail("prague closure names no distribution")
    seen: set[str] = set()
    for entry in entries:
        row = keys(entry, {"name", "version", "modules"}, "closure distribution")
        if not isinstance(row["name"], str) or not isinstance(row["version"], str) \
                or not row["name"] or not row["version"]:
            fail("closure distribution identity is malformed")
        if row["name"] in seen:
            fail(f"prague closure names {row['name']} twice")
        seen.add(row["name"])
        if not isinstance(row["modules"], list) or not row["modules"]:
            fail(f"prague closure {row['name']} names no loaded module")
    if section["count"] != len(entries):
        fail("prague closure count does not match its own list")
    if section["versionsSha256"] != closure.versions_digest(entries):
        fail("prague closure version digest does not match its own list")

    platforms = top["platforms"]
    if not isinstance(platforms, dict) or not platforms:
        fail("prague closure pin measures no platform")
    for key in sorted(platforms):
        row = keys(
            platforms[key],
            {
                "generated", "pythonExecutableSha256", "fileRecords", "contentSha256",
                "standardLibrary", "interpreterRuntime", "unownedSitePackages",
                "distributions",
            },
            f"pin.platforms.{key}",
        )
        if row["generated"] is not True:
            fail(f"pin.platforms.{key} is recorded but not generated")
        if not closure.is_sha256(row["pythonExecutableSha256"]):
            fail(f"pin.platforms.{key} Python executable digest is malformed")
        standard_library = closure.validate_standard_library(
            row["standardLibrary"], fail,
            label=f"pin.platforms.{key}.standardLibrary",
        )
        interpreter_runtime = closure.validate_interpreter_runtime(
            row["interpreterRuntime"], fail,
            label=f"pin.platforms.{key}.interpreterRuntime",
        )
        unowned_site_packages = closure.validate_unowned_site_packages(
            row["unownedSitePackages"], fail,
            label=f"pin.platforms.{key}.unownedSitePackages",
        )
        if standard_library["implementation"] != PYTHON_IMPLEMENTATION.lower() \
                or ".".join(standard_library["version"].split(".")[:2]) != PYTHON_SERIES:
            fail(f"pin.platforms.{key} standard library is not pinned CPython 3.11")
        names = {cell["name"] for cell in row["distributions"]}
        if names != seen:
            fail(
                f"pin.platforms.{key} measures {sorted(names)}, but the closure "
                f"pins {sorted(seen)}"
            )
        total = sum(int(cell["files"]) for cell in row["distributions"])
        if row["fileRecords"] != total:
            fail(f"pin.platforms.{key} file-record total does not match its rows")
        if row["contentSha256"] != closure.environment_content_digest(
            row["distributions"], standard_library, interpreter_runtime,
            unowned_site_packages,
        ):
            fail(f"pin.platforms.{key} content digest does not match its own rows")
    return top


def constraints_text(document: dict[str, Any]) -> str:
    return closure.render_constraints(document["semanticClosure"], header=CONSTRAINTS_HEADER)


def self_check() -> int:
    """Prove the validator rejects a pin that overstates what it pins."""

    distributions = [
        {"name": "ethereum_rlp", "version": "0.1.5", "modules": ["ethereum_rlp"]},
        {"name": "coincurve", "version": "20.0.0", "modules": ["coincurve"]},
    ]
    measured = [
        {"name": "ethereum_rlp", "files": 8, "contentSha256": "a" * 64},
        {"name": "coincurve", "files": 17, "contentSha256": "b" * 64},
    ]
    standard_library_files = [
        {"path": "stdlib/hashlib.py", "sha256": "d" * 64},
        {"path": "stdlib/json/__init__.py", "sha256": "e" * 64},
    ]
    standard_library = {
        "implementation": PYTHON_IMPLEMENTATION.lower(),
        "version": "3.11.9",
        "fileRecords": len(standard_library_files),
        "contentSha256": closure.standard_library_digest(standard_library_files),
        "files": standard_library_files,
    }
    runtime_files = [
        {"path": "basePrefix/lib/libpython3.11.dylib", "sha256": "f" * 64}
    ]
    interpreter_runtime = {
        "fileRecords": len(runtime_files),
        "contentSha256": closure.interpreter_runtime_digest(runtime_files),
        "files": runtime_files,
    }
    unowned_site_packages = {
        "fileRecords": 1,
        "contentSha256": closure.unowned_site_packages_digest([
            {"path": "sitePackages/_virtualenv.py", "sha256": "8" * 64}
        ]),
        "files": [
            {"path": "sitePackages/_virtualenv.py", "sha256": "8" * 64}
        ],
    }
    document = {
        "schema": 4,
        "lane": LANE,
        "checkout": {
            "repository": REPOSITORY, "commit": EELS_PIN, "sourceRoot": SOURCE_ROOT,
        },
        "interpreter": {
            "implementation": PYTHON_IMPLEMENTATION, "series": PYTHON_SERIES,
        },
        "provisioning": dict(PROVISIONING),
        "contentPolicy": "whereGenerated",
        "semanticClosure": {
            "policy": copy.deepcopy(CLOSURE_POLICY),
            "contentExcludes": list(closure.CONTENT_EXCLUDES),
            "bytecodePolicy": dict(closure.BYTECODE_POLICY),
            "executedLoaderPolicy": dict(closure.EXECUTED_LOADER_POLICY),
            "installerMetadataExcludes": list(closure.INSTALLER_METADATA),
            "standardLibraryPolicy": dict(closure.STANDARD_LIBRARY_POLICY),
            "interpreterRuntimePolicy": dict(closure.INTERPRETER_RUNTIME_POLICY),
            "distributions": copy.deepcopy(distributions),
            "count": 2,
            "versionsSha256": closure.versions_digest(distributions),
        },
        "platforms": {
            "macos-arm64": {
                "generated": True,
                "pythonExecutableSha256": "3" * 64,
                "fileRecords": 25,
                "contentSha256": closure.environment_content_digest(
                    measured, standard_library, interpreter_runtime,
                    unowned_site_packages,
                ),
                "standardLibrary": copy.deepcopy(standard_library),
                "interpreterRuntime": copy.deepcopy(interpreter_runtime),
                "unownedSitePackages": copy.deepcopy(unowned_site_packages),
                "distributions": copy.deepcopy(measured),
            }
        },
    }
    validate(document)

    mutants: list[tuple[str, Any]] = []

    moved = copy.deepcopy(document)
    moved["checkout"]["commit"] = "0" * 40
    mutants.append(("checkout-repointed", moved))

    unpolicied = copy.deepcopy(document)
    unpolicied["semanticClosure"]["policy"]["transitionPackages"] = []
    mutants.append(("emptied-closure-policy", unpolicied))

    unbounded_stdlib = copy.deepcopy(document)
    del unbounded_stdlib["semanticClosure"]["standardLibraryPolicy"]
    mutants.append(("standard-library-policy-dropped", unbounded_stdlib))

    bytecode_readable = copy.deepcopy(document)
    bytecode_readable["semanticClosure"]["bytecodePolicy"]["pycachePrefix"] = None
    mutants.append(("bytecode-cache-made-readable", bytecode_readable))

    loader_unbound = copy.deepcopy(document)
    del loader_unbound["semanticClosure"]["executedLoaderPolicy"]
    mutants.append(("executed-loader-policy-dropped", loader_unbound))

    unbound_runtime = copy.deepcopy(document)
    del unbound_runtime["semanticClosure"]["interpreterRuntimePolicy"]
    mutants.append(("interpreter-runtime-policy-dropped", unbound_runtime))

    restated = copy.deepcopy(document)
    restated["semanticClosure"]["distributions"][0]["version"] = "0.1.6"
    mutants.append(("version-restated-without-redigest", restated))

    unweighed = copy.deepcopy(document)
    unweighed["semanticClosure"]["distributions"].append(
        {"name": "py_ecc", "version": "8.0.0", "modules": ["py_ecc"]}
    )
    unweighed["semanticClosure"]["count"] = 3
    unweighed["semanticClosure"]["versionsSha256"] = closure.versions_digest(
        unweighed["semanticClosure"]["distributions"]
    )
    mutants.append(("named-but-never-weighed", unweighed))

    recounted = copy.deepcopy(document)
    recounted["platforms"]["macos-arm64"]["fileRecords"] = 26
    mutants.append(("file-total-disagrees-with-rows", recounted))

    repacked = copy.deepcopy(document)
    repacked["platforms"]["macos-arm64"]["distributions"][0]["contentSha256"] = "c" * 64
    mutants.append(("row-digest-disagrees-with-total", repacked))

    changed_stdlib = copy.deepcopy(document)
    changed_stdlib["platforms"]["macos-arm64"]["standardLibrary"]["files"][0][
        "sha256"
    ] = "f" * 64
    mutants.append(("changed-stdlib-byte", changed_stdlib))

    changed_runtime = copy.deepcopy(document)
    changed_runtime["platforms"]["macos-arm64"]["interpreterRuntime"]["files"][0][
        "sha256"
    ] = "0" * 64
    mutants.append(("changed-interpreter-runtime-byte", changed_runtime))

    changed_unowned = copy.deepcopy(document)
    changed_unowned["platforms"]["macos-arm64"]["unownedSitePackages"]["files"][0][
        "sha256"
    ] = "9" * 64
    mutants.append(("changed-unowned-site-packages-byte", changed_unowned))

    changed_python = copy.deepcopy(document)
    changed_python["platforms"]["macos-arm64"]["pythonExecutableSha256"] = "z" * 64
    mutants.append(("malformed-python-executable-digest", changed_python))

    unmeasured = copy.deepcopy(document)
    unmeasured["platforms"] = {}
    mutants.append(("no-platform-measured", unmeasured))

    relaxed = copy.deepcopy(document)
    relaxed["provisioning"] = {
        "tool": "pip", "command": "pip install -e .", "constraints": "",
    }
    mutants.append(("provisioning-recipe-dropped", relaxed))

    for label, mutant in mutants:
        try:
            validate(mutant)
        except closure.ClosureError:
            continue
        fail(f"prague closure self-check accepted {label}")

    # A pin whose versions are met must satisfy the in-process assertion, and a
    # pin whose versions are not met must not.
    refusals: list[str] = []
    absent = copy.deepcopy(document)
    absent["semanticClosure"]["distributions"][0]["name"] = "definitely_not_installed"
    try:
        closure.assert_pinned_versions(absent, fail, label="self-check")
    except closure.ClosureError as exc:
        refusals.append(str(exc))
    if not refusals:
        fail("prague closure self-check accepted an absent pinned distribution")

    return len(mutants) + len(refusals) + closure.self_check()


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    mode = result.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--self-check", action="store_true")
    result.add_argument("--eels-root", help="pinned EELS checkout")
    return result


def main() -> int:
    args = parser().parse_args()
    if args.self_check:
        count = self_check()
        print(f"OK — prague closure self-check: {count} mutants rejected")
        return 0

    root = resolve_root(args.eels_root)
    verify_checkout(root)
    observed = derive(root)
    series = interpreter_series(observed)
    if series != PYTHON_SERIES:
        fail(
            f"pinned EELS environment runs Python {observed['interpreter']['version']}, "
            f"pinned at the {PYTHON_SERIES} series"
        )
    if args.write:
        document = build(root, observed)
        PIN_PATH.write_text(closure.canonical_json(document), encoding="utf-8")
        CONSTRAINTS_PATH.write_text(constraints_text(document), encoding="utf-8")
        print(closure.report(observed, label="prague semantic closure"))
        print(f"OK — wrote {PIN_PATH.name} and {CONSTRAINTS_PATH.name}")
        return 0

    # Checking is not "would --write produce this file".  Content is measured
    # per platform and a platform that has never been measured must still be
    # able to run the lane, so the two halves are held to different standards:
    # the closure — membership and versions — binds everywhere, and bytes bind
    # wherever a row exists to bind them.
    try:
        committed = validate(json.loads(PIN_PATH.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read the committed prague closure pin: {exc}")

    section = closure_section(observed)
    problems = closure.compare_versions(committed["semanticClosure"], section)
    if problems:
        fail(
            "the pinned EELS environment does not match its committed closure: "
            + "; ".join(problems)
        )
    if committed["semanticClosure"] != section:
        fail("committed prague closure differs from this environment's derivation")

    expected_constraints = constraints_text(committed)
    try:
        if CONSTRAINTS_PATH.read_text(encoding="utf-8") != expected_constraints:
            fail(
                "committed prague constraints file does not render from the "
                "committed closure; run --write"
            )
    except OSError as exc:
        fail(f"cannot read the committed prague constraints file: {exc}")

    native = native_key()
    row = committed["platforms"].get(native)
    if row is None:
        print(
            f"OK — prague closure pin matches: {section['count']} pinned "
            f"distributions at their exact versions, {observed['fileRecords']} files; "
            f"content digests (including {observed['standardLibrary']['fileRecords']} "
            f"pinned executable standard-library files and "
            f"{observed['interpreterRuntime']['fileRecords']} loaded interpreter runtime "
            f"image record(s)) are not recorded for {native}, so bytes are "
            f"unverified here (run --write on {native} to record them)"
        )
        return 0
    drift = closure.compare_content(row, observed)
    if drift:
        fail(
            f"the pinned EELS environment matches its pinned versions but not the "
            f"{native} bytes recorded for them: " + "; ".join(drift)
        )
    if row["contentSha256"] != observed["contentSha256"] \
            or row["fileRecords"] != observed["fileRecords"]:
        fail(f"prague closure content digest differs for {native}")
    print(
        f"OK — prague closure pin matches: {section['count']} pinned "
        f"distributions, {observed['fileRecords']} distribution files and "
        f"{observed['standardLibrary']['fileRecords']} pinned executable standard-library files, "
        f"plus {observed['interpreterRuntime']['fileRecords']} loaded interpreter runtime "
        f"image record(s), "
        f"content verified on {native}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except closure.ClosureError as exc:
        print(f"REGRESSION — prague closure pin: {exc}", file=sys.stderr)
        raise SystemExit(1)
