import Blanc.ProxyPairUpgradeRefinement
import AxiomAudit

#full_axioms Blanc.ProxyPair.Upgrade.migration_establishes_initializedDomain
#full_axioms Blanc.ProxyPair.Upgrade.migration_sound
#full_axioms Blanc.ProxyPair.Upgrade.shared_getter_refinement
#full_axioms Blanc.ProxyPair.Upgrade.shared_setter_refinement
#full_axioms Blanc.ProxyPair.Upgrade.upgradeToAndCall_primary_realizes_migration
#full_axioms Blanc.ProxyPair.Upgrade.upgradeTo_realizes_identity
#full_axioms Blanc.ProxyPair.Upgrade.upgradeToAndCall_skipped_empty_realizes_identity
#full_axioms Blanc.ProxyPair.Upgrade.upgradeTo_identity_sound_of_admissible
#full_axioms Blanc.ProxyPair.Upgrade.throughProxy_primary_refinement
#full_axioms Blanc.ProxyPair.Upgrade.throughProxy_identity_refinement_of_admissible
#full_axioms Blanc.ProxyPair.Upgrade.fixture_exactProxyPairSharedExecution_value
#full_axioms Blanc.ProxyPair.Upgrade.fixture_throughProxy_value_refinement
#full_axioms Blanc.ProxyPair.Upgrade.upgradeToAndCall_primary_throughProxy_refinement
