import Blanc.Lift.Check

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Check.cert_check checks the system-drainer bytes. -/

namespace Blanc.Lift.SystemDrainer

open Jaune

-- Code: 29 bytes, SHA-256: 726c968f5f959a7b8a80e1147450accdab9acd928424bbfac3be941c6431024d
def code : ByteArray := ⟨#[
  0x5f, 0x5f, 0x5f, 0x5f, 0x5f, 0x73, 0x00, 0x00, 0x09, 0x61, 0xef, 0x48, 0x0e, 0xb5, 0x5e, 0x80,
  0xd1, 0x9a, 0xd8, 0x35, 0x79, 0xa6, 0x4c, 0x00, 0x70, 0x02, 0x5a, 0xf1, 0x00
]⟩

def t_0000_c0 : SFunc := (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.next (.push [] (by decide)) (.next (.push [0x00, 0x00, 0x09, 0x61, 0xef, 0x48, 0x0e, 0xb5, 0x5e, 0x80, 0xd1, 0x9a, 0xd8, 0x35, 0x79, 0xa6, 0x4c, 0x00, 0x70, 0x02] (by decide)) (.next (.reg .gas) (.next (.exec .call) (.last .stop)))))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.SystemDrainer
