import Blanc.Lift.UniswapV2Pair.Creation.Check

/-! GENERATED by scripts/lift/lift.py -- do not edit.
Jump destinations are checked against the exact runtime, one kernel decision per entry. -/

namespace Blanc.Lift.UniswapV2Pair.Creation

open Jaune

theorem jumps_0 :
    jumpsOkNode code (Cert.entries cert) t_0000_c0 [] = true := by
  rw [← jumpsOkNodeT_eq codeTries]
  decide +kernel

theorem jumps_ok : Cert.jumpsOk code cert = true := by
  unfold Cert.jumpsOk
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl
  · exact jumps_0

end Blanc.Lift.UniswapV2Pair.Creation
