import Blanc.Lift.Check

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
The producer is untrusted; Check.cert_check checks this data. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Token

open Jaune

-- Code: 30 bytes, SHA-256: 82c0844e567e223a0f8bb059883c2a1655b6d2ed00a54fce9a5bb0ef83d16cc1
def code : ByteArray := ⟨#[
  0x33, 0x54, 0x60, 0x24, 0x35, 0x90, 0x03, 0x33, 0x55, 0x60, 0x04, 0x35, 0x80, 0x54, 0x60, 0x24,
  0x35, 0x01, 0x90, 0x55, 0x60, 0x01, 0x60, 0x00, 0x52, 0x60, 0x20, 0x60, 0x00, 0xf3
]⟩

def t_0000_c0 : SFunc := (.next (.reg .caller) (.next (.reg .sload) (.next (.push [0x24] (by decide)) (.next (.reg .calldataload) (.next (.reg (.swap 0)) (.next (.reg .sub) (.next (.reg .caller) (.next (.reg .sstore) (.next (.push [0x04] (by decide)) (.next (.reg .calldataload) (.next (.reg (.dup 0)) (.next (.reg .sload) (.next (.push [0x24] (by decide)) (.next (.reg .calldataload) (.next (.reg .add) (.next (.reg (.swap 0)) (.next (.reg .sstore) (.next (.push [0x01] (by decide)) (.next (.push [0x00] (by decide)) (.next (.reg .mstore) (.next (.push [0x20] (by decide)) (.next (.push [0x00] (by decide)) (.last .return_)))))))))))))))))))))))

def cert : Cert := [
  (⟨0x0, [], 0⟩, t_0000_c0)
]

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Token
