import Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Token.Cert
import Blanc.Lift.CheckFast

/-! GENERATED by scripts/lift/lift.py (registered in scripts/lift/certificates.json) -- do not edit.
Each entry is decided against trie-backed reads of the exact runtime.
The generic equality rewrites each result to the unchanged Cert.check. -/

namespace Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Token

open Jaune

/-- Depth 5 covers all 30 runtime byte positions. -/
def codeTries : CodeTries code 5 :=
  CodeTries.ofCode code 5 (by decide +kernel) (by decide +kernel)

theorem entry_0 :
    checkNode code (Cert.entries cert) 0 0x0 [] t_0000_c0 = true := by
  rw [← checkNodeT_eq codeTries]
  decide +kernel

theorem cert_check : Cert.check code cert = true := by
  unfold Cert.check
  rw [Bool.and_eq_true]
  refine ⟨by decide +kernel, ?_⟩
  rw [List.all_eq_true]
  intro p hp
  simp only [cert, List.mem_cons, List.not_mem_nil, or_false] at hp
  rcases hp with rfl
  · exact entry_0

end Blanc.Lift.VyperNonreentrantDeployed.Vulnerable.Token
